### ISSUE TITLE
大佬.搜狗OCR貌似失效了?

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#1]
大佬.搜狗OCR貌似失效了?
还有一个问题是能不能截图识别的时候
让整个窗口稍微灰一点的息屏功能
不然不好判断是不是已经触发了
而且红色的虚线太细了很难看清
![](https://i.loli.net/2018/06/04/5b153b72c4bac.gif)
我不知道你这个右下角提醒是什么功能
我这右下角弹窗什么提示好像没有
希望可以添加头下角已经复制到剪切板的提示(而且可以选择存在的时间)
然后点击右下角提示可以直接跳转到orc界面
还有不能添加背景图片功能吗?
整体白色还是不如黑灰的...

**Comment by miaomiaosoft** [comment]
搜狗的等时间修复，腾讯、百度OCR也不错
息屏这个略复杂，我也是初学者
因为你的任务栏在左边，弹窗提示只匹配了任务栏在下面的时候才正常 
建议你装个剪切板增强的小工具，比如clipx,可以在有复制数据的时候播放提示音，有这类工具就没有在OCR上做提示和选择的问题了
啥？界面上加背景图片？类似皮肤功能吗，这个应该不会有，想尽量简洁一点

建议你把任务栏恢复原来的位置，弹窗功能可以免除频繁开启主界面，正常情况下只要按一下F4就OK了

**Comment by 990721830** [comment]
https://www.52pojie.cn/thread-692917-1-1.html
吾爱作者这个和你差不多这个有日语和韩语
不过界面没有你这个好.....

**Comment by 990721830** [comment]
这个天若OCR好像没有自动复制....
我之前用na文字识别那个有提示有息屏...
但是那个没翻译...
你这个没提示简直都气哭惹...

**Comment by miaomiaosoft** [comment]
52上的几个我看过了，也正是因为他们的界面丑，显示和复制都不方便，所以才自己弄一个
日语和韩语其实是支持的，但韩语用的编码这软件识别不了，能识别也会显示乱码，日文没问题，而且几个OCR引擎中也只有有道支持韩文，感觉除是中日英之外用到韩文的地方应该也不多

复制提示真那么重要吗？如果开启了自动复制那么每次识别都会复制并不需要提示啊，这个习惯就好了，不要强迫自己

**Comment by 990721830** [comment]
可能受之前Na文字识别的习惯...
习惯久了肯定会好的...
如果能有选择开关那是更好了...
反正要是你会弄的话弄个声音提示也可以丫?
那先用用适应再说吧

**Comment by miaomiaosoft** [comment]
你试试新版吧，
修复了搜狗OCR
支持复制识别文本+译文，应该能变相满足你要单独快捷键复制译文的要求
支持自动复制时的声音提示，不过你要自己在配置里改 A_Copy_S=1
也支持拖放图片识别了

**Comment by 990721830** [comment]
天了噜...
这么快...
简直棒死了惹...
任务栏不同方向弹窗那个如果不是很难的话
有空的时候最好也帮我修复一下惹(滑稽)

**Comment by miaomiaosoft** [comment]
你试下把 弹窗位置 改成 除右下角之外的几个选项看看

**Comment by 990721830** [comment]
都没用惹... 
自定义也没用

**Comment by 990721830** [comment]
而且我有个问题为什么点锁定之后(锁定状态:开)
点关闭弹窗为什么还是依然关闭啦
而且不能做到像便签一样随便拖动到某处锁定吗?

**Comment by 990721830** [comment]
对了...
我又有一个更方便的弹窗快捷键想法了...
不知道能不能实现...
就是比如...
左键双击弹窗直接复制当前显示文字...
右键单击弹窗直接切换原文和翻译...
左键单击(或者单击滚轮)弹窗直接显示中译英输入框...

**Comment by miaomiaosoft** [comment]
锁定只是禁止弹窗在15秒左右自动关闭
随意拖动涉及的操作逻辑太多，不好弄
我这试了下任务栏放左边后弹窗改成右中是正常的啊，你可能修改后没重启软件吧

弹窗快捷键想法可能没法增加，因为有一个功能叫弹窗穿透，这个会导致鼠标点不到文字之外的部分，其实六个按钮已经够快捷了
