### ISSUE TITLE
字体颜色只有黑和黄吗？字体只有雅黑吗？

### ISSUE THREAD

**Issue by tt3736035** [miaomiaosoft/PandaOCR#10]
字体太粗了，看得很费力，我调了宋体、仿宋什么的，没效果。

**Comment by miaomiaosoft** [comment]
字体是标准粗细，可以试下楷体相对细点，此设置只对弹窗字体有效，主窗口的编辑框默认雅黑不能改
弹窗字体的内部颜色（非边框黑色）可以在配置文件内修改 “弹窗字体颜色=0”
把0改成十进制的颜色值就行，比如 33023

**Comment by tt3736035** [comment]
颜色会改了，但是弹窗字体改成楷体还是太粗了，怎么办?

**Comment by miaomiaosoft** [comment]
截图看看有多粗？
我这觉得不粗啊
![QQ截图20190314101346](https://user-images.githubusercontent.com/4084875/54326633-f8a6a480-4641-11e9-9a14-d43af2428c3c.jpg)

**Comment by tt3736035** [comment]
我也想发截图的，怎么发？

**Comment by miaomiaosoft** [comment]
把图片拖到这里打字的地方会自动上传

**Comment by tt3736035** [comment]
![%S9IK}AN2BMXJ65(JVNL)$N](https://user-images.githubusercontent.com/38688389/54326772-8f736100-4642-11e9-805c-a7b53e11df96.png)

**Comment by tt3736035** [comment]
这是调了楷体了 还是粗

**Comment by tt3736035** [comment]
WIN10 64

**Comment by tt3736035** [comment]
![) VJ)GA(8TGMQ}34XB5_WCT](https://user-images.githubusercontent.com/38688389/54326824-d4979300-4642-11e9-89a7-c6aee8ebfa74.png)
英文是一样

**Comment by miaomiaosoft** [comment]
颜色最好不要深色，因为边框已经是深色了，你这样肯定会显得粗了

**Comment by tt3736035** [comment]
我用默认的黄色 感觉刺眼
调了这么久其它颜色都是很粗的，
弹窗背景能调吗？或者推荐几个低调的颜色？

**Comment by miaomiaosoft** [comment]
下个版本我试下加个边框开关，不加边框也许就不“粗了”

**Comment by tt3736035** [comment]
支持
