### ISSUE TITLE
有些游戏在游戏内快捷截图功能会失效

### ISSUE THREAD

**Issue by Reisen123** [miaomiaosoft/PandaOCR#100]
窗口化也不行，必须要先切出正常桌面再按快捷键才行，比如坦克世界

**Comment by miaomiaosoft** [comment]
手工修改配置：
热键类型=1

有些游戏会禁用其他程序的热键，另外应该要管理员权限运行

**Comment by Reisen123** [comment]
> 手工修改配置：
> 热键类型=1
> 
> 有些游戏会禁用其他程序的热键，另外应该要管理员权限运行

好的，我改一下试试

**Comment by Reisen123** [comment]
> 手工修改配置：
> 热键类型=1
> 
> 有些游戏会禁用其他程序的热键，另外应该要管理员权限运行

管理员运行完美解决
