### ISSUE TITLE
我用的2.45发现2个严重问题和1个改进意见，希望能改进

### ISSUE THREAD

**Issue by hamibobo123** [miaomiaosoft/PandaOCR#102]
1、经常无法识别字体或者数字有点倾斜的验证码，用百度OCR，搜狗OCR和腾讯OCR都有这种问题
，要识别很多次才能通过，看能不能提供验证码的OCR识别方案

2、连续用脚本识别多次后，例如十几次，每次识别的过程大概4秒左右，识别的内容就是4个数字组成的验证码，经常出现pandaocr死掉，没反应，必须从任务管理器关闭进程，然后重启才行。在多次识别方面，软件应该还有缺陷，不知道是软件内存溢出还是越界导致的异常

3、希望能够提供一个供其他软件或者脚本使用的API接口，让其他软件或者脚本直接调用pandaocr的接口，进行识别。就是pandaocr对当前的主要功能（例如截图识别）分别封装一个接口给代码开发者使用，目前你只是提供给手动用户使用，这个希望你能改进，非常感谢

这个软件做的还是非常不错的，真心的给你点赞。如果能把上面几个问题解决一下，真的是爱死你了：）

**Comment by miaomiaosoft** [comment]
1. 猜测你用的次数过于频繁而被引擎限制调用，程序默认用的就是演示版，不适合频繁使用！如果需要频繁使用应该自己申请或购买API版的ID和KEY。
2. 卡死的问题可能和弹窗有关，这个尝试解决过，但无果，你可以关掉弹窗试试，并启用识别后自动复制功能。
3. 接口调用都很简单，你要是软件开发者直接去引擎的网站看文档写入自己的程序中就可以了，还更快，不需要先经过我来调用

**Comment by hamibobo123** [comment]
1、也没有频繁使用，每次就识别几次而已，并非成百上千次

**Comment by miaomiaosoft** [comment]
不知道你还在不在用这个工具
看你描述应该是专门用来识别验证码上
其实吧，这类文字OCR虽然勉强能识别验证码，但它们毕竟不是专门干这个的，识别率并不会太高，所以你说的多次才能通过的问题应该就在这里，你的这种需求应该接入那种打码平台的接口
卡死的问题主要怀疑是弹窗，但你又是关的，另外比较可疑的是文本朗读和截图时窗口是否显示状态
可以试试关掉朗读，和将窗口关闭至托盘
因为我看有一个用来机翻游戏的播主这样频繁用着大半个小时也挺稳定的
