### ISSUE TITLE
2.45截图像素不精准，请修正，希望增加识别结束标识

### ISSUE THREAD

**Issue by hamibobo123** [miaomiaosoft/PandaOCR#103]
1、使用截图识别的时候，按住鼠标左键画框截图后，发现截图的区域和选定的区域不一样，向左偏移了两个像素，上下方向没注意，每次识别的时候不是很精准，和截图前的预先设计不符，这个麻烦作者仔细校正一下截图区域像素的偏移的问题。我们追求的是perfect，不能只是手动识别，大差不多就行了
2、希望能增加一个识别结束后的标志，要不然有时候1秒就有结果，有时候3秒，不确定，希望识别动作完成后，不论结果怎么样，以某种方式（不要声音提示）告诉使用者一下，最好能给个变量，返回个true或者false以告诉使用者识别结束了。

**Comment by miaomiaosoft** [comment]
1. 确实有这个小问题，要不你启用高级截图试试，那个应该是准的
2. 这个提示是有的，在配置里叫“加载动画”，你改成非0的数值就能开启，识别的时候会在屏幕左下显示，识别完成后消失，算是一种提示吧

**Comment by hamibobo123** [comment]
1、你既然知道有问题，希望在后续版本修复一下，这个应该不难，不能明知有问题，就放那里对吧，或者你就同步一下高级截图的精准度就可以了。高级截图每次都要选择打勾，有点不方便，你懂的，好累，这个问题不着急，你有空的时候，顺便改一下就可以了，画框的边框线最好沿用高级截图的边框线，比较细，好看

**Comment by miaomiaosoft** [comment]
尝试帮你修复了截图像素不对的问题，至于边线粗细，很早的时候是很细的，只有1像素，但是太细了也不太好辨别，所以改成2像素，这个保持不变。
其实高级截图也不一定截图完要点那个勾，直接双击截图区域也可以完成截图，习惯下也挺好用的。

下载：
[PandaOCR.zip](https://github.com/miaomiaosoft/PandaOCR/files/4261360/PandaOCR.zip)
