### ISSUE TITLE
截图的像素有偏差，修改后的版本还是不对

### ISSUE THREAD

**Issue by hamibobo123** [miaomiaosoft/PandaOCR#104]
上次你发的那个版本，上次下载了，一直没时间测试，今天仔细的测试了一下，发现还是有问题。可能是你没有理解我的问题的意思。
1、首先截图的像素位置和使用者设计的有偏移，你用那个特别的工具大漠工具，才能看得出来，否则肉眼看不出来，你百度一下就可以找到一个大漠工具，很方便，你没有的话，可以联系我，我给你
2、要明确一点截图的画框线，建议能使用1个像素，真没必要使用2像素，发自内心的建议，就改为高级截图的线的粗细，感觉非常好，这个问题还是以建议为主，主要看你的意思。还有就是画框线所占的像素也应该在截图后的图片中截取下来，但实际没有截取并保留框线所占像素的图样，这个麻烦一定要改一下，你品你细品，截图是不是这个感觉和意思
3、你改后，再发出来我测试一下，不要怕麻烦，咱工具都做了这么多功能了，也付出了很多努力，希望它能更加完美，其实就是想截图截的精准一点，这样才能识别的更加到位。因为这个工具不一定全部都是手动截图识别，有时候也可以自动化工具进行截图识别，这时候就需要截图更加精确对吧

**Comment by miaomiaosoft** [comment]
我太好奇你到底是拿这个做什么用，肉眼看着没问题就应该不是个问题，而且这个主要也只是做为识别段落文本用而已，对识别结果没有影响！

1像素对我个人来说太细了，在有些分辨率更高的屏幕下更看不清，2像素是个比较合适的宽度，高级截图虽然是1像素，但是它实现了高亮截图区域，这样就算0像素也是能分辨的，而我这个没有，以我个人水平也实现不了。

抱歉，首先感谢你这么热心提出改进建议，但这个像素的问题在我看来真是个完全可以忽略的问题
另外，这个工具其实基本是停止更新了，在最后一个版本的更新日志有写，可能你没注意
我知道你是个完美主义，其实我更是，你从配置中那么多细节项目应该也能感觉到，但就是因为太需要完美而又发现有些东西因自己水平或是编程语言本身的问题实现不了才放弃更新

**Comment by hamibobo123** [comment]
好吧，非常理解你，那还是保持最后一个正式发布的版本2.45吧，像素就不要像上次帖子里贴的版本那样变动了，保持最初的2.45原样吧。其实用起来也没问题，可以用另一种方法折中一下也行的，呵呵，非常感谢。做个实用工具确实不易。真心的给这个工具点个赞！！
如果你能做个语音识别小工具，就是语音控制电脑干活的，让他干嘛就干嘛的那种，灵活点的，不要太死板，那就太好了

**Comment by jinhaoyue** [comment]
作者大大脾气好好……摸摸
