### ISSUE TITLE
0和O的识别不太准

### ISSUE THREAD

**Issue by steveJJJ** [miaomiaosoft/PandaOCR#106]

**Comment by miaomiaosoft** [comment]
这个我无法处理，因为调用的是在线引擎

**Comment by steveJJJ** [comment]
嗯嗯，感谢您回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miao_miao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 晚上7:17
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"焦小豪"<837226902@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 0和O的识别不太准 (#106)





 
这个我无法处理，因为调用的是在线引擎
