### ISSUE TITLE
关于百度OCR的通用识别API问题

### ISSUE THREAD

**Issue by jinhaoyue** [miaomiaosoft/PandaOCR#107]
作者你好，我在使用panda OCR 2.45的过程中发现1=百度云_API版 使用的是我的文字识别（高精度）的额度而非通用文字识别，但是我设置成3=AI高精度的时候调用的是我的通用文字识别，不过不能识别日语（我感觉它应该是直接识别中文，然后就是一堆乱码了）。

作者大大求翻牌啊，不然我只能自己想办法写一个了嘤嘤嘤

**Comment by miaomiaosoft** [comment]
只有1是API版，使用自己的ID和KEY
其他的应该都是演示版，3也是演示版
要设置日语你应该在识别语言那选择jp

**Comment by jinhaoyue** [comment]
我选择了jp，但是我选了3之后还是乱码（不过演示版不重要，我主要是玩游戏用的所以还是用自己个人API）
作者大大如果有空的话（特别不好意思，看到你说了不更新了），能不能把API的请求改成通用文字识别啊，因为高精度一天只有500次免费请求量，通用的一天有5w次，两个识别率其实差不多

**Comment by miaomiaosoft** [comment]
API版或其他引擎不乱码？
乱码截图来一张

**Comment by jinhaoyue** [comment]
![Screenshot (145)](https://user-images.githubusercontent.com/28560615/78050335-a8b29100-73ae-11ea-9926-769c4739216c.png)
![set](https://user-images.githubusercontent.com/28560615/78050354-acdeae80-73ae-11ea-9427-d1e91cba4921.JPG)
这是我设置成 百度OCR 3=AI高精度的翻译图

**Comment by jinhaoyue** [comment]
![Screenshot (146)](https://user-images.githubusercontent.com/28560615/78050865-735a7300-73af-11ea-8f39-ddee60e13669.png)
这是我用我自己的API 设置成1的样子，然后翻译都是用一个，我觉得应该就是OCR那里出问题了

**Comment by miaomiaosoft** [comment]
![BaiduShurufa_2020-4-1_0-51-45](https://user-images.githubusercontent.com/4084875/78053305-fcbf7480-73b2-11ea-9b02-953e3af92930.jpg)

好久没用我都忘了，百度的演示版是不支持识别语言的，它只能默认auto自动识别，只有API版才行
帮你修改了下，API版换成通用识别了
[PandaOCR.zip](https://github.com/miaomiaosoft/PandaOCR/files/4410427/PandaOCR.zip)

**Comment by jinhaoyue** [comment]
感谢，辛苦了
（其实可以更新个充电通道的，我相信还是有挺多人想要给你充电的，比如我）

**Comment by jinhaoyue** [comment]
另外前两天我在淘宝上看到有人售卖你的软件，链接如下：
https://m.tb.cn/h.VTiflN6?sm=99031e
我已经举报了，不过如果你介意的话还是本人去处理一下比较好

**Comment by miaomiaosoft** [comment]
谢谢，我说咋后台用户统计越来越多每天都五千多了
看他也没卖出几个，本身这软件也基本放弃，就算了，不过我准备利用更新方式提醒一下用户这东西其实不用买 ...

**Comment by innerbeast** [comment]
> 谢谢，我说咋后台用户统计越来越多每天都五千多了
> 看他也没卖出几个，本身这软件也基本放弃，就算了，不过我准备利用更新通道提醒一下用户这东西其实不用买 ...

完全可以商业化的这个软件，不想商业化给个打赏通道也行啊，粉丝们一包烟钱还是掏得起的

**Comment by miaomiaosoft** [comment]
> > 谢谢，我说咋后台用户统计越来越多每天都五千多了
> > 看他也没卖出几个，本身这软件也基本放弃，就算了，不过我准备利用更新通道提醒一下用户这东西其实不用买 ...
> 
> 完全可以商业化的这个软件，不想商业化给个打赏通道也行啊，粉丝们一包烟钱还是掏得起的

这软件问题太多，我又没本事搞定，加上都准备停更了，不太好意思要捐助
等日后脸皮厚点再说吧~
