### ISSUE TITLE
希望能增加DeepL接口

### ISSUE THREAD

**Issue by Dorl121** [miaomiaosoft/PandaOCR#108]
https://www.deepl.com/home
DeepL 人工翻译训练的机器翻译，也提供API接口，不知道能不能添加到软件中？

**Comment by miaomiaosoft** [comment]
添加的话应该不麻烦，但这是个国外服务，延迟我测了下在国内有点高，体验可能不比搜狗那些好
如果添加的话你是要演示版还是API版，它这个API版应该是要收费的

ping -4 www2.deepl.com

正在 Ping 733868e706dd40d3a4a0588fc39b3df8.pacloudflare.com [172.65.212.243] 具有 32 字节
的数据:
来自 172.65.212.243 的回复: 字节=32 时间=213ms TTL=54
