### ISSUE TITLE
接受捐助列表公示

### ISSUE THREAD

**Issue by miaomiaosoft** [miaomiaosoft/PandaOCR#109]
待编辑~

**Comment by xiaozhaizz** [comment]
嘻嘻嘻害怕被人知道真实姓名的我赶紧把自己的用户名换了23333
不知道是不是因为前段时间我在b站录了教程，然后用的人变多了……本来是录游戏实况的，然后一直被人问用什么软件于是就录了一个教程……
目前我把捐助通道也放在我的视频里了，不知道作者你介意不……
主要是现在github被墙了很多人其实是上不了的

**Comment by miaomiaosoft** [comment]
> 嘻嘻嘻害怕被人知道真实姓名的我赶紧把自己的用户名换了23333
> 不知道是不是因为前段时间我在b站录了教程，然后用的人变多了……本来是录游戏实况的，然后一直被人问用什么软件于是就录了一个教程……
> 目前我把捐助通道也放在我的视频里了，不知道作者你介意不……
> 主要是现在github被墙了很多人其实是上不了的
> https://www.bilibili.com/video/BV1Vt4y1U7Es/
> 这是我的视频地址，作者大大如果你觉得哪里不好的我也可以删

当然不介意了，还得感谢你的支持和推荐！
视频我有看，感觉你特聪明，注释少没教程，但软件的使用基本上你都挺正确，比如更改自定排序，我都认为没人会知道这是个啥。

另外我补充一些好像没被公开的小技巧：
- 程序界面上存在的设置多数是可以实时生效的，比如设置语言、设置固定截图规则，更换引擎这类，只有更改热键或者保存设置时才点保存。
- 有时手工更改了配置又不想重启软件可以试试右键点击界面左上角图标重载配置，不要左键。
- 从演示版临时更改为API版可以右键点击引擎选择组合框。
- 要关闭朗读可以把朗读内容选择为第一项禁用，将朗读音量调整为零虽然也可以，但如果不关的话它还是会下载并朗读一遍，会些许影响识别速度。
![BaiduShurufa_2020-4-3_14-3-50](https://user-images.githubusercontent.com/4084875/78329367-17147080-75b4-11ea-9c23-d1887c188920.jpg)
- 觉得按快捷键识别麻烦可以把鼠标移到屏幕左上角来触发识别，默认配置有启用，也可以改为其他位置。
- 智能识别和智能翻译那几个都用的演示版，不使用API版。
- 朗读你可能不用但我也说一下，智能朗读那同一个选项有重复是因为一个是边下边播，另一个是先尝试边下边播，如果无效则使用先下再播以保证朗读有效。
- 大概就这些了，教程做的很棒，通俗易懂，换我就做不来，总之再次感谢你的支持！


当然还有最重要的一点，声音超好听~

**Comment by xiaozhaizz** [comment]
get了更多技巧~
前两天发现还能设置快捷键来快速切换截图的序列，感觉用于临时翻译某些游戏选项挺方便的
过两天我再录一个相关技巧的视频

**Comment by miaomiaosoft** [comment]
> get了更多技巧~
> 前两天发现还能设置快捷键来快速切换截图的序列，感觉用于临时翻译某些游戏选项挺方便的
> 过两天我再录一个相关技巧的视频

不知道你还在不在用
最近研究了下自动固定截图
有在用的话能不能帮忙测试一下

固定截图的配置项下增加了三个参数：
`[固定截图]
自动固定截图热键=F8键
自动固定截图延迟=4000
自动固定截图精度=98`

可以自己添加，也可以删除旧配置文件让程序自动生成
三个配置都需要手工设置
热键格式参照之前的热键写法
延迟数值为毫秒
精度指前后两次截图如果小于这个相似度则重新识别


[PandaOCR_TEST.zip](https://github.com/miaomiaosoft/PandaOCR/files/4495828/PandaOCR_TEST.zip)

**Comment by rehigain** [comment]
感谢！中国软件行业先锋，我们看到了中国未来的希望！

**Comment by torotJ** [comment]
之前捐助过，如何联系你拿key呢

**Comment by miaomiaosoft** [comment]
> 之前捐助过，如何联系你拿key呢

软件里点反馈-进群找群主

**Comment by yuhu-code** [comment]
> 捐助时建议备注：PandaOCR+留言或建议(可选)，方便区分整理，谢谢大家支持，PandaOCR因你而更好！~
> 另：为了表示感谢，对于捐助过的朋友现在可以附赠您一个KEY用来激活捐助版专享功能，如果需要可以随时联系作者认领！
> 
> 名字	备注（WX）
> f*g	*
> *境	*
> *河	*
> s*y	开发不易，感谢大佬！
> *桦	谢谢再次更新
> w*i	加油，很喜欢这软件。
> *杰	*
> *七	*
> *生	*
> *森	软件带来诸多方便感谢
> *阳	*
> T*n	继续更新软件
> *哥	*
> *🍀	PandaOCR 超级好用！
> *y	*
> *衣	*
> *羽	*
> *文	很好用，望继续更新~
> j*e	把所有零钱都给你了
> * `	*
> *坚	*
> *瓜	*
> *北	pandaocr you-hengh
> *空	*
> *点	*
> *安	等有钱了一定发大的
> n*e	支持一下
> C*_	*
> *龙	谢谢
> *弘	*
> *生	*
> *桦	作者加油 程序很好
> *斌	感谢，pandaocr
> l*t	PandaOCR支持作者
> S*l	谢谢 很实用
> *枫	大*辛苦
> 明*	加油，软件很棒
> C*X	*
> *里	很用的工具，感谢
> *库	*
> Z*j	怎么说，一块是一块
> *逆	PandaOCR-yunni
> *言	PandaOCR，很棒很棒
> *萝	感谢作者大大
> *L	软件如此优秀👍
> *神	特别好用的小软件
> *境	图床功能很好用
> H*n	PandaOCR+软件超棒！
> F*	*
> z*x	*
> *雨	了表心意
> *舟	谢谢，莫嫌少
> W*r	*
> *!	感谢作者~谢谢~
> *远	*
> *酒	支持pandocr
> *空	PandaOCR谢谢你的工具
> *鹏	*
> *潮	继续加油
> *子	PandaOCR有道...祥子
> *羽	*
> *僮	*
> *日	很好的软件，望坚持
> **	论文救星❤️
> m*i	*
> 张*y	PandaOCR
> *松	*
> *落	感谢大*！
> h*m	*
> *星	PandaOCR希望做的更好
> W*a	*
> *宇	谢谢大*的开发
> *鸣	PandaOCR真好用
> *儿	*
> *子	PandaOCR 绵薄之力
> E*1	*
> *主	*
> *梦	*
> *O	*
> r*s	PandaOCR加油
> *梁	好用好用，支持维护
> *园	*
> a*X	PandaOCR捐助
> 标*9	*
> E*e	PandaOCR 谢谢你
> *柠	学生党，意思一下
> *流	*
> *m2	PandaOCR超好用
> *兴	*
> *雪	谢谢作者*大
> *景	*
> 李*H	*
> *白	*
> *远	小小支持一下
> *黑	*
> *羊	PandaOCR很有用
> *生	*
> *成	有支持才更持久，感谢
> *磊	意思一下
> *川	*
> *主	*
> *[]	*
> *民	*
> *凡	*
> *复	软件很不错
> *萤	软件很好用
> *野	PandaOCR+开发不易
> *士	*
> *东	*
> *家	用了很多次，捐一下
> C*d	*
> J*n	PandaOCR+用一次赞助
> *名	学生党赚钱回来继续
> *人	666
> *🐘	*
> *笋	*
> *住	*
> *然	*
> *信	*
> R*y	PandaOCR 很好用！
> *仔	软件很好用！加油
> Z*j	*
> *牌	PandaO C R谢谢你
> *F	*
> *玛	PandaOCR 感谢大*
> M*S	谢谢开发OCR
> G*r	*
> *影	*
> t*i	*
> *成	*
> *影	*
> *醇	PandaOCR 喜欢你
> A*8	*
> *蛋	开发者加油
> *-	*
> *[]	*
> *军	*
> *生	*
> 8*t	*
> *坚	大*恰瓶阔乐
> *从	聊表心意
> *息	*
> *克	*
> R*k	请大*喝阔乐
> *欣	软件很好用，谢谢分享
> *博	PandaOCR 谢谢大*
> *！	还没赚钱😂😂
> *江	*
> *埃	加油！
> *、	翻译真的不错，
> *木	*
> *平	*
> *心	*
> *原	弘扬互联网精神，加油
> *胖	*
> *成	*
> *爽	*
> *泰	*
> *L	*
> *😘	*
> *恒	感谢分享这么好的软件
> *[]	*
> *易	*
> E*e	*pandocr捐助
> *计	*
> d*l	有其他语言识别就好了
> *子	感谢作者大*的OCR
> G*a	*
> *飞	一人一毛钱，哈哈哈
> *飞	没想到吧，又捐了一毛
> x*i	*
> *司	PandaOCR-望越做越好
> *倍	*
> *伍	*
> S*L	*
> *鲲	*
> *神	PandaOCR
> *	PandaOCR
> *白	*
> A*S	为什么不开通第一项？
> F*o	初次遇到，了表心意
> *中	*
> *默	*
> c*a	*
> *宇	*
> *好	*
> z*x	*
> *士	*
> *💕	软件很好，支持一下
> *院	*
> w*n	*
> C*u	真滴🦥 /:beer
> *火	*
> *良	*
> *火	*
> *[]	工具很好用，学习使我
> W*D	感谢❤️
> *~	*
> *。	开发不易！感恩！
> *柳	*
> *官	*
> *溢	Panda没使用先赞为敬
> *🐯	*
> Y*O	加油加油
> *君	PandaOCR好用，支持
> ~*~	PandaOCR微信全部家当
> *铭	棒的软件，很有趣的人
> *良	*
> A*3	*
> *凯	*
> *班	熊猫ovt
> M*r	ocr很好用，加油
> *七	*
> k*d	*
> z*x	*
> *雾	*
> *男	*
> *定	*
> *）	加油pandaocr
> S*G	1元支持
> Y*	*
> *~	*
> s*k	*
> *~	*
> *子	*
> *东	pandaocr加油
> *寰	*
> *之	加油
> R*y	*
> *毕	*
> *告	*
> *客	*
> *本	*
> *海	*
> *子	谢谢刚刚下载先支持
> *山	*
> *[]	*
> *香	*
> *友	*
> *弟	*
> X*y	*
> A*n	*
> *凭	*
> *春	*
> *银	*
> *帝龙	*
> *l	*
> *强	捐助
> *枫	*
> M*e	*
> *长	*
> *象	*
> *宝	*
> *岐	*
> *跑	*
> *鱼	*
> V*n	*
> L*n	*
> *鸿	*
> *禁	*
> 磊*i	*
> *雨	*
> S*a	看了你昨天的更新谢谢
> B*y	点击打开没显示再点才
> *鸥	谢谢维护
> *[]	*
> *世	*
> *聪	*
> r*l	*
> *猪	*
> 王*t	*
> *生	*
> c*t	*
> P*e	*
> L*i	PandaOCR+还不错！
> *噫	*
> R*l	*
> W*A	PandaOCRcola支持一下
> *~	*
> *航	*
> *。	*
> *乎乙	*
> *银	感谢分享
> *橙	*
> *车	继续加油！谢谢帮助
> *亮	*
> H*a	*
> *马	*
> R*J	*
> *婷	多谢，软件很好用
> *狮	PandaOCR项目捐助
> *流	*
> *仔	*
> A*i	*
> *[]	*
> *线	*
> *。	*
> *大	*
> *头	*
> Z*e	谢谢大佬
> *金	*
> *漏	“PandaOCR”+谢谢制作
> *利	*
> *石	*
> *笑	*
> *易	*
> *E	*
> *意	*
> *果	*
> *妮	*
> 1*1	*
> *z	*
> *鹏	谢谢
> *！	PandaOCR开发不易努力
> *质	*
> *白	*
> f*)	*
> *糖	*
> *~	*
> *平	*
> A*4	绵薄之力，软件好用！
> *哥	*
> *好	*
> *旁	钱少别介意
> *象	*
> *伟	*
> *浩	*
> _*_	感谢你的软件
> *。	*
> *雨	捐助
> *好	PandaOCR超级棒
> L*`	*
> *超	*
> *狼	*
> F*o	感谢，以表心意
> *海	*
> *l	*
> *狮	pandaocr+很赞，祝好
> *[]	PandaOCR加油
> S*l	熊猫捐助
> h*c	*
> *泮	*
> *人	*
> *鸟	*
> *鱼	PandaOCR 加油奥利给！
> *碭	*
> *戏	*
> *—	*
> *坠	*
> *啊	穷学生一个
> *鱼~	*
> z*x	*
> *溪	*
> W*n	*
> W*m	*
> *宁	感谢pandaocr软件
> *粹	*
> *人	*
> 2*0	*
> *刻	*
> *仔	谢谢你的软件。
> R*	*
> *意	*
> 博*2	工具捐赠
> *l	*
> *跑	*
> *羽	只要在，必支持
> L*n	*
> *鹏	*
> *七	*
> L*L	*
> *？	热键/显示or隐藏_弹窗
> J*n	*
> M*t	*
> h*e	*
> *哲	PandaOCR+感谢付出
> *。	制作不易
> *坚	*
> *语	*
> *春	*
> *悠	感谢研发者
> a*X	PandaOCR
> *白	*
> n*l	*
> *伟	spaceocr api 谢谢
> *道	开发不易，聊表心意
> *风	*
> 星*6	*
> *	谢谢你他妈的真好用！
> *送	OCR好用，帮了大忙！
> *A	*
> 王*8	*
> *	*
> *朗	*
> *事	*
> *海	*
> *峰	*
> C*s	*
> *仔	*
> *契	很好用，感谢
> ***	*
> *旭	PandaOCR+一点心意
> *Tel	*
> *里	*
> *焱	*
> *清	谢谢提供优秀工具！
> #*#	*
> l*e	*
> *必	*
> *
> *宇	*
> *雨	*
> *董	*
> *诗	*
> *羊	*
> *旺	大*666
> *觉	pandaocr用着还不错
> 朱*s	*
> *师	*
> a*n	*
> *坏	*
> *J	感谢辛苦付出，很好用
> *城	*
> C*s	*
> *华	*
> *白	*
> H*w	支持一下，加油。
> *兮	*
> *哥	*
> *仰	感谢大*
> *女匊	您费心了，鼓励下。
> *￥￥	*
> *灵	*
> 名字	备注（ZFB）
> 一路向北	*
> 郑草川琥珀主	*
> 石*禾	*
> 夜夜夜夜光	*
> 爱你ML	*
> 赤行	*
> qb	PandaOCR，yes
> Pluviophile	*
> RP.WINER	*
> 前进	*
> 胡*琦	*
> *子旺	ocr非常好用，希望能一直更新下去！
> *毅	牛逼，我爱你
> *达理	*
> *国栋	“PandaOCR”期待更多方便的功能
> *沐风	PandaOCR 0404更新前时有闪退
> *颖月	*
> *吉泽	谢谢您的pandocr，希望能一直做下去
> *昌杰	PandaOCR感谢分享好工具，小小心意
> *颖帅	感谢您为大家提供这么好用的软件，开发不易
> *颖帅	“PandaOCR”软件好用，再次捐助
> *祥	*
> *捷	加油，我不能白嫖这么好的软件
> *阳克红	*
> *美杉	*
> *成	*
> *家豪	辛苦了，熊猫OCR很准确。继续加油
> *伟	*
> *沧海	panda ocr
> *嘉伟	*
> *涵	好东西就要支持
> *汉璋	PandaOCR牛*
> *正杰	*
> *继	PandaOCR
> *雨	PandaOCR 谢谢大*开发软件❤️
> *薇	ltem
> *一鸣	*
> *泽昊	PandaORC
> *嘉伟	*
> *桐年	pandaocr 💪💪💪人💪
> *敬其	支持，支持工作
> *树彬	很方便使用
> *意达	就冲你抛弃吾爱这波，我捐了。
> *远程	*
> *建伟	*
> *臣	*
> *文超	*
> *伟同	感谢您的软件
> *雨	*
> *雪强	*
> *永泰	加油
> *阳	软件非常好，感谢你的制作与分享
> *金鑫	PandaOCR 学生党绵薄之力一起加油
> *悦	*
> *轩	*
> *灿	*
> *正霖	捐助微薄，分享无价，加油
> *祥	*
> *炳宽	加油！PandaOCR！
> *华	pandaOCR
> *新民	*
> *泰笙	支持作者
> *清源	感谢开发
> *伟涛	*
> *宇航	pandaocr的支持
> *楫	*
> *华锋	*
> *瑞文	软件超好用，捐助开发者一顿早餐！
> *艺	PandaOCR+很好用
> *湘伟	panda-OCR捐助
> *韵琪	虽然很少但是支持一波！！
> *嘉勋	*
> *津厚	PandaOCR 软件很棒哦！
> *昊	*
> *伟	*
> *海辉	*
> *晓洪	*
> *晓燃	支持一下
> *龙辉	*
> *俊淼	*
> *晓庚	*
> *俊峰	PandaOCR希望建群交流字有限
> *泽东	很感谢你的PandaOCR
> *文军	pandaocr不错滴，快捷方便
> *宇豪	*
> *晓宇	*
> *海龙	*
> *伟	*
> *威	为了赚钱择手段啊
> *琨	希望能将识别出的逗号改为中文格式或自选
> *兴梁	*
> *冬	*
> *明	一点意思，加油！
> *红生	*
> *炜涛	PandaOCR 免费不易，聊表心意
> *衡	*
> *宇	*
> *祯松	您这软件很好用，谢谢
> *宁	pandaocr这个软件非常有趣！
> *思微	*
> *振锋	*
> *磊	*
> *艳伟	作者**加油
> *永全	*
> *秋明	*
> *玉婷	*
> *晓岚	喵酱技术牛，关键有颗有趣的灵魂~
> *名东	非常感谢你们，一群无私奉献，希望你们做得
> *超	*
> *志强	Pandaocr 感谢你的好软件
> *志鹏	大佬厉害了
> *振山	*
> *宏亮	支持关注panda
> *明	*
> *秀	*
> *烁之	PandaOCR 开发不易
> *嫒	*
> *耿峰	好软件，加油！
> *彦平	*
> *哲	感谢，panda真的很好用
> *吉鹏	感谢，好工具
> *秋云	*
> *承鑫	软件很好，以后有能力定会再次捐助
> *双彬	*
> *晓艳	*
> *方明	*
> *斌	*
> *昱中	*
> *国清	*
> *创	PandaOCR 感谢努力 请继续加油
> *伟	*
> *俊鹏	*
> *洪伟	加油，小小心意不要嫌弃
> *正	*
> *尚伦	*
> *晓江	本来准备选菊花，但是**收不到。
> *枫	*
> *志伟	*
> *云翔	PandaOCR加油，学生党支持！
> 再次谢谢支持
> *文艺小青年  *    很好用呢

**Comment by sanbyzhu** [comment]
我应该是那个坚的了哈，我来取key哈，我的邮箱是1354325610@qq.com

**Comment by kingaoshuai** [comment]
我的留言是,微薄,但是心意,来拿KEY了1262427019@qq.com

**Comment by 1048657400** [comment]
不管多少是个意思来拿KEY了1048657400@qq.com

**Comment by dont-beat-up-the-doctor** [comment]
感谢作者的辛劳和付出，承认劳动的价值并给予经济和荣誉上的补偿才是社会前进的动力，再次感谢作者。求key一枚。

tianwenzhi@outlook.com 
--

**Comment by sqlmap3** [comment]
392368969@qq.com key

**Comment by SBIAMNMM** [comment]
不管多少，是个意思，来拿KEY了。237201574@qq.com

**Comment by dont-beat-up-the-doctor** [comment]
谢谢啊，绵薄之力而已，敢问如何取key？



发自我的小米手机
在 SBIAMNMM <notifications@github.com>，2020年10月2日 下午3:22写道：

不管多少，是个意思，来拿KEY了。237201574@qq.com<mailto:237201574@qq.com>

**Comment by sarayaya** [comment]
开发不易，辛苦维护，非常感谢

**Comment by Andy766** [comment]
感谢 顺便求key体验一下新功能

**Comment by blanca0101** [comment]
开发不易，多少是个意思，顺便来拿个KEY，谢谢。
blanca01@163.com

**Comment by sarayaya** [comment]
已捐助过，谢谢开发者，但我电脑是高分辨屏，使用起来不是很方便

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: blanca0101 <notifications@github.com>
发送时间: Tuesday, October 20, 2020 3:43:57 PM
收件人: miaomiaosoft/PandaOCR <PandaOCR@noreply.github.com>
抄送: sarayaya <dumplingtj@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [miaomiaosoft/PandaOCR] 接受捐助列表公示 (#109)


开发不易，多少是个意思，顺便来拿个KEY，谢谢。
blanca01@163.com<mailto:blanca01@163.com>

―

**Comment by paulxm** [comment]
软件带来诸多方便, 多少是个意思，顺便来拿个KEY，谢谢。paulxm@126.com

**Comment by 18078111024** [comment]
已捐助1.68+9.9，微信名：老友牛杂
43088806@qq.com

**Comment by chenxin0397** [comment]
2020.11.07支付宝已捐助一点心意，非常支持该软件！
chenxin0397@163.com

**Comment by Zach-001** [comment]
微信已捐助一点心意，非常支持该软件！   微信名：杨振
bj1311@163.com

**Comment by kaomabil** [comment]
一点心意，非常支持该软件！微信名：a御龙科技
kaomabil@163.com     or    745913246@.com

**Comment by xlaohu** [comment]
拿key，65282107@qq.com

**Comment by tophdo** [comment]
微信已捐助，感谢开发者！微信名：Do_  1192765373@qq.com

**Comment by linhaiwen777** [comment]
微信已捐助，微信名：林海·文苑    邮箱：64177435@qq.com

**Comment by eee1987** [comment]
大佬，感谢江湖救急。

**Comment by eee1987** [comment]
大佬感谢江湖救急，支付宝已捐助拿key。1204794621@qq.com

**Comment by suzhejun** [comment]
持续关注，刚实习，等我拿到第一桶金后会微信持续捐助 微信名：苏柘。xiaobosq@gmail.com

**Comment by miaomiaosoft** [comment]
> 持续关注，刚实习，等我拿到第一桶金后会微信持续捐助 微信名：苏柘。[xiaobosq@gmail.com](mailto:xiaobosq@gmail.com)

抱歉，我没发现你在微信里有捐助记录，你应该用微信的留言功能给我发邮箱！

另外，再提醒各位，请在捐助后使用相应支付程序的留言或备注功能留下邮箱，而不应在此公共页面回复，这会泄漏你的个人信息，而且也不便于我验证，此处的领KEY留言是不会回复和发KEY的！
谢谢！

**Comment by YAVAWA** [comment]
微信已留言邮箱,请发送一枚KEY,转账单号:10001071012020112601230785698516

**Comment by suxiwan** [comment]
感谢开发人员，学生党一枚只能请大佬喝瓶冰红茶了，求大佬发下KEY   473316223@qq.com  ~!

**Comment by 0383838** [comment]
03838@163.com,备注了

**Comment by malu2335** [comment]
微信已捐助，感谢大佬的软件！微信名2335

**Comment by raver** [comment]
2020/12/26，微信已捐助，感谢您的软件，请继续开发！微信名lowceremony

**Comment by meiling011** [comment]
微信已捐助，感谢软件!微信名美美^^
邮箱：517762279@qq.com

**Comment by meiling011** [comment]
还没发KEY我呢？

**Comment by 0383838** [comment]
问错人了，我不是作者



在 2021-02-03 17:17:48，"meiling011" <notifications@github.com> 写道：

还没发KEY我呢？

**Comment by Naco** [comment]
非常感谢作者能够开发这么好用的软件，坚持不易，请加油！已经通过支付宝捐助。

**Comment by yhj127** [comment]
微信转账单号，10001071012021032700581305220280。微信名：虫虫。
请发送一枚KEY,谢谢
邮箱：1251978834@qq.com

**Comment by qq626447** [comment]
软件带来诸多方便, 多少是个意思，顺便来拿个KEY，谢谢1315924836@qq.com

**Comment by 1131693691** [comment]
已捐助，不过忘了备注，ZFB有留言，嘻嘻来取个KEY，1131693691@qq.com

**Comment by lseaJK** [comment]
微信捐助，感谢pandaOcr，来拿KEY了，谢谢大佬们！1417854702@qq.com

**Comment by 1090004161** [comment]
微信捐助过了 这个软件对于学生党来说非常好用感谢作者大大

**Comment by todayfinez** [comment]
微信已捐助，求key，猫祖，todayfinez@126.com

**Comment by jpcj96yj3** [comment]
微信捐助过了 不过忘了备注 这个软件非常好用感谢作者大大
KEY如何拿  jpcj96yj3@163.com   橡胶熊   支付宝   喵喵酱

**Comment by Jimmypratice** [comment]
直接微信先捐助了才看到要备注， 软件非常好用，感谢！
43713762@qq.com，jimmy，微信支付

**Comment by ie328** [comment]
微信已捐助. 求key. 8462183@qq.com

**Comment by kkk555kkk333** [comment]
支付宝已捐助，邮箱号644185507@qq.com。谢谢创作者

**Comment by HyperClockUp** [comment]
已经捐助，wx nooo UpdateSuccess 求key 924093945@qq.com

**Comment by wanhang189** [comment]
1

**Comment by facaigege** [comment]
微信  2021年12月24日14:37:30     支付 
金额 9.9
支持一下邮箱1162732225@qq.com
谢谢

**Comment by attenlearner** [comment]
我也捐了，小小意思，但对我用处很大，微信号是lockker，时间应该是2022-01-15, 1:04左右，当时没有留言的选项。很想弄个key版本的，谢谢了！加油呀！

**Comment by xiaozhaizz** [comment]
我是金昊月。你的邮件我已收到，我会尽快查阅

**Comment by attenlearner** [comment]
刚才只自报家门，忘记邮箱了，heyul@163.com
