### ISSUE TITLE
弹窗只有黄、黑、红三色吗？

### ISSUE THREAD

**Issue by tt3736035** [miaomiaosoft/PandaOCR#11]
这版本字体清晰很多，但我试了很多只有这3色，像蓝、绿这些数值是多少？
![批注 2019-03-15 105041](https://user-images.githubusercontent.com/38688389/54405012-33770e00-4710-11e9-942a-4ee1a2490529.jpg)

**Comment by miaomiaosoft** [comment]
https://www.shuxuele.com/hexadecimal-decimal-colors.html

取Decimal十进制数值

**Comment by tt3736035** [comment]
![BFCUF62L LC%M_13M@70FXI](https://user-images.githubusercontent.com/38688389/54406751-3c6ade00-4716-11e9-9cba-605e69cc60a3.png)
蓝色选不出来，绿色正常

**Comment by tt3736035** [comment]
205还是红色
![TPL@}PX)NITNB8 3WQ1K)JH](https://user-images.githubusercontent.com/38688389/54406775-5c020680-4716-11e9-9e1b-0ab958f9b3a4.png)

**Comment by miaomiaosoft** [comment]
![QQ截图20190315114732](https://user-images.githubusercontent.com/4084875/54407295-41c92800-4718-11e9-9ff9-fb1572fed30a.jpg)
那网站取的数值好像有问题，没找到其他的在线取色网站
你装个FSCapture用这个取

**Comment by tt3736035** [comment]
明白了，谢谢。
