### ISSUE TITLE
右下处边缘贴合的东东,能支持位置移动不?

### ISSUE THREAD

**Issue by dnknn** [miaomiaosoft/PandaOCR#113]
右下处边缘贴合的东东,能支持位置移动不?
![image](https://user-images.githubusercontent.com/10995302/79018522-956da580-7ba6-11ea-9531-8a9117ab2973.png)
如上图, 不知怎么叫法,有没术语称呼来着...暂且叫为[ABC]吧...

✎建议[ABC]能够实现停留的位置:
### ②不好实现就支持到⚙CONFIG.ini配置文件里给个参数改改..ini里貌似没有发现到这个DIY参数.
到时就可以移到边缘中间位置去,感觉右下角有点偏野了✿(。◕‿◕。)✿

**Comment by miaomiaosoft** [comment]
这个叫弹窗按钮
原则上不能移，但事实上也可以
增加它的高度就行了
![BaiduShurufa_2020-4-11_16-46-51](https://user-images.githubusercontent.com/4084875/79039478-18791500-7c14-11ea-85bc-496317c1f7b6.png)

弹窗是以右下角为准点向内展开
而弹窗按钮位置是弹窗高度的一半
也就是屏幕高度-任务栏高度-（弹窗高度/2）
假设屏幕高度1080，要移到中间，就填500吧，但同时弹窗的内容会提高到从顶部开始

**Comment by dnknn** [comment]
叫弹窗按钮和弹窗文字不能分别设置高度位置吗?

**Comment by miaomiaosoft** [comment]
两个是一体的，这样更美观，文字在底部按钮却在中间这不太科学
而且由于弹窗部分的代码实现比较混乱，除非下一次再次重写程序的时候才会考虑做出更改

**Comment by miaomiaosoft** [comment]
下个版本会增加一个其他调试参数：弹窗按钮位置:1
1=上 2=下 0=中

改完后如：其他调试参数=讯飞发音:1@x_yiping|备用引擎日志:1|手贱开关:1|弹窗按钮位置:0|
