### ISSUE TITLE
一钮多用再强化

### ISSUE THREAD

**Issue by dnknn** [miaomiaosoft/PandaOCR#114]
发现很多按钮都支持左键+右键,交互设计Good,简约又高效.
因此, 建议作者也可以考虑再支持鼠标中键点击,
有的地方可以再加鼠标中键点击即滚轮按键点击的动作行为哦!
从而继续高歌猛进...!!!

![image](https://user-images.githubusercontent.com/10995302/79071242-48581380-7d0d-11ea-8e34-ee6b194e856a.png)
✎建议 上图之弹窗按钮的鼠标中键点击用来打开主界面.
实用场景:当程序最小化到托盘去了, 然后截图OCR的弹窗结果出来后,
此时 对弹窗按钮的中键点击即可呼出主界面, 用来快速选择复制.
比弹窗按钮的右键复制更快.

**Comment by miaomiaosoft** [comment]
这个应该不难实现，下个版本会考虑

**Comment by miaomiaosoft** [comment]
已发新版
