### ISSUE TITLE
✎一个牛逼轰轰+顶级实用的建议劲爆来袭!

### ISSUE THREAD

**Issue by dnknn** [miaomiaosoft/PandaOCR#115]
✎一个牛逼轰轰+顶级实用的建议劲爆来袭!
这个偏向极客专业点, 不过也很简单,尝试后定会爱不释手, 因为足够实用智能!

高级截图=1
![image](https://user-images.githubusercontent.com/10995302/79071433-5195b000-7d0e-11ea-869f-83efa5bcf07b.png)
能否实现对Chrome内核的Web网页页面的HTML元素的自动识别, 
相当于在Chrome浏览器里按<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>的操作效果.

截图时自动选取浏览器窗口的页面HTML元素, 当然这需要手动启用Chrome命令行.
 chrome://accessibility，勾选 Native accessibility API support 以及 Web accessibility 
Chrome 每次关闭后都会重置这些设置，如希望每次打开Chrome时自动启用，就加上启动命令 --force-renderer-accessibility到快捷方式或浏览器自身的命令行设置,就可以一劳永逸!
![image](https://user-images.githubusercontent.com/10995302/79071612-43945f00-7d0f-11ea-87d9-7bfccbcf541c.png)

![image](https://user-images.githubusercontent.com/10995302/79071638-6757a500-7d0f-11ea-85bb-fd2c5d2b66a8.png)
![image](https://user-images.githubusercontent.com/10995302/79071670-90783580-7d0f-11ea-934d-ac93e68932dc.png)

如需具体体验,请参考体验下Snipaste截图
Snipaste - 截图 + 贴图 https://zh.snipaste.com

**Comment by miaomiaosoft** [comment]
老哥很有想法，但是这个我想了下似乎更适合截图软件，OCR可能不太需要
为了让文本识别更精准，我们应该手工截取不包括其他元素，比如图片，图标在内的纯文本图像

看样子Snipaste是已经实现了你说的，其实可以两者结合使用
像这样设置
![QQ截图20200413000438](https://user-images.githubusercontent.com/4084875/79073673-755ef300-7d1a-11ea-93a5-71d1774b79dd.jpg)
使用Snipaste截图后OCR就会自动识别了

**Comment by dnknn** [comment]
> 监听图像识别也是好主意
可是依旧很有局限性啊, 那个选项是监听剪贴板📋里的任何图像, 而不是监听其他截图程序的截图.
导致这个选项一般都不会去固定开着的, 除非不会对图像文件Ctrl+或右键⇒复制., 包括网页上的图像文件.
### 所以呢,大侠 想想有没更好的实现方式.  最好是PandaOCR自身截图支持chrome://accessibility

**Comment by miaomiaosoft** [comment]
没有更好的实现方式
一是我觉得这是没太大必要的
二来主要我不是专业程序员，不是大侠，你说的我能力有限不知道咋实现（高级截图其实是用的微信截图组件，我写的是非高级截图）
这个工具我也是边学边做的，你提的建议其实都挺不错，但我只能满足一些不那么复杂的东西
