### ISSUE TITLE
剪切识别Ctrl+V

### ISSUE THREAD

**Issue by dnknn** [miaomiaosoft/PandaOCR#116]
![image](https://user-images.githubusercontent.com/10995302/79108187-6161d280-7da8-11ea-9b81-542a88088df6.png)
焦点:focus在PandaOCR主界面窗口时候,
📋剪贴板图像识别功能, 建议增加<kbd>Ctrl</kbd>+<kbd>V</kbd>
   正因为是图像, 所以<kbd>Ctrl</kbd>+<kbd>V</kbd>不影响任何其他正常事件动作或交互行为.
如果支持,鼠标:hover在`剪切识别`的按钮上的描述文案也同步改为`Ctrl+V识别复制图片`

此外, 这里右键认为应该要加入 `剪切识别`    `图像识别`
![pic20200413_171957](https://user-images.githubusercontent.com/10995302/79109507-0e3d4f00-7dab-11ea-8b8e-a682906d17e2.png)

**Comment by miaomiaosoft** [comment]
那就多此一举了，鼠标都移上去了，再点一下不就行了，何必再按键盘

右键那也是多余的，旁边不远就有的按钮没必要再弄到菜单上
