### ISSUE TITLE
PandaOCR.v2.52 运行不了

### ISSUE THREAD

**Issue by gitccl** [miaomiaosoft/PandaOCR#119]
我第一次用这个软件，下载了PandaOCR.v2.52，解压到桌面后，双击运行就出现了下面错误，而且exe文件从桌面消失了，把exe文件解压到其他盘也是一样。
![20200419224530](https://user-images.githubusercontent.com/60637740/79690902-8e722180-828f-11ea-827b-9e7e8647e02b.png)

**Comment by gitccl** [comment]
是杀毒软件的原因吗，我电脑没安装其他什么杀毒软件啊，也没报毒什么的

**Comment by miaomiaosoft** [comment]
被杀了呗，没另外安装杀毒那就是WIN10自带的杀毒

**Comment by hcw022703** [comment]
### 

> [`_****_`](url)
