### ISSUE TITLE
GOOGLE翻译不支持多字数吗？

### ISSUE THREAD

**Issue by tt3736035** [miaomiaosoft/PandaOCR#12]
我才翻译80个单词，谷歌没结果出来，其它的都能出结果。

**Comment by miaomiaosoft** [comment]
![QQ截图20190315115111](https://user-images.githubusercontent.com/4084875/54407417-b4d29e80-4718-11e9-863b-403aa25702bc.jpg)

测试没问题，另外提问最好带上你那80个单词，我才好找到问题
还有，不需要开新帖，在旧帖回复就行了

**Comment by tt3736035** [comment]
This method can be easily extended for specific separation of other HPAI viruses or biological targets by replacing the aptamers with the antibodies or biological recognition elements against the targets. More importantly, the method is very promising for separating the targets from a sample with a large volume in a shorter time to achieve a more sensitive detection.

**Comment by tt3736035** [comment]
In this study, a 3D-printed magnetophoretic device was successfully developed and was the first time used for separating H5N1 viruses by using magnetic nanoparticles and specific aptamer to the best of our knowledge. Both COMSOL and MATLAB were used to simulate the trajectories of the magnetic nanoparticles-H5N1 virus complexes with an optimal flow rate of the carrier of 120 μL/min. The proposed magnetophoretic system was demonstrated to be able to separate the H5N1 viruses with the separation efficiency up to 88% in a continuous-flow condition.

**Comment by tt3736035** [comment]
这85个，谷歌翻译不了

**Comment by tt3736035** [comment]
老大，在吗？是什么问题呢

**Comment by miaomiaosoft** [comment]
先用其他的吧  推荐搜狗
这个问题似乎和文字里的特别字符有关

**Comment by miaomiaosoft** [comment]
已更新修复，重新下载

**Comment by tt3736035** [comment]
更新在哪，还是2。12呀

**Comment by miaomiaosoft** [comment]
就是2.12  但下载地址的文件是更新过的
不过还发现了新BUG，还是等明天的2.13吧

**Comment by tt3736035** [comment]
OK
