### ISSUE TITLE
不开源就别在github发

### ISSUE THREAD

**Issue by woshiniming007** [miaomiaosoft/PandaOCR#120]
github是一个开源社区，免费是为了促进开源。

不开源就别厚脸皮在这里发软件！

**Comment by miaomiaosoft** [comment]
虽然是开源社区，但不开源也并不违反GITHUB社区协议
其实这软件开发初期就想过开源，但之前开源另一个软件并没得到预想的效果，再加上像您这类素质较低的伸手党甚至直接拿到淘宝倒卖的见过不少，所以开源的事暂时不想！

**Comment by buptlzc** [comment]
> github是一个开源社区，免费是为了促进开源。
> 
> 不开源就别厚脸皮在这里发软件！

不喜欢就别用，开源不是理所当然的，开源或者免费，都是为了分享，不是为了让你白嫖还指责开发者分享的不够多
