### ISSUE TITLE
2.52版本，点击截图识别按钮时，窗体不能自动隐藏了

### ISSUE THREAD

**Issue by yin-jeff** [miaomiaosoft/PandaOCR#121]
如标题，  2.51还是可以的

**Comment by miaomiaosoft** [comment]
#截图隐藏窗口：0=禁用 | 1=启用 | 截图时如果主窗口为可视状态将暂时隐藏主窗口
截图隐藏窗口=0

**Comment by yin-jeff** [comment]
谢谢
________________________________
发件人: miao_miao <notifications@github.com>
发送时间: 2020年4月21日 18:12
收件人: miaomiaosoft/PandaOCR <PandaOCR@noreply.github.com>
抄送: yin-jeff <yinxu.cn@outlook.com>; Author <author@noreply.github.com>
主题: Re: [miaomiaosoft/PandaOCR] 2.52版本，点击截图识别按钮时，窗体不能自动隐藏了 (#121)


#截图隐藏窗口：0=禁用 | 1=启用 | 截图时如果主窗口为可视状态将暂时隐藏主窗口
截图隐藏窗口=0

―
