### ISSUE TITLE
建议加2个小功能，可以使软件体验好很多

### ISSUE THREAD

**Issue by buptlzc** [miaomiaosoft/PandaOCR#122]
1.增加简洁模式（可在主窗口和简洁模式之间转换）——只保留翻译窗口，软件会显得干净很多，占用面积小
2.置顶，翻译软件在简洁模式下保持置顶的话，阅读文献时，只要复制即可实时看到翻译，方便很多
3.感觉弹窗模式稍稍有点鸡肋，字太小，有点看不清楚，无法挪动位置，且可用上面的方式更好的代替

最后，这些只是本人在使用后的一点建议，pandaOCR是我目前用过最喜欢的OCR+翻译软件！感谢大大！

**Comment by miaomiaosoft** [comment]
是这样的，预览弹窗其实就是个简洁模式
弹窗文字的大小样式都是可以在配置里调整的，看不清可以加大加粗
虽不能直接挪动位置，但改变弹窗的宽高是可以变相做到移动位置的

你常用翻译的话可以试试勾选文本监听并自动翻译：
![BaiduShurufa_2020-4-22_8-1-35](https://user-images.githubusercontent.com/4084875/79926454-8cff4f80-846f-11ea-9807-a6f089684b80.jpg)

那样就不用开主窗口了，只要复制它就会自动翻译

**Comment by buptlzc** [comment]
嗯嗯，好的，谢谢大大
