### ISSUE TITLE
搜狗api使用问题

### ISSUE THREAD

**Issue by qingcheqin** [miaomiaosoft/PandaOCR#123]
翻译可以用，识别用不了

**Comment by miaomiaosoft** [comment]
API版？是的话需要提供KEY给我测试
演示版测试可用

**Comment by qingcheqin** [comment]
演示版可用
无奈的是搜狗的翻译跟识别用的是同一个api，结果。。。翻译可用，识别就不行

在线获取PID&amp;KEY

PID：&nbsp;156a68c35b79620407e2c6ddc0976cde
Key：&nbsp;4ce73c8f48dbe4fcdb6316262ce4badc





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miao_miao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 上午9:53
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"花影"<935248950@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 搜狗api使用问题 (#123)





 
API版？是的话需要提供KEY给我测试
 演示版测试可用

**Comment by miaomiaosoft** [comment]
测试失败，我感觉不是接口问题，翻译和识别的KEY应该不能是同一个吧，你在后台再看看

**Comment by qingcheqin** [comment]
所以很奇怪，我还以为是我操作的问题，教程看了好几遍的说





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miao_miao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 上午10:08
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"花影"<935248950@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 搜狗api使用问题 (#123)





 
测试失败，我感觉不是接口问题，翻译和识别的KEY应该不能是同一个吧，你在后台再看看

**Comment by miaomiaosoft** [comment]
我这测试返回的错误都是翻译的错误码
一般是不能共用的，得重新弄个OCR的KEY

**Comment by qingcheqin** [comment]
行，我再去问问，


之前进了官方客服群，他们说是需要使用官方的插件，不然无法提供技术支持哦。。。就不正面回答我。。。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miao_miao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 上午10:12
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"花影"<935248950@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 搜狗api使用问题 (#123)





 
我这测试返回的错误都是翻译的错误码
 一般是不能共用的，得重新弄个OCR的KEY

**Comment by qingcheqin** [comment]
你好，之前测试的错误码还在吗？，我发给搜狗的识别看一下





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miao_miao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 上午10:12
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"花影"<935248950@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 搜狗api使用问题 (#123)





 
我这测试返回的错误都是翻译的错误码
 一般是不能共用的，得重新弄个OCR的KEY

**Comment by miaomiaosoft** [comment]
> 你好，之前测试的错误码还在吗？，我发给搜狗的识别看一下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"miao_miao"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月22日(星期三) 上午10:12 收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;; 抄送:&nbsp;"花影"<935248950@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 搜狗api使用问题 (#123) 我这测试返回的错误都是翻译的错误码 一般是不能共用的，得重新弄个OCR的KEY — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

哥们，这不是API的问题，你应该用OCR的KEY而不是共用，后台是不能建OCR的KEY还是你不会弄？
