### ISSUE TITLE
更新右下角提醒点击软件闪退

### ISSUE THREAD

**Issue by peasshoter** [miaomiaosoft/PandaOCR#124]
> //==========================Crash Report(YangTuSoft)===========================
> Crash Program： [YTSOFT][xfnet.dll]
> 
> DLL Information:
> 
> Exception Code : C0000005 ACCESS_VIOLATION
> Crash Address: 0B304AF8 01:C000000F
> 
> CPU:
> EAX:0B304AF8
> EBX:00000000
> ECX:00DD0D68
> EDX:00000000
> ESI:0B304AF8
> EDI:00000000
> CS:EIP:0023:0B304AF8
> SS:ESP:002B:0018FBB0 EBP:0018FBD8
> DS:002B ES:002B FS:0053 GS:002B
> Flags:00010206
> 
> PDB Search Path:.;E:\downloads\Programs\
> 
> Call Stack:
> Address Frame Function SourceFile
> 0B304AF8 0018FBAC FrmAddr Failed:870000:00000000
> 755D62FA 0018FBD8 FrmAddr Failed:870001:000062FA C:\windows\syswow64\USER32.dll
> 755D6D3A 0018FC50 FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
> 755E0D3F 0018FC88 FrmAddr Failed:870001:00010D3F C:\windows\syswow64\USER32.dll
> 755E853A 0018FCA8 FrmAddr Failed:870001:0001853A C:\windows\syswow64\USER32.dll
> 0045D3A7 0018FCD8 FrmAddr Failed:870001:0005C3A7 E:\downloads\Programs\PandaOCR.exe
> 0045D16D 0018FD08 FrmAddr Failed:870001:0005C16D E:\downloads\Programs\PandaOCR.exe
> 0045D05C 0018FD30 FrmAddr Failed:870001:0005C05C E:\downloads\Programs\PandaOCR.exe
> 0045D416 0018FD7C FrmAddr Failed:870001:0005C416 E:\downloads\Programs\PandaOCR.exe
> 755D6D3A 0018FDF4 FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
> 755D77C4 0018FE54 FrmAddr Failed:870001:000077C4 C:\windows\syswow64\USER32.dll
> 755D7BCA 0018FE64 FrmAddr Failed:870001:00007BCA C:\windows\syswow64\USER32.dll
> 00589699 0018FE74 FrmAddr Failed:870001:00188699 E:\downloads\Programs\PandaOCR.exe
> Stack Param Info:
> 
> Call Stack:
> Address Frame Function SourceFile
> 0B304AF8 0018FBAC FrmAddr Failed:870000:00000000
> 
> 755D62FA 0018FBD8 FrmAddr Failed:870001:000062FA C:\windows\syswow64\USER32.dll
> 
> 755D6D3A 0018FC50 FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
> 
> 755E0D3F 0018FC88 FrmAddr Failed:870001:00010D3F C:\windows\syswow64\USER32.dll
> 
> 755E853A 0018FCA8 FrmAddr Failed:870001:0001853A C:\windows\syswow64\USER32.dll
> 
> 0045D3A7 0018FCD8 FrmAddr Failed:870001:0005C3A7 E:\downloads\Programs\PandaOCR.exe
> 
> 0045D16D 0018FD08 FrmAddr Failed:870001:0005C16D E:\downloads\Programs\PandaOCR.exe
> 
> 0045D05C 0018FD30 FrmAddr Failed:870001:0005C05C E:\downloads\Programs\PandaOCR.exe
> 
> 0045D416 0018FD7C FrmAddr Failed:870001:0005C416 E:\downloads\Programs\PandaOCR.exe
> 
> 755D6D3A 0018FDF4 FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
> 
> 755D77C4 0018FE54 FrmAddr Failed:870001:000077C4 C:\windows\syswow64\USER32.dll
> 
> 755D7BCA 0018FE64 FrmAddr Failed:870001:00007BCA C:\windows\syswow64\USER32.dll
> 
> 00589699 0018FE74 FrmAddr Failed:870001:00188699 E:\downloads\Programs\PandaOCR.exe
> 
> 每次更新，点通知就闪退，也没打开网页

**Comment by miaomiaosoft** [comment]
你哪下的软件？
你帖的错误最上面这条“Crash Program： [YTSOFT][xfnet.dll]”
这DLL我都没见过，肯定不是这软件的
谷歌了下似乎是一个加密软件
你最好想想软件是在哪下的，把网址给我看看是不是被人加了料

**Comment by peasshoter** [comment]
我再github上下载的啊

**Comment by peasshoter** [comment]
这好像是autodesk验证服务的dll

**Comment by miaomiaosoft** [comment]
"YangTuSoft"谷歌出来可能是这个：http://www.yangtusoft.cn/
企业安防
因为目前只有你一人报告这个问题，所以应该不会是程序的BUG
