### ISSUE TITLE
还是之前的问题，方便提供一下错误码吗？

### ISSUE THREAD

**Issue by qingcheqin** [miaomiaosoft/PandaOCR#125]
我也不太懂，官网的人说要错误码，谢谢~

**Comment by miaomiaosoft** [comment]
你就问他们翻译的KEY能不能用来OCR

**Comment by miaomiaosoft** [comment]
![BaiduShurufa_2020-4-24_12-12-14](https://user-images.githubusercontent.com/4084875/80174337-ef4d8100-8624-11ea-96fe-06d3c8f520c1.png)

这样点，重新获取OCR用的KEY
两种KEY获取的地方都不一样，连QQ群都不是同一个
估计你跑去翻译群问OCR 。。。

**Comment by miaomiaosoft** [comment]
我注册了个帐号跑去看了一下确实是一个KEY但共用服务
错误码：

{
    "detect": {
        "zly": "zly",
        "detect": "zh-CHS",
        "errorCode": "0",
        "language": "中文",
        "id": "e16b644a-8268-42a6-bc3f-335292461c8e",
        "text": "null"
    },
    "translate": {
        "qc_type": "1",
        "zly": "zly",
        "errorCode": "10",
        "index": "content0",
        "from": "zh-CHS",
        "source": "sogou",
        "text": "null",
        "to": "en",
        "id": "e16b644a-8268-42a6-bc3f-335292461c8e",
        "dit": "j",
        "orig_text": "null",
        "md5": ""
    }
}

**Comment by miaomiaosoft** [comment]
那不用反馈了，可能是我这的问题，少加了一个附加协议

**Comment by miaomiaosoft** [comment]
[PandaOCR.zip](https://github.com/miaomiaosoft/PandaOCR/files/4526678/PandaOCR.zip)
你用这个版本试试

**Comment by qingcheqin** [comment]
好的，我试试，群我应该没加错~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "miao_miao"<notifications@github.com&gt;; 
发送时间: 2020年4月24日(星期五) 中午12:37
收件人: "miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;; 
抄送: "花影"<935248950@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [miaomiaosoft/PandaOCR] 还是之前的问题，方便提供一下错误码吗？ (#125)





 
PandaOCR.zip
 你用这个版本试试

**Comment by qingcheqin** [comment]
可以啦。换回以前的版本就可以啦~





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miao_miao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 中午12:37
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"花影"<935248950@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 还是之前的问题，方便提供一下错误码吗？ (#125)





 
PandaOCR.zip
 你用这个版本试试

**Comment by miaomiaosoft** [comment]
什么以前的版本，得用上面刚发的这个版本

**Comment by qingcheqin** [comment]
现在最新用的不是2.52，发的这个不是2.5以前的版本？，不过能用就行，谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miao_miao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 中午12:45
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"花影"<935248950@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 还是之前的问题，方便提供一下错误码吗？ (#125)





 
什么以前的版本，得用上面刚发的这个版本

**Comment by miaomiaosoft** [comment]
行行行， 你确定用的上面发的就行！~
