### ISSUE TITLE
关于竖排文本识别的优化

### ISSUE THREAD

**Issue by Manshaoco** [miaomiaosoft/PandaOCR#126]
能否考虑增加对竖排文本识别的优化功能，谢谢！

**Comment by miaomiaosoft** [comment]
不是有OCR引擎可以识别吗

**Comment by Manshaoco** [comment]
> 不是有OCR引擎可以识别吗

诶，不好意思，没看到比较直接的竖排文本的设置项目，具体有哪些OCR引擎可以自动识别竖排文本呢？还不太会使用相关设置(/捂脸笑哭)

**Comment by miaomiaosoft** [comment]
我个人是用不到识别竖排文字，你可以自己一个个试一下，我记得有几个支持的，这里说的是演示版
API版本应该都支持
这个不用什么设置，引擎如果支持就会自动识别竖排并返回正确的文本

**Comment by Manshaoco** [comment]
> 我个人是用不到识别竖排文字，你可以自己一个个试一下，我记得有几个支持的，这里说的是演示版
> API版本应该都支持
> 这个不用什么设置，引擎如果支持就会自动识别竖排并返回正确的文本

好的，我挨个试了下，发现有道和Space这俩引擎可以识别日文竖排文字，Space的准确率更高。非常感谢开发者大大！
