### ISSUE TITLE
一些建议功能

### ISSUE THREAD

**Issue by zelda0079** [miaomiaosoft/PandaOCR#13]
1. 其实我不太懂得怎样使用 (4.支持截取识别固定区域，例如可帮助翻译英文游戏/软件中的单词或队友聊天记录), 不知道能不能第1次截图后, 之后勾选启用固定截图, 下次按F4自动截取同区域? 现在启用固定截图确实是会截一个屏幕中间的固定位置, 不知道怎样更改位置

2. 软件窗口不能改变形状, 配合其他窗口化游戏不太方便

3. 弹窗能不能加选项将右则改为下方, 左右并排翻译前后文本?

**Comment by miaomiaosoft** [comment]
![QQ截图20190331221009](https://user-images.githubusercontent.com/4084875/55290142-cc40a580-5401-11e9-8c8f-a049b4cd90e7.jpg)

1. 鼠标放上去就会显示简单的使用提示了

2. 改变形状？我不太理解，固定截图和弹窗显示还不够方便吗，根本就不需要显示或操作主窗口，一切由按一次快捷键完成

3. 可以设置显示两者，识别和译文，左右并排意思是要弄两个弹窗，一个在屏幕左边显示识别一个在屏幕右边显示译文？

**Comment by zelda0079** [comment]
1. 简单来说, 就是按了"启用固定截图", 然后F4, 只会截到屏幕中间某个区域, 而这个区域不能自己选择或改变(我试了取消, 用F4选取, 再勾选之后还是截固定区域, 不是我选的), 所以说可能是我不知道怎样用, 鼠标对着"启用固定截图"没提示

第2点和第3点是相近的, 例如我调了1600*900游戏窗口, 我工作列惯了放右侧, 对于像我这类的人, 如果可以将翻译窗口放在游戏窗口下方会更好, 尤其文字本身是左至右的, 相比剩下320像素放翻译文, 我觉得能放下方会比较好
所以为什么建议增加左右两侧功能

**Comment by zelda0079** [comment]
第1点我看懂了, 谢谢

**Comment by miaomiaosoft** [comment]
弹窗是以右下方为中心点，不是右边，可以调整弹窗宽/高度
如果你是觉得弹窗位置应该再往下一些，那可以调低弹窗高度
如果觉得弹窗应该在左边，那调整弹窗宽度，如屏幕宽度 1600 那弹窗宽度也应该在1600左右，不过长文本显示效果可能不太好

弹窗叠加到窗口前面是没关系的，因为弹窗背景本身也是透明的，希望这个你还是适应一下

**Comment by zelda0079** [comment]
果然是我不太懂用, 我以为右侧两个框框是指弹窗, 试了一下, 原来还有黄色字的小框框弹出在右下角, 那没问题了, 很好用, 谢谢
