### ISSUE TITLE
请问搜狗OCR是怎么做到这么高精度的

### ISSUE THREAD

**Issue by MrAlphne** [miaomiaosoft/PandaOCR#130]
我自己也调用了搜狗OCR的接口，但是识别的内容不完整

**Comment by miaomiaosoft** [comment]
请举例，我帮你看看

**Comment by MrAlphne** [comment]
十分感谢！！
![5_4](https://user-images.githubusercontent.com/37764056/80782568-5204c680-8ba9-11ea-94d7-c59c9e3417a7.png)
比如说这张图，我用您的软件就可以全部识别出来，但是我用[https://deepi.sogou.com/doccenter/textcognitivedoc?fr=process](url)里的python调用demo，返回的结果只有目录前面的标题，没有页码。
[title.txt](https://github.com/miaomiaosoft/PandaOCR/files/4562520/title.txt)

**Comment by miaomiaosoft** [comment]
不好意思，PY我不太懂，如果完全按官方例程做的但结果不对那可能例子的问题，如果不是例子的问题尝试检查这部分是否出错：

image = "iVBORw0KGgoAAAANSUhEUgAAA3cAAASeCAIAAADqv..."  #图片二进制内容进行base64编码后的字符串
imageShort = image[0:1024]
sign = md5(pid+service+salt+imageShort+key); 

登陆后台也可以找到他们的QQ群，你可以问问

**Comment by MrAlphne** [comment]
好的，我之前申请过加他们的群了，只不过现在还没有通过。
请问您在用户上传图片后有对图片进行过处理吗，比如说缩小尺寸之类的。

十分感谢您的耐心回复！

**Comment by miaomiaosoft** [comment]
没做缩小，只做了放大和转码成JPG缩小图片体积
当图片宽高小于100时放大到100，因为有些识别引擎不支持太小的图

**Comment by MrAlphne** [comment]
好的，再次感谢您的耐心解答！
