### ISSUE TITLE
鼠标滑到右上角调用这个建议设置开关可以关闭那种。

### ISSUE THREAD

**Issue by wenyida** [miaomiaosoft/PandaOCR#132]
习惯右上角双击关闭窗口，每次都能跳出来识别。麻烦这个功能设置个开关。

**Comment by miaomiaosoft** [comment]
右上角？我记得默认开启的是左上角啊
这个功能是有现成开关的，编辑下配置文件改成0：
#边角触发截图：0=禁用 | 1-4=启用 | 分别为左上角、右上角、左下角、右下角 | 鼠标停留在屏幕角落时触发截图
边角触发截图=1
