### ISSUE TITLE
WIN7系统中打开执行文件后跳出警告菜单 关闭后程序主页面变模糊

### ISSUE THREAD

**Issue by liuye1992** [miaomiaosoft/PandaOCR#134]
![微信图片编辑_20200507060711](https://user-images.githubusercontent.com/50910435/81228432-06c73980-9029-11ea-9f8e-e2add794092e.jpg)

**Comment by liuye1992** [comment]
另外繁体识别还无法实现么？感觉程序内引用的翻译ocr都提供了繁体识别API。

**Comment by miaomiaosoft** [comment]
第一个是小问题，重开下就好
繁体肯定支持了，只是没有统一语言而已，有的接口zht代表繁体有的是zh-tw之类，一般自动识别语言就行

**Comment by liuye1992** [comment]
> 
> 
> 第一个是小问题，重开下就好
> 繁体肯定支持了，只是没有统一语言而已，有的接口zht代表繁体有的是zh-tw之类，一般自动识别语言就行

多谢，另外还想问个问题，能否添加批处理OCR功能？如果图形界面写出来很耗时，提供命令行操作即可。多文档批处理感觉非常实用。

**Comment by miaomiaosoft** [comment]
批量类的功能可能暂时不会有，目前的方向主要还是轻量使用，配置文件里有个自动保存文本功能，也许能帮你减少识别后保存文本的操作
