### ISSUE TITLE
未按下截图快捷键，却自动进入截图

### ISSUE THREAD

**Issue by hkahfakh** [miaomiaosoft/PandaOCR#136]
win10
开着FastStone Capture截图软件
未进行操作只是在鼠标移动的过程中就截屏了
不知道导致原因

**Comment by miaomiaosoft** [comment]
https://github.com/miaomiaosoft/PandaOCR/issues/132  参考

**Comment by hkahfakh** [comment]
> #132 参考

好的谢谢   修改了边角触发截图就好了
