### ISSUE TITLE
开发新需求

### ISSUE THREAD

**Issue by tangtaoshadow** [miaomiaosoft/PandaOCR#138]
## 现在很多网页上的数据禁止复制，或者使用flash，图片等形式来增加文字复制的难度，所以最好是能在开发一套浏览器插件就更好了💗💗

**Comment by miaomiaosoft** [comment]
这不是我的能力范围，抱歉
解决网站防复制有一些现成的油猴脚本，你可以找找看

**Comment by tangtaoshadow** [comment]
非常感谢Thanks♪(･ω･)ﾉ，软件做的越来越好了
