### ISSUE TITLE
是否能把截图范围调成可随意扭动形状，而不是简单的矩形

### ISSUE THREAD

**Issue by Wish-John** [miaomiaosoft/PandaOCR#139]

**Comment by miaomiaosoft** [comment]
截图这块我没法做到更好，抱歉
不过PandaOCR内有一项功能可以配合其他支持非矩形截图工具做到
![BaiduShurufa_2020-5-15_18-1-58](https://user-images.githubusercontent.com/4084875/82038528-3daae880-96d6-11ea-8114-bec2172c51dd.jpg)
你可以试一试
