### ISSUE TITLE
如果是复制粘贴到翻译框里面的内容，换行为何不能强制合并？

### ISSUE THREAD

**Issue by tt3736035** [miaomiaosoft/PandaOCR#14]
如题，但截图翻译是可以合并换行的。
如图，并没有合并换行翻译
![QQ图片20190402102719](https://user-images.githubusercontent.com/38688389/55371763-fa250780-5531-11e9-9252-85edd7381b97.png)

**Comment by miaomiaosoft** [comment]
这是故意设计的，自动OCR后的自动翻译才会强行合并一次
手动点翻译是不走合并的
设计的想法是手动翻译只适合一些单词，所以不需要合并

下个版本改成鼠标左键点击 手动翻译 后合并，右键点击不合并

**Comment by tt3736035** [comment]
手动确实有必要呀，比如分别在2页上的内容，你没法截图（换页间有其它内容），只能手动复制翻译了。
而且能智能翻译剪贴板的内容就更好了

**Comment by miaomiaosoft** [comment]
新版已调整
