### ISSUE TITLE
搜狗api出现识别错误，求助

### ISSUE THREAD

**Issue by qq627296160** [miaomiaosoft/PandaOCR#141]
![image](https://user-images.githubusercontent.com/47805895/82751563-a71fab00-9dea-11ea-967a-2e5248e6c00f.png)
配置已经设置好了，为什么还出现问题？
![image](https://user-images.githubusercontent.com/47805895/82751583-cd454b00-9dea-11ea-8801-54aa47579595.png)

**Comment by miaomiaosoft** [comment]
内个啥，你是不是也用的体验金，是的话那个体验金是只能给翻译用的，OCR需要另外充值。
接口应该是没问题的，不久前才测试并修复过

**Comment by qq627296160** [comment]
奥，了解了，谢谢大神
