### ISSUE TITLE
能否增加一个选项，识别完毕之后，自动添加到剪贴板

### ISSUE THREAD

**Issue by masterjian** [miaomiaosoft/PandaOCR#142]
目前识别率还是非常高的，识别完毕之后，必须要Ctrl+A ,Ctrl+C
能否增加一个选项，识别后自动放入剪贴板（因为如果识别内容太多，放入剪贴板反而不合适）

**Comment by miaomiaosoft** [comment]
不是已经有自动复制功能吗
启用后会自动复制到剪贴板

**Comment by masterjian** [comment]
> 不是已经有自动复制功能吗
> 启用后会自动复制到剪贴板

是，没看到。
