### ISSUE TITLE
程序在游戏情况下的一些改进建议

### ISSUE THREAD

**Issue by cccccccccccccccccccccccccccccccccccccc** [miaomiaosoft/PandaOCR#144]
![prtsc](http://service.bilibili.com/picture/chatres/41076deba1104a1ba055bc38aacae3d5/msg/20200529/prtsc_1590722650048.jpg)

如图，在实际游戏使用过程中，遇到了一些问题：

1.可否添加选项让悬浮翻译结果窗口，既显示ocr原文结果，又显示翻译结果，好让自己知道是哪部分文字属于ocr识别错误 or 机翻错误，便于脑内修正。
2. 按下截图翻译的快捷键后，游戏窗口会失去焦点，需要切换回游戏窗口为active再点下一步；翻译流程可否改为全后台线程工作模式，或在更新完UI结果后重新将焦点自动切回游戏。

**Comment by miaomiaosoft** [comment]
这俩建议其实都有现成选项或配置的
1 看图：
![BaiduShurufa_2020-5-29_12-10-9](https://user-images.githubusercontent.com/4084875/83220407-769e8f00-a1a5-11ea-8a98-6f26da5b01b1.jpg)

2 修改配置文件：
恢复焦点窗口=1

**Comment by cccccccccccccccccccccccccccccccccccccc** [comment]
原来如此，在下愚钝

第一点解决了

但是焦点问题，我检查了下CONFIG.ini里的
恢复焦点窗口=1
是开启的
使用的版本为github release的最新（2.56）

第一次翻译完回切回游戏窗口焦点，继续游戏操作，之后第二次点翻译键，就不返回了
之后也是间歇性的不会返回原窗口
失去焦点的时刻为左下角emoji弹出的时刻

**Comment by miaomiaosoft** [comment]
“左下角emoji弹出”
是啥

**Comment by cccccccccccccccccccccccccccccccccccccc** [comment]
> 
> 
> “左下角emoji弹出”
> 是啥

![prt](https://user-images.githubusercontent.com/6230462/83223594-c719ea80-a1ad-11ea-8635-0443e79fb18f.jpg)

关掉动画确实就能返回了，之前我是配合其他alwaysOnTop强制置顶游戏窗口，略麻烦
这下直接就OK了

感谢回复！
