### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by weiwoduga** [miaomiaosoft/PandaOCR#147]
希望能增加个在托盘图标模式下，使用快捷键截图识别后，能直接弹出主程序的功能

**Comment by miaomiaosoft** [comment]
其实是故意这样设计的，放拖盘就是不想让它弹出主窗口，需要弹出就不应该把主窗口关闭到托盘

**Comment by weiwoduga** [comment]
> 其实是故意这样设计的，放拖盘就是不想让它弹出主窗口，需要弹出就不应该把主窗口关闭到托盘

我的使用方式是开机自启动托盘，当需要用的时候，直接按快捷键截图识别，然后结果能弹出来。因为现在的OCR，识别的结果往往不太理想，需要由人来检查判断。建议加个截图后弹出主窗口的开关功能，体验会更好。

**Comment by miaomiaosoft** [comment]
下个版本会增加一个强制显示窗口的配置项
