### ISSUE TITLE
无效操作：“将图片直接拖入至程序界面上会自动开始识别”

### ISSUE THREAD

**Issue by lihe1639** [miaomiaosoft/PandaOCR#149]
我尝试把图片拖入，但是无论怎么拖，都拖不进去，鼠标会变成一个圆圈带个斜杠那样

**Comment by miaomiaosoft** [comment]
把图片传上来我看看

**Comment by lihe1639** [comment]
> 把图片传上来我看看
> 我这测试没问题

重启电脑录屏的过程中发现是图片太大拖进去没识别成功，重新截取一张小的图片可以了~
多谢大佬~
