### ISSUE TITLE
能否增加个监视剪贴板，复制后直接翻译的功能？

### ISSUE THREAD

**Issue by tt3736035** [miaomiaosoft/PandaOCR#15]
如题，对于某些OCR识别不准确的单词，特别是符号，复制后自动翻译就很好用了

**Comment by miaomiaosoft** [comment]
加这个的话可能会有性能影响，因为要一直监视复制操作，最好还是在主窗口上操作的好
我考虑下加不加

**Comment by miaomiaosoft** [comment]
新版已加

**Comment by tt3736035** [comment]
老大神速啊
![批注 2019-04-03 090611](https://user-images.githubusercontent.com/38688389/55445842-c5778580-55ef-11e9-9ffb-88ab03347e62.jpg)
