### ISSUE TITLE
姐，你的捐助二维码看不到啊

### ISSUE THREAD

**Issue by liwenbus** [miaomiaosoft/PandaOCR#150]
电信网络看不到捐助二维码~

**Comment by miaomiaosoft** [comment]
软件界面上也有的，如果不是最新版可以上这下载：https://miao520.lanzous.com/b015f3htg
谢谢~
另外，我不是妹子，让你失望了，你可能从B站教程摸来的，但那是用户做的视频，不是我做的~

**Comment by liwenbus** [comment]
好的，哈哈哈
