### ISSUE TITLE
建议增加识别引擎切换快捷键设置

### ISSUE THREAD

**Issue by 914191848** [miaomiaosoft/PandaOCR#152]
公式识别不能识别文字，识别公式时候总要手动切换，建议增加快捷键设置

**Comment by miaomiaosoft** [comment]
下一个版本会将公式和表格识别都独立出来，这样更好切换，快捷键应该就不需要了
![BaiduShurufa_2020-6-4_11-49-11](https://user-images.githubusercontent.com/4084875/83713008-9f1d0200-a659-11ea-8799-c22fb4f53a21.jpg)
