### ISSUE TITLE
F4截图识别时，选中状态不能移到屏幕的右边

### ISSUE THREAD

**Issue by joysenlong** [miaomiaosoft/PandaOCR#153]
![image](https://user-images.githubusercontent.com/50039360/83732059-14023300-a67e-11ea-98ae-157bdd99375d.png)

**Comment by miaomiaosoft** [comment]
试了，可以呀，不过性能不是很好，拖动速度慢一点是可以移到最底的
要么勾选高级截图吧

**Comment by miaomiaosoft** [comment]
想起来了
虽然你说是1080P但可能你修改了DPI缩放
这个程序本身不支持DPI缩放设置
所以你要这样做：
04：如果你是高分屏或修改了系统DPI缩放，可能出现截图不全或弹窗位置偏移的问题，此时你需要在此程序文件的属性中取消系统DPI设置。
