### ISSUE TITLE
错误代码1

### ISSUE THREAD

**Issue by sonyxu** [miaomiaosoft/PandaOCR#157]
错误代码1
细节如图：
![图片](https://user-images.githubusercontent.com/25625821/84480361-03c60580-acc7-11ea-8b8e-3da24f99214c.png)

win10 预览版 19645.1 win8兼容模式也不能运行。

**Comment by miaomiaosoft** [comment]
你是不是和别的软件放一起？
是的话拜托放在单独的目录！

**Comment by sonyxu** [comment]
使用scoop安装，肯定应用之间隔离了啊。
文件树：
pandaocr
 ├── 2.57
 │   ├── BASS.dll
 │   ├── CONFIG.ini
 │   ├── e7b46d6945b1a205bd8a8d909718aa57
 │   ├── install.json
 │   ├── manifest.json
 │   ├── msc.dll
 │   ├── PandaOCR.exe
 │   ├── PrScrn.dll
 │   └── speex.dll
 ├── 2.58
 │   ├── BASS.dll
 │   ├── CONFIG.ini
 │   ├── e7b46d6945b1a205bd8a8d909718aa57
 │   ├── install.json
 │   ├── manifest.json
 │   ├── msc.dll
 │   ├── PandaOCR.exe
 │   ├── PrScrn.dll
 │   └── speex.dll
 └── current
     ├── BASS.dll
     ├── CONFIG.ini
     ├── e7b46d6945b1a205bd8a8d909718aa57
     ├── install.json
     ├── manifest.json
     ├── msc.dll
     ├── PandaOCR.exe
     ├── PrScrn.dll
     └── speex.dll

**Comment by miaomiaosoft** [comment]
我对scoop不了解，正常运行不会出现你所说的错误
PandaOCR的某些功能需要管理员权限，不知道是不是被scoop限制，这需要你自己解决了

**Comment by sonyxu** [comment]
等会我刚好像发现问题了，这个scoop源有问题不是你这里的锅，他把config.ini创建成文件夹了

**Comment by miaomiaosoft** [comment]
你。。。

**Comment by sonyxu** [comment]
我去给源提交issue在这关了哈，作者辛苦！打扰了。。。
