### ISSUE TITLE
PandaOCR.exe文件隔一段时间被自动删除，但是已经加入了白名单

### ISSUE THREAD

**Issue by EugeniaWEI** [miaomiaosoft/PandaOCR#159]
电脑只安装了联想电脑管家，并且把PandaOCR.exe程序所在文件夹以及exe程序都设置进入了白名单。但是隔一段时间PandaOCR.exe程序就会被自动删除，回收站里也没有。请问这个应该怎么办？把PandaOCR.exe压缩之后才不会被删除。

**Comment by miaomiaosoft** [comment]
如果是WIN10系统，那可能还有个系统自带杀毒在后面偷偷删除

**Comment by EugeniaWEI** [comment]
是win10系统，请问系统自带的杀毒有办法加白名单吗？我在设置里看显示近期没有发现病毒和威胁，没办法忽略。发自我的iPhone------------------ 原始邮件 ------------------发件人: miao_miao  <notifications@github.com>发送时间: 2020年6月23日 22:14收件人: miaomiaosoft/PandaOCR <PandaOCR@noreply.github.com>抄送: Eugenia WEI <eugeniawyj99@gmail.com>, Author <author@noreply.github.com>主题: 回复：[miaomiaosoft/PandaOCR] PandaOCR.exe文件隔一段时间被自动删除，但是已经加入了白名单 (#159)
如果是WIN10系统，那可能还有个系统自带杀毒在后面偷偷删除

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/miaomiaosoft/PandaOCR/issues/159#issuecomment-648178081",
"url": "https://github.com/miaomiaosoft/PandaOCR/issues/159#issuecomment-648178081",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by miaomiaosoft** [comment]
由于我用的是WIN7，具体加白名单怎么操作我没法知道，需要自己网上搜一下方法
个人建议禁用系统WD杀毒，换用其他更方便加白名单的杀毒

**Comment by EugeniaWEI** [comment]
好的，谢谢
