### ISSUE TITLE
弹窗背景不能设置吗？不能滚动吗？

### ISSUE THREAD

**Issue by tt3736035** [miaomiaosoft/PandaOCR#16]
弹窗透明背景，后面有文本的话影响观看，怎么设置成不透明呢？
弹窗字体已设置成很小，还是显示不全，能否滚动观看？

**Comment by miaomiaosoft** [comment]
不能不透明，那样非常丑
默认有字体边框就是考虑到和背景后内容冲突，可你偏要不设边框那只会影响你的观感
不能滚动，但你可以增加弹窗高度解决这个问题，也建议不要识别过多的文本
