### ISSUE TITLE
希望添加“热键”主动--显示/隐藏  弹窗

### ISSUE THREAD

**Issue by LadyCuaCua** [miaomiaosoft/PandaOCR#161]
2020-6-29   今天是第一次 下载并使用您的软件。全面操作了一遍，整体感觉很棒！

我的工作方式 很需要  这个”热键“来主动 显示/隐藏 这个识别翻译弹窗，我尝试了”强制显示窗口“，这让我反复点击”X“来关闭窗口很厌烦，我工作中切换的软件会很多，所以不希望pandaOCR 占用我的切换空间

如果下个版本能够拥有此功能，我非常乐意捐助并推荐个我的同事们。当然这是对您的工作表示赞赏和感谢。

![8fd6c2b693d3b22e17d82c24db88f92](https://user-images.githubusercontent.com/38346302/86029917-63156b00-ba66-11ea-9073-2b5813c1d7d6.png)

**Comment by LadyCuaCua** [comment]
最好可以 自己设置”热键“

**Comment by miaomiaosoft** [comment]
那我建议你不要自动隐藏弹窗，将隐藏时间设为0，等你实在不再需要它的时候再手动关闭
本身弹窗也是背景透明和鼠标穿透的，不隐藏也几乎不会影响到你的其他操作

**Comment by miaomiaosoft** [comment]
下个版本会加到配置文件：弹窗热键
可以自行设置热键

**Comment by LadyCuaCua** [comment]
感谢您能采纳建议并期待新版本的到来。
届时我会以捐助的形式来致敬您的工作，当然这是理所应当的。

**Comment by miaomiaosoft** [comment]
哥们，其实你不用一直强调捐助，捐助是自愿的，如果你乐意捐助，就算没有这个功能你也会捐，一直强调要先为你定制这个功能才会捐助让我觉得有点不那么好的感觉，似乎变成我是为了这份工钱在为你打工。

这个问题我三天后才再次回复你就是因为这个，本来有功能增加的要求通常我都是会尽量满足，但一直强调定制才会捐助让我感觉很不好，满足你的要求可能会被人认为我是冲着这点捐助才这么做的。

所以，不好意思，这个功能虽然已经写好但还是决定暂时屏蔽不打算在下个版本出现。

**Comment by LadyCuaCua** [comment]
您多心了，但是我为此感到很抱歉。对不起！
捐助在我个人看来是表示对您的工作付出的表示敬意，而且请您理解我并不是举着钱来驱动您的工作。
（我内心是这样想的，这软件本身就免费使用，提取额外的需求，作者付出时间和精力，这么看来捐助是很符合道理的。
而且作为使用者，也仅仅只能靠捐助这样的行为更实际的表达对作者您采纳我个人建议并付出时间工作的反馈。
我只是觉得，您能采纳建议并付出时间去修改为此我只说句感谢 来回应那太苍白了。
捐助只是表示 感谢和致敬，别无他意。
---Respect---！

**Comment by LadyCuaCua** [comment]
&nbsp; &nbsp;&nbsp;是我的表达不严谨 &nbsp;&nbsp;&nbsp; 您没有理解我的想法，但是我为此很抱歉。 （希望您能看完）


您提供的软件是免费使用，是否捐助是自愿行为（个人理解：这个自愿捐助只是在不提出要求，不给作者增加额外工作负担的情况下）
但是我觉得如果向作者提出要求并得到满足后仍然不捐助，这就不”道义“了。（事情要分两部分来看）


我确实强调得到了额外帮助是要捐助的，我也认为个人需求得到满足后无疑要捐助！因为这部分是属于”个人服务“，我也希望所有使用者&nbsp;都能看到，也希望大家都能这样做。不要只说句”谢谢大佬“之类的就了事。


简而言之，下载使用您的软件捐助是自愿的，但是满足了个人需求，就得捐助！因为作者付出了额外的工作量。（免费软件白嫖使用-可以，但是提供服务付费没毛病）


！！！（为什么是得到更新后---再捐助）！！！
我的解释：当作者看到新的个人需求及建议时，是会根据自身工作时间 /&nbsp;版本更新周期 / 修改难度 / 及工作量大小&nbsp;等等因素/来判断是否添加功能，不会因为个人需求来频繁更新版本。所以这部分捐助在得到更新后时支付时最恰当的。
简言之：是否添加新功能，要看作者心情的。作者有自己的工作和生活，功能不是拿钱就能买到的，这也是避免有的人捐助后”催更“的行为给作者带来不必要的麻烦。


每一条提问我都看过了，有的人提需求连敬语都不使用，”理直气壮“来发问来提要求。作为我个人看到这些行为虽然嗤之以鼻，但也不可能去指手画脚。我只是用我自己的方式让一部分人意识到，不要&nbsp;白嫖别人提供的额外劳动。


至此我希望能把事情说明白了。


（咱们素未谋面也没什么利益关系，也没有生活工作上的交集，但是我还是想把事情说明白解释清楚）


这封信是我对于此事做出的最后回应，不会再给您平添烦扰。


--- 致敬 ---







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miao_miao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午5:08
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"ʕ•̫͡•ʕ ʕ•̫͡•ʕ"<roughness@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 希望添加“热键”主动--显示/隐藏  弹窗 (#161)





 
哥们，其实你不用一直强调捐助，捐助是自愿的，如果你乐意捐助，就算没有这个功能你也会捐，一直强调要先为你定制这个功能才会捐助让我觉得有点不那么好的感觉，似乎变成我是为了这份工钱在为你打工。
 
这个问题我三天后才再次回复你就是因为这个，本来有功能增加的要求通常我都是会尽量满足，但一直强调定制才会捐助让我感觉很不好，满足你的要求可能会被人认为我是冲着这点捐助才这么做的。
 
所以，不好意思，这个功能虽然已经写好但还是决定暂时屏蔽不打算在下个版本出现。

**Comment by miaomiaosoft** [comment]
所以你把捐助当成是一次付费服务而不是对这个东西本身的认可？
你真有意捐助的话在我说了会在下个版本加上的时候就已经捐了而不是重复强调只有当你真正用上的时候才会捐助。
您是在买东西，而不是捐助或者说打赏！

我认可你说，但或许观念不一样，对你来说可能钱花了就一定要见到属于自己的东西，否则这钱就白花
但我要的也只是一个认可，钱多钱少并无所谓，不然我完全可以将免费软件变成付费软件

俩陌生人说多了也没意思，你要的功能会保留，不管你还乐不乐意，你的捐助我就不要了，这个话题也请不要继续，我会删除
