### ISSUE TITLE
公式识别不够准确

### ISSUE THREAD

**Issue by hbliu80** [miaomiaosoft/PandaOCR#163]
最近需要用到公式识别功能，用mathpix snipping tools能准确识别，但是用pandaOCR公式识别工具不准确，能改进一下吗？

**Comment by miaomiaosoft** [comment]
PANDA目前内置有三种公式识别接口
#公式识别：0=微软公式_演示版 | 1=百度公式_API版 | 2=网校公式_演示版
如果当前的识别效果不满意可以尝试其他的

mathpix应该是收费的吧，如果需要增加到PANDA的话需要提交ID和KEY给我测试
