### ISSUE TITLE
2.61版本腾讯接口错误

### ISSUE THREAD

**Issue by cherub0507** [miaomiaosoft/PandaOCR#164]
如题，退回2.59版本就正常

**Comment by miaomiaosoft** [comment]
你看一下更新日志
如果你是用的旧版腾讯AI接口，你应该将版本改成2

**Comment by cherub0507** [comment]
用的新版的腾讯AI接口

**Comment by cherub0507** [comment]
提示“图像识别错误，请重试或更换其他引擎”
同样的密钥2.59版就正常

**Comment by miaomiaosoft** [comment]
KEY发我测试一下

**Comment by miaomiaosoft** [comment]
2.59用的是旧版接口啊
你怎么能说你用的是新版腾讯AI？
旧版你得改成2啊

**Comment by cherub0507** [comment]
> KEY发我测试一下

改旧版也一样报错

旧版key
腾讯OCRID=2118462282
腾讯OCRKEY=HwGzmIQMfRTQeaZB

新版key
腾讯OCRID=AKIDkCeFbaRSUeqYAtQLqdcLPHWYefZywYCe
腾讯OCRKEY=WnKbcoofIfJhRu2iIYbciMnzHmBKsdO9

**Comment by cherub0507** [comment]
测试完麻烦评论删除，谢谢

**Comment by cherub0507** [comment]
改配置得重启程序

我傻了。。。

抱歉抱歉

**Comment by cherub0507** [comment]
切换旧版好用了

新版测试还是报错

**Comment by cherub0507** [comment]
难不成OCR和翻译调用的API不是一个key？

**Comment by miaomiaosoft** [comment]
你的KEY没有问题
我这测试可能和一个多线程初始化有关
你关掉程序，手动修改腾讯版本=1
然后再启动程序，当然你也可以继续用旧版接口，测试旧接口的识别质量要好于新版

**Comment by cherub0507** [comment]
好的，多谢解答

**Comment by miaomiaosoft** [comment]
是我的问题，发一个修复版给你
[PandaOCR_2.61.zip](https://github.com/miaomiaosoft/PandaOCR/files/4894992/PandaOCR_2.61.zip)

**Comment by cherub0507** [comment]
> 是我的问题，发一个修复版给你
> [PandaOCR_2.61.zip](https://github.com/miaomiaosoft/PandaOCR/files/4894992/PandaOCR_2.61.zip)

测试可用

感谢大佬！！！
