### ISSUE TITLE
新BUG

### ISSUE THREAD

**Issue by liziming0506** [miaomiaosoft/PandaOCR#166]
我的电脑（720p）投影到“仅第二屏幕”（就是复制、扩展的那种）分辨率更高（1080p），但是窗口啊，截图识别啊，只能支持左上角1280*720的部分，我没有办法识别到右下角的文字，望解决，蟹蟹

**Comment by miaomiaosoft** [comment]
03：如果你有两块屏幕，请选择“高级截图”以解决无法截取第二块屏的问题。
