### ISSUE TITLE
高级截图……

### ISSUE THREAD

**Issue by liziming0506** [miaomiaosoft/PandaOCR#168]
如果窗口是关闭状态，按F4高级截图之窗口不会自动弹出（显示）

**Comment by liziming0506** [comment]
画板截图也有这个问题

**Comment by fendouweida** [comment]
蠢不蠢啊 邮件都不会，是要把所有人都艾特一遍吗？
2020年7月10日 +0100 AM1:13 liziming0506 <notifications@github.com>，写道：

**Comment by liziming0506** [comment]
解决了，解决了，大佬不用回我了

**Comment by liziming0506** [comment]
> 蠢不蠢啊 邮件都不会，是要把所有人都艾特一遍吗？ 2020年7月10日 +0100 AM1:13 liziming0506 <notifications@github.com>，写道：
> […](#)
> 画板截图也有这个问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

啥意思

**Comment by liziming0506** [comment]
[笑哭]大佬，退出重进设置不会保存

**Comment by miaomiaosoft** [comment]
> [笑哭]大佬，退出重进设置不会保存

退出前要点保存按钮才会保存设置



> 蠢不蠢啊 邮件都不会，是要把所有人都艾特一遍吗？ 2020年7月10日 +0100 AM1:13 liziming0506 <notifications@github.com>，写道：
> […](#)
> 画板截图也有这个问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可能是GITHUB的BUG，有时没有AT别人也会收到信息，又或者你不小点了关注本项目

**Comment by liziming0506** [comment]
啊，解决了，太感谢了
