### ISSUE TITLE
Win10系统设置了自定义缩放140后，截图识别不正常！

### ISSUE THREAD

**Issue by fanmli** [miaomiaosoft/PandaOCR#17]
Win10系统设置了自定义缩放140后，截图识别不正常！

https://i.loli.net/2019/04/05/5ca6edc1d7200.png

**Comment by miaomiaosoft** [comment]
不好意思，我没有高分屏设备，这问题可能解决不了

**Comment by miaomiaosoft** [comment]
![172748lmwd5js65du1nqm5](https://user-images.githubusercontent.com/4084875/55649548-dacdf900-5815-11e9-8026-0c8424391b68.jpg)

要不你试试这样设置

**Comment by eipip1e0** [comment]
可能是显示设置里面的缩放的问题，将其设置为100%就能全截屏了，，
我常用的125%，和你一样的状况只能截取一部分。
![TIM图片20190523201431](https://user-images.githubusercontent.com/31157354/58251913-7084ff80-7d54-11e9-94fb-1058531987ae.png)

不知作者大大能否修复？ @miaomiaosoft

**Comment by miaomiaosoft** [comment]
@eipip1e0 像上面的图那样设置啊，这个已知是很难修复的

**Comment by tututuaaa** [comment]
我的笔记本也是显示125%，但是按照下边图片设置软件即可，不用更改电脑的显示比例
![image](https://user-images.githubusercontent.com/62591141/77404754-2abe1b00-6ded-11ea-8b0f-ad748102c526.png)

**Comment by tututuaaa** [comment]
![image](https://user-images.githubusercontent.com/62591141/77404927-63f68b00-6ded-11ea-8e60-b7f4f6053e4e.png)

**Comment by XZPQNBV5** [comment]
新版本的高级截图模式，完美解决了这个问题
![image](https://user-images.githubusercontent.com/50760834/83356021-ccd22480-a395-11ea-8fd1-d95126dd4e95.png)

**Comment by killfey** [comment]
21比9显示器，分辨率3440x1440，缩放100%。win10 V2004。显卡1080TI。从2.59开始截图识别那个光标就巨卡无比，延迟严重。2.61一样如此。换回2.58就正常。
同样配置下，显示器是1080P的就没这个问题...

**Comment by miaomiaosoft** [comment]
> 21比9显示器，分辨率3440x1440，缩放100%。win10 V2004。显卡1080TI。从2.59开始截图识别那个光标就巨卡无比，延迟严重。2.61一样如此。换回2.58就正常。
> 同样配置下，显示器是1080P的就没这个问题...

可能和2.59增加的划词复制功能有关，下个版本会改善

**Comment by killfey** [comment]
> > 21比9显示器，分辨率3440x1440，缩放100%。win10 V2004。显卡1080TI。从2.59开始截图识别那个光标就巨卡无比，延迟严重。2.61一样如此。换回2.58就正常。
> > 同样配置下，显示器是1080P的就没这个问题...
> 
> 可能和2.59增加的划词复制功能有关，下个版本会改善

2.62已正常，作者棒棒哒
