### ISSUE TITLE
v2.61 游戏内使用截图快捷键翻译后，会使游戏窗口变为非激活窗口

### ISSUE THREAD

**Issue by HuGnnn** [miaomiaosoft/PandaOCR#170]
我找了一圈设置没有找到相关选项，想知道能否有改进方法

这样会让体验很不好

**Comment by miaomiaosoft** [comment]
确保游戏为窗口化或窗口化全屏
然后
![BaiduShurufa_2020-7-13_14-3-56](https://user-images.githubusercontent.com/4084875/87275944-d365c700-c511-11ea-8026-63e32c415054.jpg)

**Comment by HuGnnn** [comment]
> 确保游戏为窗口化或窗口化全屏
> 然后
> ![百度Shurufa_2020-7-13_14-3-56](https://user-images.githubusercontent.com/4084875/87275944-d365c700-c511-11ea-8026-63e32c415054.jpg)

嗯嗯 我试了这两个选项，但是都没有用，看上去感觉和禁用恢复焦点效果是一样的

**Comment by miaomiaosoft** [comment]
什么游戏

**Comment by miaomiaosoft** [comment]
另外，这个功能可能需要管理员权限，要确保使用管理权限运行的OCR
如果启用了加载动画可能抢占第一次的焦点，通常第二次正常，也可以直接关掉加载动画再试试，我这测试无问题

**Comment by HuGnnn** [comment]
> 另外，这个功能可能需要管理员权限，要确保使用管理权限运行的OCR
> 如果启用了加载动画可能抢占第一次的焦点，通常第二次正常，也可以直接关掉加载动画再试试，我这测试无问题

有用有用！开启管理员权限后不会每次都抢占焦点了，但是翻译几次后又会抢占一次焦点。
另外想问下加载动画这个是在哪个地方呢

**Comment by miaomiaosoft** [comment]
教程里有写

**Comment by HuGnnn** [comment]
[http://ww1.sinaimg.cn/large/a84f7790gy1ggpclu3pnfg20tp0kc1ip.gif](url)

这是管理员权限下的表现，还是不太行，和焦点窗口是什么应用无关

**Comment by miaomiaosoft** [comment]
你不能这样用，你如果游戏里用主窗口应该关闭到托盘，不然主窗口会抢焦点

**Comment by HuGnnn** [comment]
> 你不能这样用，你如果游戏里用主窗口应该关闭到托盘，不然主窗口会抢焦点

ohhhhhhhhhh 关闭到托盘就好了！我只试过最小化

感谢问题解决了
