### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by LEMONLIANGG** [miaomiaosoft/PandaOCR#171]
如题 不时的会发生闪退问题 
杀毒软件是火绒 
同时有开utools、wgestures、按键精灵、ONEDRIVE、quicklook和IDM 不知道是哪个软件的问题会有影响 还是程序本身的问题

**Comment by miaomiaosoft** [comment]
具体一点 是程序进程突然消失还是程序文件都被删除

**Comment by LEMONLIANGG** [comment]
> 具体一点 是程序进程突然消失还是程序文件都被删除

是程序突然消失 配置文件都在

**Comment by miaomiaosoft** [comment]
配置文件当然会在了，我想知道的是 
只是程序进程消失
还是程序进程消失+程序文件也不存在
如果是前者那告诉你的使用频率
后者的话自己尝试在杀毒里加一下白名单
如果是WIN10系统你还要排除WD杀毒自动删除程序文件的问题

**Comment by LEMONLIANGG** [comment]
> 配置文件当然会在了，我想知道的是
> 只是程序进程消失
> 还是程序进程消失+程序文件也不存在
> 如果是前者那告诉你的使用频率
> 后者的话自己尝试在杀毒里加一下白名单
> 如果是WIN10系统你还要排除WD杀毒自动删除程序文件的问题

文件都在 那应该是我的频率问题 我是识别纪录片里的字幕 用了按键精灵的脚本可能过快了 这个有什么办法解决吗
