### ISSUE TITLE
希望可以增加修改ocr.space的api功能

### ISSUE THREAD

**Issue by flyingsw** [miaomiaosoft/PandaOCR#172]
ocr.space识别日文效果比国内的其他几款效果好很多，可惜配置文件尚未能修改api key

**Comment by miaomiaosoft** [comment]
演示版引擎比如搜狗 百度这些基本只支持中英的，所以可能导致你认为他们对日文识别不太行，但其实他们的API版基本都支持日文识别，你可以试试。
ocr.space由于是国外服务，在国内使用不太稳定而且延迟偏高，相信用的人不多所以没添加API版接口

**Comment by miaomiaosoft** [comment]
下个版本增加API版接口
