### ISSUE TITLE
最近百度OCR和部分OCR无法使用，总是提示识别错误

### ISSUE THREAD

**Issue by hamibobo123** [miaomiaosoft/PandaOCR#173]
从几天前开始，一直都不能使用百度OCR了，总是提示，识别错误，请更换引擎，截图识别任何图像都是这样的结果，这咋回事？之前用的是2.45，现在用最新的2.62还是这样的情况。

除了这个问题，就是用其他引擎的时候，重复识别一个图片或者截图偏小的时候，经常也会出现这个提示

**Comment by miaomiaosoft** [comment]
![BaiduShurufa_2020-7-25_12-58-23](https://user-images.githubusercontent.com/4084875/88449083-a94bc780-ce76-11ea-8627-1e41a7de7770.jpg)

如图，测试并没有问题，不管是演示版还是API版。
我不知道你的使用是否过于频繁导致被演示版暂时禁用，如果是的话你最好注册一个API版，百度有很多免费限额。
每个引擎对图片大小都有要求，像素太小可能识别失败。
不过你的问题更可能属于上面说的，过于频繁或网络不稳再加上用的演示版有时会出现失败的问题。

**Comment by hamibobo123** [comment]
我这里确认百度OCR无法使用，一直提示“图像识别错误，请更换其他引擎”，一周以前还正常的啊，具体不知道怎么回事。
什么是演示版什么是API版，没理解什么意思。
手工截图或者用这个软件界面去操作按钮的，是不是就是演示版？API版怎么用的？

**Comment by miaomiaosoft** [comment]
演示版就是你没注册自己用的接口，默认就是演示版
你也可以理解为免费试用版
建议你看看教程里的视频教程，里面有提到如何使用API版
你都不知道什么是API版自然用的就是演示版

**Comment by miaomiaosoft** [comment]
新版尝试解决这个问题，你可以更新试试
