### ISSUE TITLE
设置好截屏键之后，还没有按就自动截屏了，而且取消不了，频率还很高。

### ISSUE THREAD

**Issue by 20060504** [miaomiaosoft/PandaOCR#174]

**Comment by HuGnnn** [comment]
你可能是在高级里面开了边角触发截图？

**Comment by 20060504** [comment]
我把边角截屏禁止之后也一样，不过我已经看开了，把文本速度调到最快就可以截到文字了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miaomiaosoft/PandaOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月26日(星期天) 下午3:00
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"千二百"<yukexin0504@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 设置好截屏键之后，还没有按就自动截屏了，而且取消不了，频率还很高。 (#174)





 
你可能是在高级里面开了边角触发截图？

**Comment by miaomiaosoft** [comment]
那我就看不开了
你是不是设错快捷键了
高级设置里那个快捷键是自动固定截图用的，按一下自动每隔几秒截图识别，再按一下才会关闭
但就算设错每次截图系统都会有提示的，不知道你搞的什么鬼

**Comment by 20060504** [comment]
我把系统提示关了...然后把高级设置里的快捷键调成了和基础设置一样的...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miaomiaosoft/PandaOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月26日(星期天) 晚上8:05
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"千二百"<yukexin0504@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 设置好截屏键之后，还没有按就自动截屏了，而且取消不了，频率还很高。 (#174)





 
那我就看不开了
 你是不是设错快捷键了
 高级设置里那个快捷键是自动固定截图用的，按一下自动每隔几秒截图识别，再按一下才会关闭
 但就算设错每次截图系统都会有提示的，不知道你搞的什么鬼

**Comment by miaomiaosoft** [comment]
俺服了柚

**Comment by 20060504** [comment]
所以，我换其他版本的也会一样吗......




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miaomiaosoft/PandaOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月26日(星期天) 晚上8:10
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"千二百"<yukexin0504@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 设置好截屏键之后，还没有按就自动截屏了，而且取消不了，频率还很高。 (#174)





 
俺服了柚

**Comment by miaomiaosoft** [comment]
删除你现在的配置文件，再重启软件让它重新生成默认配置，不要去动高级设置里的热键，要改你得改主界面上的热键

**Comment by 20060504** [comment]
我换了一个版本，解决了，我现在绝对不会傻兮兮去动高级设置的热键了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miaomiaosoft/PandaOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月26日(星期天) 晚上8:16
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"千二百"<yukexin0504@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 设置好截屏键之后，还没有按就自动截屏了，而且取消不了，频率还很高。 (#174)





 
删除你现在的配置文件，再重启软件让它重新生成默认配置，不要去动高级设置里的热键，要改你得改主界面上的热键

**Comment by miaomiaosoft** [comment]
行吧
