### ISSUE TITLE
你好，请问如何保留识别的换行符？

### ISSUE THREAD

**Issue by asdfj2381k** [miaomiaosoft/PandaOCR#176]
![image](https://user-images.githubusercontent.com/56584082/89378805-315b8800-d727-11ea-886c-e7bae6f8b36f.png)

如图：

题目的答案 A  B C D  的换行被去掉了。

能否通过设置保留换行？

**Comment by miaomiaosoft** [comment]
![BaiduShurufa_2020-8-5_17-23-57](https://user-images.githubusercontent.com/4084875/89396058-abe4d180-d740-11ea-88c0-4c22a3b44efc.jpg)
或者在截图时按住ALT键

**Comment by XieJiSS** [comment]
@miaomiaosoft 可不可以增加只合并文本不自动缩进的选项，现在智能合并都自带了段首缩进，导致黏贴进 Markdown 直接变成了代码块。谢谢

**Comment by miaomiaosoft** [comment]
> @miaomiaosoft 可不可以增加只合并文本不自动缩进的选项，现在智能合并都自带了段首缩进，导致黏贴进 Markdown 直接变成了代码块。谢谢

#行首空格：0=禁用 | 1=启用 | 2=只在选择了智能合并时才启用 | 为文本每行开头添加空格缩进
行首空格=0
