### ISSUE TITLE
怎么配置不自动检测升级

### ISSUE THREAD

**Issue by hamibobo123** [miaomiaosoft/PandaOCR#178]
最近每次开机后都会提示更新升级这个软件，有没有地方设置可以不检测升级？如果需要升级，我自己会手动下载最新版

**Comment by miaomiaosoft** [comment]
就只有一个弹窗提示，而且几秒后会自动隐藏，几乎不会对你有任何影响
及时更新版本可以解决潜在的问题
很多时候一些人发现问题跑来问，但往往让他更新到新版就可以当场解决，所以不准备提供设置

**Comment by hamibobo123** [comment]
这个麻烦还是提供一下设置好吧，其他很多软件都有不提示更新或者不自动更新，不就是这个意思吗，我们是人，我们自己可以手动下载的好吧。你这个是每天提示一次，太烦了。你要为用户考虑，不要为了提示或者下载新版本而提示。给一个配置项就行了啊，可以自己修改的，默认是提示，这样不就两全其美了么

**Comment by hamibobo123** [comment]
你知道强迫症么，你知道心里长草的感受么，麻烦考虑不同人使用的感受，要有自己的解决方案

**Comment by miaomiaosoft** [comment]
你如果非要去掉呢，现在不少安全软件都有弹窗拦截，你可以试试

**Comment by miaomiaosoft** [comment]
新版已更新：
调整 恢复使用 检查版本 配置项，当设为0时，只有1/5的机率会在发现新版时弹窗提示

希望你可以接受，实在不接受我也没法
