### ISSUE TITLE
嘤嘤嘤...

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#18]

**Comment by 990721830** [comment]
怎么设置组合快捷键丫...

**Comment by miaomiaosoft** [comment]
不支持组合键，实现起来过于麻烦就懒的弄了

**Comment by 990721830** [comment]
> 不支持组合键，实现起来过于麻烦就懒的弄了

那能做到增加在WGestures这样不同触边摩擦呼出【图片识别/截图识别/剪切识别】吗...

![【Snipaste】【2019-04-12】No 224909](https://user-images.githubusercontent.com/25548230/56046154-36980500-5d75-11e9-8f88-efff9b63c7c1.jpg)

**Comment by miaomiaosoft** [comment]
[快捷识别.zip](https://github.com/miaomiaosoft/PandaOCR/files/3074141/default.zip)

放到程序目录，WGestures 里的执行操作设为快捷识别.exe的路径应该就可以了

**Comment by 990721830** [comment]
is ok....
简直棒棒嗒惹...

**Comment by miaomiaosoft** [comment]
重新下载一下最新版，刚发现并修复了搜狗翻译的API版有一些小BUG（比如行尾空格和文本中带%都会导致翻译错误）
你配置改的应该没问题
