### ISSUE TITLE
建议增加关闭检查更新功能

### ISSUE THREAD

**Issue by yzsl** [miaomiaosoft/PandaOCR#182]
#检查版本：开发者设置
检查版本=0

检查版本设置0禁用根本无效  右小角照样弹出发现新版本 如果没点到×直接点中弹窗的话直接弹出蓝奏云和github两个页面
这个非常影响体验 看了另外一个回答是为了解决潜在问题 但是强制检查更新就不太好了
用的自带的杀软没屏蔽弹窗功能  最新版启动太慢是一方面 更重要的是每次新版更新都要重新配置CONFIG.ini文件 
软件更新频率高是好事 但还是希望能有彻底关闭检查更新功能

**Comment by miaomiaosoft** [comment]
我只是举例有些杀软有这个功能，其他软件也有啊，比如阿呆喵有弹窗拦截，还有太多同类型的小工具都有拦截功能。
检查版本的代码只会在程序完全启动后才会运行，也不会因此影响启动速度。
而且弹窗会自己关闭，你们为什么就不能完全无视它让它自己消失呢？
我觉得这更多是你们自己的问题，强迫症？这个我解决不了。

**Comment by miaomiaosoft** [comment]
补充：
弹窗会在5秒后关闭，所以你等5秒就行了！
弹窗拦截工具推荐：http://www.pc6.com/softview/SoftView_122290.html
开源绿色软件，运行后也基本上不占用你任何系统资源。

**Comment by miaomiaosoft** [comment]
新版已更新：
调整 恢复使用 检查版本 配置项，当设为0时，只有1/5的机率会在发现新版时弹窗提示

这 . 总 . 行 . 吧 .

**Comment by yzsl** [comment]
> 新版已更新：
> 调整 恢复使用 检查版本 配置项，当设为0时，只有1/5的机率会在发现新版时弹窗提示
> 
> 这 . 总 . 行 . 吧 .

行吧 行吧  软件挺好的  1/5也挺好的 知足了
