### ISSUE TITLE
希望增加PDF识别后合并文本功能。

### ISSUE THREAD

**Issue by picturehome** [miaomiaosoft/PandaOCR#185]
这个应该和批量图片识别功能相类似的吧？能直接识别PDF就更方便了

**Comment by miaomiaosoft** [comment]
最新版的有这功能，不过属于捐助专享功能，有需要的话可以考虑捐助后向我要个KEY激活
另外就是虽然有，但其实是分为两个功能的，需要先将PDF转为图片，再使用图文批量识别转为TXT

**Comment by Okomoxi** [comment]
请问捐助专享版批量识别后，可以直接生成或者合成双层PDF吗？非常期待和需要这个功能。

**Comment by miaomiaosoft** [comment]
> 请问捐助专享版批量识别后，可以直接生成或者合成双层PDF吗？非常期待和需要这个功能。

这个没有
