### ISSUE TITLE
Star数量达到2000时送一波捐助版KEY

### ISSUE THREAD

**Issue by miaomiaosoft** [miaomiaosoft/PandaOCR#186]
偷偷送20个KEY，先到先得！
回复留下邮箱即可 😘 😘 😘

**Comment by iwlei** [comment]
wlei@live.in

**Comment by foreverunfree** [comment]
2190626969@qq.com
谢谢！

**Comment by faint32** [comment]
faint32@yeah.net
谢谢！！！

**Comment by fa122** [comment]
1053526769@qq.com
谢谢！！

**Comment by weiwoduga** [comment]
weiwoduga@foxmail.com    感谢！

**Comment by moonnsheep** [comment]
shiro_karas@qq.com谢谢大佬！

**Comment by LXH528** [comment]
2131003@qq.com 非常感谢！！！

**Comment by 1223729570** [comment]
1223729570@qq.com 谢谢

**Comment by hebtuzrl** [comment]
23188747@qq.com   非常感谢！！！

**Comment by ryan521** [comment]
ryanjiena@gmail.com 谢谢啦~

**Comment by killfey** [comment]
33634@qq.com
感谢UP

**Comment by TobyMiracle** [comment]
819625860@qq.com
Thanks!!

**Comment by iwlei** [comment]
wlei@live.in
多谢！

**Comment by Grant02** [comment]
grant02@163.com 谢谢~

**Comment by OKI30** [comment]
springtimedust@gmail.com
好耶，感谢!

**Comment by MC-dusk** [comment]
hallotime@163.com
支持

**Comment by maotuanzi** [comment]
谢谢~  916853034@qq.com

**Comment by maotuanzi** [comment]
谢谢〜
916853034@qq.com

**Comment by maotuanzi** [comment]
916853034@qq.com
谢谢！

**Comment by Reveanime** [comment]
chenhaoahch@qq.com
谢谢大佬！

**Comment by chhLab** [comment]
myworksync@outlook.com
谢谢miaomiaosoft

**Comment by yvhkps** [comment]
yvhkpstn@163.com
~~谢谢~~

**Comment by LYP504NLF** [comment]
1028381507@qq.com

多谢靓仔！

**Comment by miaomiaosoft** [comment]
由于活动过早结束（意料之外~），所以提前发KEY，以上参与的朋友应该全收到KEY了，另外为了保护各位的隐私，已将以上邮箱地址打码！🤟
