### ISSUE TITLE
搜狗翻译又不行了？

### ISSUE THREAD

**Issue by tt3736035** [miaomiaosoft/PandaOCR#19]
其它翻译都正常。

**Comment by miaomiaosoft** [comment]
更新了，腾讯翻译也不错，可以换着用

**Comment by 990721830** [comment]
> 更新了，腾讯翻译也不错，可以换着用
api到底怎么用丫
我申请了key还是不行惹...
![【Snipaste】【2019-04-22】No 110442](https://user-images.githubusercontent.com/25548230/56480831-7cc83380-64ee-11e9-8a8d-f2f4bf9cfe1d.jpg)
