### ISSUE TITLE
能否增加部分快捷键

### ISSUE THREAD

**Issue by ixinshang** [miaomiaosoft/PandaOCR#192]
例如直接按下快捷键，可以直接翻译或者其他的，谢谢。
https://i.loli.net/2020/08/24/PevRsBFVi3rMEjA.jpg

**Comment by miaomiaosoft** [comment]
CTRL+回车或双击就是翻译了
具体参照悬停提示

如想在其他地方快速翻译可以勾选高级设置里的双击复制

**Comment by ixinshang** [comment]
> CTRL+回车或双击就是翻译了
> 其他的参照悬停提示
> 
> 如想在其他地方快速翻译可以勾选高级设置里的双击复制

好的，谢谢。
