### ISSUE TITLE
希望得到一个pandaocr  key

### ISSUE THREAD

**Issue by shl19720610** [miaomiaosoft/PandaOCR#193]
https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxgetmsgimg?MsgID=938540169703703545&skey=@crypt_f273df07_a0489e605b7f23c8e7a79905c5ac8691
这是捐助记录，希望得到一个key,邮箱shl19720610@163.com
另外建议图片识别功能提高对手写体的识别效果

**Comment by miaomiaosoft** [comment]
你这图发跟没发一样，我看不到，不过也懒的验证，那个两块的应该就是你了，KEY已经发你邮箱
已经内置了不少手写体接口，具体查看 配置文件内注释
