### ISSUE TITLE
无法打开软件——无法找到指定DLL库文件“msc.dll”中的输出命令“QTTSFini”

### ISSUE THREAD

**Issue by qjkcusoon** [miaomiaosoft/PandaOCR#194]
运行时出错！
错误信息：无法找到指定DLL库文件“msc.dll”中的输出命令“QTTSFini”

我尝试寻找msc.dll，但都是x86，找不到x64位的。求助！ TnT

![image](https://user-images.githubusercontent.com/44939232/92493619-4d22e400-f227-11ea-830f-0605bdab64cb.png)

**Comment by miaomiaosoft** [comment]
放到别的目录吧，可能你当前目录有一个同名文件把PandaOCR生成的文件替换了
也可能被杀毒误杀，自己排查一下吧

**Comment by qjkcusoon** [comment]
WIN10 专业版 1909

**Comment by qjkcusoon** [comment]
换了个文件夹，还是同样的问题。我没有安装杀毒软件，就是win10自带的安全中心，而且两个文件夹都添加到了白名单，还是显示同样的错误，打不开...  
笔记本电脑正常使用，台式机就出错。但是我在笔记本里也没找到这个msc.dll库...

**Comment by miaomiaosoft** [comment]
用这个文件放到PandaOCR目录下
[msc.zip](https://github.com/miaomiaosoft/PandaOCR/files/5189190/msc.zip)

如果系统提示文件已存在那就覆盖

**Comment by qjkcusoon** [comment]
解决啦！十分感谢！

**Comment by miaomiaosoft** [comment]
虽然解决了但我多一句嘴，如果放到新建的文件夹里也会出错那可能说明你的电脑中毒了，有空全盘扫描一下
