### ISSUE TITLE
2.64版本的闪退问题，附Win7自带报告

### ISSUE THREAD

**Issue by star2056** [miaomiaosoft/PandaOCR#195]
有时打开软件后，在气泡弹出前后，程序会出错退出
本人是小白，系统Win7，有安装火绒，但是关闭后该问题依旧出现，要尝试很多次才能正常打开
附上出错时Win7给的报告

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	PandaOCR.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	5f3b5148
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.23455
  故障模块时间戳:	573a5509
  异常代码:	c0000005
  异常偏移:	00035d92
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by miaomiaosoft** [comment]
https://www.jianshu.com/p/fa35a7da4111

参考
我也WIN7，但没有问题

**Comment by star2056** [comment]
> https://www.jianshu.com/p/fa35a7da4111
> 
> 参考
> 我也WIN7，但没有问题
正在尝试使用管理员身份运行，但PandaOCR这个绿色软件也没有安装相关啊
这个问题出现频率很低，但一旦发生就要重开很多次碰运气

**Comment by miaomiaosoft** [comment]
此问题已在2.65版本解决，旧版可以将“固定截图热键”设为0（如果用不到这个功能且不想用新版）来避免闪退
