### ISSUE TITLE
可以发个KEY给我吗？

### ISSUE THREAD

**Issue by ALEXMSMX** [miaomiaosoft/PandaOCR#197]
已微信收款留言给你了，有空可以回个KEY给我吗？

**Comment by ALEXMSMX** [comment]
已微信收款留言给你了，有空可以回个KEY给我吗？
忘了写邮箱地址：89130159@QQ.COM

**Comment by miaomiaosoft** [comment]
谢谢
不过最好要附上捐助记录或名称，不然不知道哪个是你，导致等下还会重复在你留言的地方问你要邮箱
一般下午或晚上统一发送KEY

**Comment by ALEXMSMX** [comment]
名称是  云中国度  
留言只留了个手机号：*******8193
