### ISSUE TITLE
【还有一个建议】可以实现拖拽图片到熊猫处直接识别的功能吗?

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#2]
![](https://i.loli.net/2018/06/04/5b1548ba52ef3.gif)

**Comment by miaomiaosoft** [comment]
这个可以考虑一下

**Comment by 990721830** [comment]
哦...对了还少了一个翻译直接快捷键复制...

**Comment by miaomiaosoft** [comment]
自动复制里可以设为复制译文

**Comment by 990721830** [comment]
不是
我默认是的ctrl+z截图+复制原文的
可以的话还是希望不一样的快捷键

**Comment by miaomiaosoft** [comment]
一个快捷键就已经很麻烦了，你看我弄了一个快捷键就弄了两个设置框，不想再有新的快捷键，抱歉

弹窗那里可以手动复制译文的  也不麻烦
![qq 20180605003157](https://user-images.githubusercontent.com/4084875/40929754-41cf9a40-6858-11e8-81c0-680cb6d3a1ef.jpg)

**Comment by 990721830** [comment]
好吧...
我任务栏还是放回左边了...
到时候翻译的时候打开主界面就好了...
反正大部分只是为了识别文字...
还有你这个最下面的译是什么作用?
我点开输入文字点空格貌似没有中译英
![](https://i.loli.net/2018/06/05/5b156bde5781b.gif)

**Comment by miaomiaosoft** [comment]
![qq 20180605010405](https://user-images.githubusercontent.com/4084875/40931210-cfe165a8-685c-11e8-9361-5228b7d116b3.jpg)
我这好像没有问题
输入中文
回车
会翻译英文结果
这是游戏沟通用的
