### ISSUE TITLE
现在是不是没有自动清理内存了?

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#20]
我这边感觉用很多次好像会变卡...
需要重启才能解决...
还有能否增加一个批量本地身份证识别的功能...

**Comment by miaomiaosoft** [comment]
批量和身份证识别暂时不想加，主要还是单次识别段落文本
每次识别完理论上都会释放内存，虽然内存会有略微增加但应该还不至于到卡的地步吧，卡的时候你看看内存占用最大能到多少
