### ISSUE TITLE
可以增加小语种的OCR识别接口吗?

### ISSUE THREAD

**Issue by Andy766** [miaomiaosoft/PandaOCR#200]
比如法语 这种带特殊字母é的语言

**Comment by miaomiaosoft** [comment]
试了有道OCR使用“AUTO”语言可以识别
其它引擎没试，小语种建议申请个API版用，有些不支持自动识别语言的引擎需要自己修改识别语言为“FR”，但各引擎对语言的缩写可能不一样，“FR”是有道OCR用的，其他需要查看相应引擎的开发文档才清楚。

![BaiduShurufa_2020-10-4_19-14-23](https://user-images.githubusercontent.com/4084875/95013896-df2ada80-0675-11eb-980b-543da2623a27.jpg)

**Comment by Andy766** [comment]
> 试了有道OCR使用“AUTO”语言可以识别
> 其它引擎没试，小语种建议申请个API版用，有些不支持自动识别语言的引擎需要自己修改识别语言为“FR”，但各引擎对语言的缩写可能不一样，“FR”是有道OCR用的，其他需要查看相应引擎的开发文档才清楚。
> 
> ![BaiduShurufa_2020-10-4_19-14-23](https://user-images.githubusercontent.com/4084875/95013896-df2ada80-0675-11eb-980b-543da2623a27.jpg)

**Comment by Andy766** [comment]
对 我以前就是用有道词典的OCR识别法语 那个能用
原来修改语言选项在这里  我以前都没有发现
最后 非常感谢!
