### ISSUE TITLE
win764位使用后pandaOCR总是闪退

### ISSUE THREAD

**Issue by knzh** [miaomiaosoft/PandaOCR#21]
![image](https://user-images.githubusercontent.com/26003891/56888195-03a87d80-6aa6-11e9-9ff4-ec6488edd8aa.png)
![image](https://user-images.githubusercontent.com/26003891/56888220-128f3000-6aa6-11e9-9743-d5dd007bbe63.png)
![image](https://user-images.githubusercontent.com/26003891/56888235-19b63e00-6aa6-11e9-99db-ea0b314746f0.png)

**Comment by miaomiaosoft** [comment]
我也是一样的系统环境，但没发现有错误或闪退
你如果是从旧版升级会出错的话，要先删除旧版的CONFIG文件，或者下载到其他目录再运行看看

如果是网络原因导致出错，你可以试下把各种引擎都换成别的看看
