### ISSUE TITLE
Windows 10 打开乱码

### ISSUE THREAD

**Issue by Fred-Qhin** [miaomiaosoft/PandaOCR#214]
Device name	WilliamT470P
Processor	Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz   2.50 GHz
Installed RAM	24.0 GB (23.8 GB usable)
Device ID	A8D5FDB7-F0B0-4B30-B6F2-D259F4251024
Product ID	00331-10000-00001-AA589
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 10 Pro
Version	20H2
Installed on	‎11/‎18/‎2020
OS build	19042.630
Experience	Windows Feature Experience Pack 120.2212.31.0

![image](https://user-images.githubusercontent.com/39523950/100022125-98f42b00-2e1d-11eb-89ac-ce78705dfe16.png)

**Comment by miaomiaosoft** [comment]
你这是放弃了还是自己找到了解决方法，其实在已知问题里有写：https://support.qq.com/products/94736/faqs/83050

**Comment by Fred-Qhin** [comment]
我放弃了，设置完这个改成 非 Unicode 显示 Chinese，Beta 前面的√去掉

[cid:image001.png@01D6C400.05BB3F90]

我电脑上另一个程序不知道为什么就会乱码，之前设置过，不弄了。只有重装系统，没啥办法。
