### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by TGW555** [miaomiaosoft/PandaOCR#217]
错误代码：1
错误信息：数组成员引用下标超出定义范围
![搜狗截图20年11月29日1540_1](https://user-images.githubusercontent.com/29172047/100536123-55ecea00-3259-11eb-8ddc-cea2827dc533.jpg)

**Comment by miaomiaosoft** [comment]
删除配置文件 或 放到单独目录不要和其他程序或OCR工具放一起
重新运行

**Comment by TGW555** [comment]
> 删除配置文件 或 放到单独目录不要和其他程序或OCR工具放一起
> 重新运行

谢谢，已解决
