### ISSUE TITLE
智能翻译+对照不会使用api版

### ISSUE THREAD

**Issue by yuban01652** [miaomiaosoft/PandaOCR#218]
版本2.66
使用智能翻译+对照选项，不会使用API版，只会使用演示版。如选择腾讯翻译为版本1，输入api，能够得到正确翻译，但选择智能翻译+对照后（已在配置中设置智能引擎为腾讯翻译）只会出现版本0的演示版翻译内容，翻译失败。

**Comment by miaomiaosoft** [comment]
智能翻译那几个选项其实都只用的演示版，因为感觉没人会申请好几个API接口来用这个功能，所以当初也只是简单实现。
目前暂时没有计划增加智能翻译使用API接口的功能
抱歉

**Comment by yuban01652** [comment]
了解，谢谢
