### ISSUE TITLE
高分辨率屏幕截图问题

### ISSUE THREAD

**Issue by WuZhengqiang666** [miaomiaosoft/PandaOCR#219]
我看到了这两个链接：
https://github.com/miaomiaosoft/PandaOCR/issues/154
https://github.com/miaomiaosoft/PandaOCR/issues/17

![image](https://user-images.githubusercontent.com/49598775/101065993-cfc20200-35d0-11eb-9680-4b7b86f638d5.png)
请问 高级截图在那啊 我的软件2.6版本上没有找到。如图：
![image](https://user-images.githubusercontent.com/49598775/101065435-1f53fe00-35d0-11eb-854c-8fa950b62d05.png)

**Comment by miaomiaosoft** [comment]
高分屏截图：https://support.qq.com/products/94736/faqs/82384
双屏截图：https://support.qq.com/products/94736/faqs/83051

“高级截图”已经改到图中“画板截图”那里，其实自己一个个点进去看一下也能找到

**Comment by WuZhengqiang666** [comment]
非常感谢 问题已经解决。

非常喜欢你的软件，方便了我很多。

刚刚已经通过支付宝支持了一下，希望你能够在力所能及的情况下坚持更新和维护软件。

天凉了，寒气重，注意保暖，早点休息。
发件人: miao_miao <notifications@github.com<mailto:notifications@github.com>>
发送时间: 2020年12月4日 1:41
收件人: miaomiaosoft/PandaOCR <PandaOCR@noreply.github.com>
抄送: 方正好强 <ctffmaf@outlook.com>; Author <author@noreply.github.com>
主题: Re: [miaomiaosoft/PandaOCR] 高分辨率屏幕截图问题 (#219)


高分屏截图：https://support.qq.com/products/94736/faqs/82384
双屏截图：https://support.qq.com/products/94736/faqs/83051

“高级截图”已经改到图中“画板截图”那里，其实自己一个个点进去看一下也能找到

**Comment by miaomiaosoft** [comment]
谢谢  KEY已发到邮箱
