### ISSUE TITLE
欢迎集成我们的免费离线OCR引擎

### ISSUE THREAD

**Issue by znsoftm** [miaomiaosoft/PandaOCR#226]
https://github.com/znsoftm/BaiPiaoOCR

**Comment by miaomiaosoft** [comment]
谢谢，看上去不错，不过我不太懂C那些主流语言的代码，也没看到有提供编译好的程序。
所以我没法在代码层面集成，只能用WEBAPI接口的形式调用，这就要您这边增加接口本地调用的功能并提供编译好能在WIN平台直接运行使用的程序。

**Comment by znsoftm** [comment]
在我们的qq群中提供编译好的程序。
