### ISSUE TITLE
没有拿到key

### ISSUE THREAD

**Issue by gougou-180** [miaomiaosoft/PandaOCR#227]

**Comment by gougou-180** [comment]
开发不易，刚刚捐助了，但是没有拿到key，可以请博主私发一个key到邮箱：1243129038@qq.com吗，十分感谢。
付款：给喵了个咪
转账单号：10001071012021020800041912197344
时间：2021-02-08 16:19:41

**Comment by miaomiaosoft** [comment]
谢谢 已发
