### ISSUE TITLE
百度知云实名认证

### ISSUE THREAD

**Issue by he01865824** [miaomiaosoft/PandaOCR#239]
你好大大 请问你有微信吗 小弟有事想请求要如何加你 当然我也非常乐意捐助

**Comment by miaomiaosoft** [comment]
不太用微信，有什么问题可以在这直说或点击反馈按钮加群讨论

**Comment by he01865824** [comment]
> 不太用微信，有什么问题可以在这直说或点击反馈按钮加群讨论

我是马来西亚的用户 百度知云5月27号起没实名的账户调用量从每日50000改为每月200次 请问你能用一个实名的百度知云帐号帮我搞一个APK key吗 完事后我愿意捐助125rmb 拜托真的非常急用

**Comment by miaomiaosoft** [comment]
这不还没到五月么，你现在还是五万次每天

**Comment by he01865824** [comment]
> 这不还没到五月么，你现在还是五万次每天

由于工作关系 我是要长期使用的 每天的使用量大概是200次 拜托大大能帮帮忙吗

**Comment by miaomiaosoft** [comment]
由于接口是实名认证的，我不方便将实名的接口借给陌生人，你也应该知道中国的各种审查相当严格，如果你识别的内容包含不太和谐的东西或是政治敏感内容那我可能要冒很大的风险，希望你能理解，我无法帮助你，我能给你的建议是尝试其他家的接口，比如搜狗或腾讯。

**Comment by he01865824** [comment]
> 由于接口是实名认证的，我不方便将实名的接口借给陌生人，你也应该知道中国的各种审查相当严格，如果你识别的内容包含不太和谐的东西或是政治敏感内容那我可能要冒很大的风险，希望你能理解，我无法帮助你，我能给你的建议是尝试其他家的接口，比如搜狗或腾讯。

好的 感谢回复
