### ISSUE TITLE
能否增加更新提示或者自动更新啊?

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#24]
如题...
如果不逛git都不知道惹...

**Comment by miaomiaosoft** [comment]
本来一直就有更新提示啊
2.22版本特殊，新加功能发现一些问题所以还没推送

**Comment by 990721830** [comment]
啊...为什么我从来没有收到过推送...

**Comment by miaomiaosoft** [comment]
忘了，你的系统把任务栏设在左边导致位置出错，本来更新的提示弹窗是设置在任务栏上方的，你改在左边那应该是弹窗弹到屏幕外了
以后看能不能修复或换一种提示方式吧

**Comment by 990721830** [comment]
好吧...
我现在是居上惹...
![【Snipaste】【2019-05-23】No 000725](https://user-images.githubusercontent.com/25548230/58190320-d0e15600-7cee-11e9-8e2a-a9547f0b06e5.jpg)

**Comment by miaomiaosoft** [comment]
佩、佩服！

**Comment by 990721830** [comment]
是不是好看哭惹...

**Comment by miaomiaosoft** [comment]
海星

**Comment by 990721830** [comment]
快来用资源管理器插件QTTabBar丫...
特别好用...

**Comment by miaomiaosoft** [comment]
都用俩年了 还行

**Comment by miaomiaosoft** [comment]
2.23已更，加了新版提示音，就算没弹窗也会知道有新版
