### ISSUE TITLE
个人百度API只有扫描没有翻译

### ISSUE THREAD

**Issue by wu1160617197** [miaomiaosoft/PandaOCR#240]
根据教程申请百度个人API，输入配置文件中保存，打开翻译器翻译时只读取出了文字，但是不翻译，这是什么情况？

**Comment by miaomiaosoft** [comment]
你申请的应该只是OCR的KEY，翻译的KEY和OCR不是同一个，翻译要上这申请：https://fanyi-api.baidu.com/
