### ISSUE TITLE
新版会自己按CTRL+C

### ISSUE THREAD

**Issue by Sylyia** [miaomiaosoft/PandaOCR#241]
退出pandaocr就不会了

**Comment by Sylyia** [comment]
链接: https://pan.baidu.com/s/1YbMUYJyQAnaRPTMQ_ro9dg 提取码: a3af
这是视频复现步骤   全程没有按ctrl c

**Comment by miaomiaosoft** [comment]
看上去你是启用了划词功能，此功能是模拟按下复制快捷键实现的。
你可以删除配置文件重启后让它生成默认配置

**Comment by Sylyia** [comment]
> 看起来你是启用了划词功能，此功能是模拟点击复制快捷键实现的。
> 你可以删除配置文件重启后让它生成替换配置

解决了，谢谢你
