### ISSUE TITLE
请问为什么提示认证百度智能云之后就会闪退呢？

### ISSUE THREAD

**Issue by Sheathluo** [miaomiaosoft/PandaOCR#242]
![image](https://user-images.githubusercontent.com/48749232/117436985-2eb1eb80-af62-11eb-8f0b-04164f8c37f2.png)
就这个窗口

**Comment by miaomiaosoft** [comment]
删除旧版CONFIG.ini配置文件试试吧

**Comment by Sheathluo** [comment]
> 删除旧版CONFIG.ini配置文件试试吧

解决了，谢谢。
