### ISSUE TITLE
已捐助15元，怎么获得专项功能。希望可以通过淘宝商店或者网页充值来捐助

### ISSUE THREAD

**Issue by kunpeng9** [miaomiaosoft/PandaOCR#243]
类似天若ocr有充值界面【虽然做的很烂】
还可以试试这个，最近出的。可以转换大脑思维导图到anki
[让考试稳过的神器！免费使用！适合高考，考研，期末考，等各种考试 - MindToCard思维卡](https://mindtocard.com/)
[解决知识碎片化知识体系框架记忆之思维导图大纲笔记结合搭配Anki或Supermemo使用的终极解决方案 - 知乎](https://zhuanlan.zhihu.com/p/370670011)

**Comment by miaomiaosoft** [comment]
谢谢  KEY已发送。
这个工具它用不到充值的功能，如果是捐助可以直接扫码，如果要给接口充值那直接到接口所在官网充就好了。
天若好像是有自己提供一个中转的识别接口，为用户代收费所以才需要充值。

这个思维卡的我没看咋明白，是OCR识别吗？还是文本处理？
