### ISSUE TITLE
请问如何登陆控制台完成实名认证并成功调用该产品方向下任一接口？控制台在哪里呢？

### ISSUE THREAD

**Issue by luoyuanyuan77** [miaomiaosoft/PandaOCR#248]
引用公告部分原文”如果您希望保留某产品方向原有免费测试额度，请在5月26日（含）前登录控制台，完成实名认证并成功调用该产品方向下任一接口，我们会为您保留该产品方向下所有接口原有免费测试额度。“**请问如何登陆控制台完成实名认证并成功调用该产品方向下任一接口。控制台在哪里呢？如何登陆，这些操作我都不太懂。求解答。**###

**Comment by miaomiaosoft** [comment]
不是吧，你都看到公告原文了怎么会不知道怎么登陆，这不应该！！！
参考这个：https://support.qq.com/products/322047/faqs/93789

你登陆进去一般就有实名的提示，如果没有就自己点右上角个人中心：
https://console.bce.baidu.com/iam/#/iam/baseinfo
