### ISSUE TITLE
能否在识别结果 后面增加搜索功能呢？

### ISSUE THREAD

**Issue by mythnet** [miaomiaosoft/PandaOCR#25]
很多时候OCR后需要进行搜索，能否在识别结果 后面增加搜索功能呢？

**Comment by miaomiaosoft** [comment]
发了新版，启用弹窗后右击弹窗左箭头按钮有百度搜索跳转，你说的是这个意思么？

![0000](https://user-images.githubusercontent.com/4084875/59670887-44dc2480-91ef-11e9-957e-42253c4b2d22.jpg)

**Comment by mythnet** [comment]
好不容易找到了，隐藏有点深。
