### ISSUE TITLE
百度私人API无法使用

### ISSUE THREAD

**Issue by Wuyitan** [miaomiaosoft/PandaOCR#254]
请问是只有我还是全部都一样无法使用？

**Comment by ijrou** [comment]
QPS限制，需要付费了，目前百度OCR已经收费了

**Comment by miaomiaosoft** [comment]
测试没问题，最近百度规则有改动，请参考教程：https://support.qq.com/products/322047/faqs/93789

**Comment by miaomiaosoft** [comment]
> QPS限制，需要付费了，目前百度OCR已经收费了

不是现在已经收费，其实一直就是收费状态，只不过以前提供的免费额度多，现在少了给人的印象就好像收费了一样。
不过我们老用户按之前的公告实名后还是5万次每天免费使用，你们错过的话只能每月1000次。

**Comment by Wuyitan** [comment]
好的 感谢各位大佬的解答
