### ISSUE TITLE
希望设置了自动复制识别功能后，能有已复制成功的提示

### ISSUE THREAD

**Issue by ATTNT** [miaomiaosoft/PandaOCR#26]
希望设置了自动复制识别功能后，能有已复制成功的提示，因为我没设置弹窗

**Comment by ATTNT** [comment]
还有能添加各大ocr的个人id设置就好了，预防自带的账号不能使用，填写自己的账号就可以了

**Comment by miaomiaosoft** [comment]
怎么的提示，比如发出“叮~”的一声？

使用自己的ID功能很早就一直有了，介绍里有写：“如需使用自己申请的ID和KEY，用文本编辑器打开程序目录下的CONFIG.ini文件，在[数据配置]项，将各版本后面数值设为1（0为演示版），并修改下面相应的ID和KEY”

**Comment by ATTNT** [comment]
可以任务栏冒泡提示已复制成功，也可以桌面中间显示小块提示复制成功，1秒厚自动消失就可以

**Comment by miaomiaosoft** [comment]
看你几天不回，我都已经做成播放提示音了，就这么着吧，以前旧版也是提示音，简洁点

**Comment by ATTNT** [comment]
没事，我就提个建议而已，不过单独音效不太好，办公室用，没音箱，哈哈，等你有时间再改吧

**Comment by miaomiaosoft** [comment]
2.25 已更

复制提示 已经加了
默认是1，声音提示，你可以改成2，弹出托盘气泡，但弹出气泡只在WIN7下测试有效，其他系统不太清楚

**Comment by ATTNT** [comment]
感谢，已经更新，使用着不错！
