### ISSUE TITLE
截图后能不复制到剪切板么

### ISSUE THREAD

**Issue by fredeason** [miaomiaosoft/PandaOCR#263]
截图模式选择为高级截图后,
按快捷键框选了之后能不能直接不复制到系统剪切板,

还有我想识别之后直接预览弹窗,,所以勾选了那个  '启用预览弹窗', 但是识别了之后屏幕右边那个黄色的字能不能去掉,,直接弹出识别结果界面就行了<
期待回复,感谢

**Comment by miaomiaosoft** [comment]
不想截图后复制那你应该选择前两个截图组件

预览弹窗就是黄字，你想要显示主窗口应该到设置里启用强制显示窗口

**Comment by fredeason** [comment]
设置了一遍可以了,,
然后发现另外的问题,,当然这个可能是windows高分屏适配的问题,
软件主窗口很小,,打开了 属性兼容性中的   '替代高DP|缩放行为缩放执行',之后窗口是变大了
但是按下识别快捷键当前显示界面会放大,
问下能通过什么设置改善下这个情况么
感谢

**Comment by fredeason** [comment]
设置了一遍可以了,,
然后发现另外的问题,,当然这个可能是windows高分屏适配的问题,
软件主窗口很小,,打开了 属性兼容性中的   '替代高DP|缩放行为缩放执行',之后窗口是变大了
但是按下识别快捷键当前显示界面会放大,
问下能通过什么设置改善下这个情况么
感谢

**Comment by miaomiaosoft** [comment]
窗口可以拖动窗口右下角拉大，窗口里的元素虽无法调整但应该不影响使用
