### ISSUE TITLE
自定义百度云API接口查询失败

### ISSUE THREAD

**Issue by 1990chs** [miaomiaosoft/PandaOCR#269]
自定义了百度云ORC的API，但是使用的时候为什么显示：
返回数据失败，请尝试更换接口或查看教程申请使用私用API接口！
![image](https://user-images.githubusercontent.com/27892759/166878263-892b9ad6-f115-4594-8f32-a816982b358f.png)

**Comment by 1990chs** [comment]
![image](https://user-images.githubusercontent.com/27892759/166878483-82b59335-400c-40d8-b3a1-e3e3966b840c.png)

**Comment by miaomiaosoft** [comment]
可能没开通免费额度

**Comment by 1990chs** [comment]
> 可能没开通免费额度

我解决了，哪个接口是我以前申请的，当时还没有实名认证，神奇的是后来哪个接口变形语音识别的接口了，我重新申请了一个接口，不过话说，出来百度还有别的好用免费的接口吗？

**Comment by 1990chs** [comment]
> 不都是有免费吗，腾讯，有道...都有免费额度

大佬有申请链接吗？

**Comment by miaomiaosoft** [comment]
如果你看过教程，那么教程最后告诉你了别的接口刚如何开通
