### ISSUE TITLE
能否对固定区域进行自定义快捷键

### ISSUE THREAD

**Issue by Asdafs** [miaomiaosoft/PandaOCR#27]
例如
ctrl+1  彩虹一号
ctrl+2  彩虹二号

自动隐藏弹窗，挺实用，建议写到勾选面板。

**Comment by miaomiaosoft** [comment]
给固定截图规则增加快捷键可以有，我试试不麻烦的话就下个版本加，不过加的话也只能在配置里手动改

自动隐藏在配置里改就可以了，一般很少改这个吧，而且这是数值改动，不是1或0的开关设置，做成勾选不太好，还有个原因是界面已经定好了，一般不会再对界面有增加的改动了

**Comment by miaomiaosoft** [comment]
2.25 已更

固定截图快捷键加了，看配置就能明白，但仅限比如alt+数字键1-0 操作10个不同规则
