### ISSUE TITLE
无法找到指定DLL库文件"msc.dll"中的输出命令“QTTSFini”

### ISSUE THREAD

**Issue by ch1nj33** [miaomiaosoft/PandaOCR#270]
![image](https://user-images.githubusercontent.com/65158364/167521847-27e5c636-ec9c-4474-93f1-e4d3be1431aa.png)

**Comment by miaomiaosoft** [comment]
https://gitee.com/DDDDDGOOO/PandaOCR.Pro

**Comment by ch1nj33** [comment]
![image](https://user-images.githubusercontent.com/65158364/167522103-b8a88e04-339b-4c05-bd27-93ed174eb4b0.png)
刚下的5.39又报这个错

**Comment by miaomiaosoft** [comment]
那只能是你系统问题了

**Comment by ch1nj33** [comment]
o(╥﹏╥)o

**Comment by ch1nj33** [comment]
之前用的好好的么

**Comment by miaomiaosoft** [comment]
尝试将文件放到纯英文目录以管理员权限运行

**Comment by ch1nj33** [comment]
找到症结了，管理员权限运行 
![0356F236](https://user-images.githubusercontent.com/65158364/167525535-e80973ce-72de-4f88-b3de-d4171ddc6068.png)

**Comment by xiaozhaizz** [comment]
我是金昊月。你的邮件我已收到，我会尽快查阅
