### ISSUE TITLE
文本、公式、表格识别的冲突问题

### ISSUE THREAD

**Issue by ciddiaz** [miaomiaosoft/PandaOCR#272]
您好！
我看到配置文件中，文本、公式、表格的Key并没有作区分，如果均使用百度的服务，在配置文件中写上三行“百度OCR_KEY=”后接针对这三个用途的不同Key，程序能根据界面上选择的功能自动尝试出合适的Key吗？
还是说必须用不同家的服务，以便调用不同的Key标签呢？
谢谢！

**Comment by xiaozhaizz** [comment]
我是金昊月。你的邮件我已收到，我会尽快查阅

**Comment by miaomiaosoft** [comment]
在你开通百度接口的时候 可以同时勾选 三种服务，则使用同一个KEY
