### ISSUE TITLE
开启 "精简显示方式" 后设置界面显示不全

### ISSUE THREAD

**Issue by huanghuanhuahuh** [miaomiaosoft/PandaOCR#277]
系统win10(19044.2006), 显示器21.5英寸1080p系统缩放100%
[![2022-09-24-213424.png](https://i.postimg.cc/GhhD1smz/2022-09-24-213424.png)](https://postimg.cc/nMgr4r7Q)

**Comment by xiaozhaizz** [comment]
我是金昊月。你的邮件我已收到，我会尽快查阅

**Comment by huanghuanhuahuh** [comment]
对不起反馈错项目了, 我转去pandaocr.pro
