### ISSUE TITLE
pandaocr 乱码？

### ISSUE THREAD

**Issue by Apyz** [miaomiaosoft/PandaOCR#279]
![pandaocr 乱码](https://github.com/miaomiaosoft/PandaOCR/assets/28755252/2448aba1-500a-4779-841e-6fe8285a8b82)

如图，电脑区域开启了 unicode utf-8 ，不支持吗？如果支持，应该怎么调整？

**Comment by xiaozhaizz** [comment]
我是金昊月。你的邮件我已收到，我会尽快查阅

**Comment by miaomiaosoft** [comment]
https://support.qq.com/products/322047/faqs/95832
