### ISSUE TITLE
为什么我从昨天开始闪退了...

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#28]
如题一次也用不了了...

**Comment by miaomiaosoft** [comment]
新版闪退还是软件没动过就突然开始闪退，版本是多少

**Comment by 990721830** [comment]
昨天用的2.23吧...
今天换了2.24还是闪退...

**Comment by miaomiaosoft** [comment]
启动就闪退还是识别中闪退？
不弹提示的吗
这样的话我很难确定哪的问题
我这用着没问题

**Comment by 990721830** [comment]
识别后闪退...
任务栏小图标直接退出...
还有之前2.23截图识别的是好像会屏幕黑一下还是什么..
为什么2.24没有那个效果了...
![【2019 06 22】【20∶06∶56】](https://user-images.githubusercontent.com/25548230/59963708-76275e00-9529-11e9-9041-55c91bb4efb9.gif)

**Comment by 990721830** [comment]
![【Snipaste】【2019-06-22】No 201414](https://user-images.githubusercontent.com/25548230/59963771-5cd2e180-952a-11e9-9124-8deaa316a1cb.jpg)
这是设置...

**Comment by miaomiaosoft** [comment]
改成和你同样的配置也没问题
看你的动图 识别和翻译都没问题，弹窗只出来个按钮没见内容
你不勾弹窗看看

**Comment by 990721830** [comment]
好像确实是弹窗的问题...
关掉不闪退了...

**Comment by miaomiaosoft** [comment]
是不是你系统最近又装了啥美化的东西和它冲突

**Comment by 990721830** [comment]
找到了...是这个...
把这个关了就好了...
但是开启的时候有办法解决吗...
![【Snipaste】【2019-06-22】No 203354](https://user-images.githubusercontent.com/25548230/59963987-1d59c480-952d-11e9-8560-d79236af3300.jpg)
还有一个就是搜狗ocr...
老是最前或者最后多出来空格能解决吗....
![【Snipaste】【2019-06-22】No 203749](https://user-images.githubusercontent.com/25548230/59964055-049dde80-952e-11e9-99ba-ed0496ac728f.jpg)

**Comment by miaomiaosoft** [comment]
DEP一般是不会有人去动的吧，我都不知道这是个啥
你一定要开的话我也不知道怎么解决

行首空格=0
暂时改成0就没空格了
有的OCR末尾的空格没处理干净就会这样，以后再修正下

**Comment by 990721830** [comment]
好的知道了...

**Comment by miaomiaosoft** [comment]
2.25 已更
行首空格可以改回1了，如果需要的话！

看了下 DEP好像主要防止程序内存溢出之类或利用溢出运行恶意代码，如果启用的话可能不止这个OCR有些功能出错，其他软件也有可能会出错，而防止恶意代码运行还是靠杀毒更专业点

**Comment by 990721830** [comment]
> 2.25 已更
> 行首空格可以改回1了，如果需要的话！
> 
> 看了下 DEP好像主要防止程序内存溢出之类或利用溢出运行恶意代码，如果启用的话可能不止这个OCR有些功能出错，其他软件也有可能会出错，而防止恶意代码运行还是靠杀毒更专业点

知道啦...
我试过啦如果把OCR也同时加入DEP列表也可以用的...
