### ISSUE TITLE
演示OCR是PandaOCR自研的，还是来自不同引擎服务商的？

### ISSUE THREAD

**Issue by handsomemother** [miaomiaosoft/PandaOCR#280]
如题，如果来自不同引擎服务商的话，是不是有可能这次请求来自百度OCR，下次请求来自阿里云OCR?
![微信截图_20240506160203](https://github.com/miaomiaosoft/PandaOCR/assets/6950898/e577f001-3362-4931-b0f5-f7d699165a71)

**Comment by xiaozhaizz** [comment]
我是金昊月。你的邮件我已收到，我会尽快查阅

**Comment by miaomiaosoft** [comment]
你应该使用自己开通的私用接口。
