### ISSUE TITLE
打开软件弹出窗口

### ISSUE THREAD

**Issue by semiChange** [miaomiaosoft/PandaOCR#281]
什么情况?
D:\PandaOCR-5.47\PandaOCR.Pro.exe

![1](https://github.com/miaomiaosoft/PandaOCR/assets/16992299/8a19b250-7280-4c2d-b5f4-5e18558632be)

**Comment by semiChange** [comment]
![1](https://github.com/miaomiaosoft/PandaOCR/assets/16992299/d2ca2e15-95bd-4075-9e73-77656db95284)

**Comment by miaomiaosoft** [comment]
重新下载并不要修改任何文件
另：
此处是普通版的反馈页面，专业版请不要在此处反馈而应该点专业版上的反馈按钮。
