### ISSUE TITLE
汉化模块--重大建议！

### ISSUE THREAD

**Issue by lvjinxin999** [miaomiaosoft/PandaOCR#29]
![X](https://user-images.githubusercontent.com/46380338/59971846-c39ddc80-95b6-11e9-9bc6-6cdf95960e74.png)
如有任何不明白的留下你的联系方式，我主动加你。

**Comment by miaomiaosoft** [comment]
首先谢谢你关注到这个功能，我一度认为没人会用上这功能，甚至还想取消
然后图片做的也很棒，相当专业通俗易懂，辛苦辛苦
但是很可惜的是，基本上都很难实现

附加这个功能的缘由是多年前有一款叫金山快译2007的软件，它除了提供翻译外还有个动态汉化功能，当时这功能可是让我一惊，所以后来一直有这个功能的需求，只可惜有此功能的软件目前只此一家，而且它的新版上似乎都已经去除了，最近因为看到有大佬写了个这方面的例子，所以就果断加上了
但是为什么没有更多的软件提供这样的功能呢，我觉得和我想的应该差不多

句柄问题，可能十年前还好，很多软件都是用系统组件做界面，句柄好取动态汉化起来比较容易，而现在不少的软件开始用各种自绘方式生成界面，句柄已经不那好取了
就算能取到句柄还不一定能取到所处句柄上的文字，就算取到了文字也不一定能把翻译正常替换上去
你说的汉化记忆，要实现的话可能要做成劫持补丁，这样的方式其实非常容易误报为病毒，报毒了用的人就不放心了
除了上面的问题，实用性也不太强，这个功能就我自己都还没用过几次，而这几次还是测试时才用的，并且测试的时候找了半天才找到几个不是自绘的，再者软件上的英文基本都不复杂，要么直接就能看懂，要么翻译一次就能记住不需要时时汉化，除非是大型的专业软件

上面说的是文字汉化，图片替换达到汉化的方式我会研究一下，但感觉希望不大

基于你的需求和演示上的软件，我建议还是找专人汉化，如果有加壳保护的话可能需要先破解，直接静态汉化会比动态汉化要更实用美观
