### ISSUE TITLE
【bug】截图后软件自动添加换行导致翻译不准确...

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#3]
![](https://i.loli.net/2018/06/05/5b159d58f3454.jpg)
我用的同样的腾讯OCR
经测试你这边软件识别框每行文字数量限制问题
导致本来原文没有换行的,软件自己给他加上换行
导致翻译不准确....(na文字识别也是和你一样)
天若ocr文字识别出来没有换行问题...
下面是GIF
https://blog.github.com/
![2018 06 05 03 50 28](https://user-images.githubusercontent.com/25548230/40939641-e7c0f77c-6877-11e8-8501-c04fa77c43f3.gif)

**Comment by miaomiaosoft** [comment]
已更新
这样是正常的，当然想强行纠正也可以，但纠正后也可能会导致比如不同行的两个标题在翻译时产生关联，不过已经做成设置了，可以按需开启

**Comment by 990721830** [comment]
但是这样开启纠错后...
原本有换行符的原文换行也被吞了貌似...

**Comment by miaomiaosoft** [comment]
所以说按需开启

**Comment by 990721830** [comment]
不知道能不能换一种机制
高级设置-里面的显示滚动条-不是目前只加在图片下面吗?
在不纠错的情况下
就是给识别文字和和翻译滚动条都加在下面
不知道这样能不能有效?

**Comment by miaomiaosoft** [comment]
已更，不过不太明白你的意思
现在识别文本不会自动合并了
