### ISSUE TITLE
使用自己申请的OCR接口

### ISSUE THREAD

**Issue by liwenbus** [miaomiaosoft/PandaOCR#30]
善良的小哥哥或小姐姐，你好，软件的config文件里面有百度OCRID=、百度OCRSECRET=、腾讯OCRID=、腾讯OCRKEY=，但没有搜狗OCR的示例。所以搜狗OCR的话是不是自己添加为搜狗OCRID=  搜狗OCRKEY=就行了呀，谢谢你哦。

**Comment by miaomiaosoft** [comment]
不行，因为搜狗的接口文档写的很烂（也可能是我能力不行参详不透），导致鉴权验证一直写不对，所以没有提供
其它俩个其实也够用了，搜狗的接口好像也要比其他的价格要更贵
