### ISSUE TITLE
你好，能否新增一个伪原创的功能

### ISSUE THREAD

**Issue by vsalw** [miaomiaosoft/PandaOCR#31]
简单说就是输入一段文字，系统进行伪原创，输出含义相同但是表述不同的文字，此功能在自媒体，论文查重具有很大的商业运营潜质，需求量很大

**Comment by miaomiaosoft** [comment]
可是这和我OCR没啥关系啊
伪原创有很多现成的工具，在一个OCR工具上实现是不是没啥必要
