### ISSUE TITLE
那个弹窗能否增加回以前老版本的复制选项啊...

### ISSUE THREAD

**Issue by Noah1995** [miaomiaosoft/PandaOCR#32]
1丶【那个弹窗能否增加回以前老版本的复制按钮啊...】

2丶【还有那个锁定按钮配合自动关闭开启的时候...】

3丶【还有就是能否显示的时候能否增加一个类似这样的中英对照模式...】
     【一句话一句话翻译...】
      复制识别
      Copy identification
      复制译文
      Copy a translation

**Comment by miaomiaosoft** [comment]
不是有自动复制功能么，完全可以替代手动复制，而且弹窗的右键菜单本身也有复制
![QQ截图20190710154658](https://user-images.githubusercontent.com/4084875/60950798-6d58c980-a32a-11e9-9c6b-d06a32cc538f.jpg)

锁定按钮？不知道是指啥

弹窗显示识别和译文并逐行对照？

**Comment by Noah1995** [comment]
我现在才发现有右键菜单...
你下次更新增加一下复制截图丫...
对...就是逐行对照...

**Comment by Noah1995** [comment]
复制你还是都加在任务栏图标右键菜单里面吧...
弹窗按钮太小了老是会变成右键桌面菜单..

**Comment by miaomiaosoft** [comment]
逐行对照，复制截图下版加

现在的弹窗按钮已经很大了，弹窗菜单不应该放在托盘菜单里，变成右键菜单可能是你点的时候正好弹窗自动关闭了，你可以延长自动关闭时间，默认好像是15秒，或者设为0
自动隐藏弹窗=15

**Comment by miaomiaosoft** [comment]
已更
