### ISSUE TITLE
有一个问题

### ISSUE THREAD

**Issue by wzjdwws** [miaomiaosoft/PandaOCR#33]
用图片识别是时候，一直提醒我图片识别错误，能问下怎么解决么？

**Comment by miaomiaosoft** [comment]
举个粟子

**Comment by wzjdwws** [comment]
![image](https://user-images.githubusercontent.com/52741130/60958802-93d23100-a339-11e9-8848-fe7fb566d57e.png)
这是我复制翻译出来的
![image](https://user-images.githubusercontent.com/52741130/60958853-a77d9780-a339-11e9-8998-d00c5a457da0.png)
截图翻译就翻译不出来l了

**Comment by miaomiaosoft** [comment]
我看你选的是腾讯OCR，腾讯的默认用的演示版，好像有一些限制或不稳定，但我这边测试是可用的
而且，这几个OCR里只有 有道OCR 能识别日文，其他都不行

你要识别日文只能用有道，其他OCR如果某个不能用可以换其他的或自己申请API

**Comment by wzjdwws** [comment]
好吧，我今天解决这个问题了。原因是固定截图模式如果你固定的范围比较小，程序就读取不到，如果截图的范围大一些，它就成功了。谢谢！
