### ISSUE TITLE
启动初始化特别慢

### ISSUE THREAD

**Issue by iaston** [miaomiaosoft/PandaOCR#34]
有时候启动panda ocr时都要大概很长时间才会提示初始化完成，在此期间软件基本失去响应。当然有的时候又比较快，大概3-5秒可以完成。不知道这期间在做什么，从时间波动性上感觉是发送了网络请求（没抓包，猜的），是否可以把不太重要的网络请求变成异步的（比如统计当前使用人数），这样可以快速启动。

**Comment by miaomiaosoft** [comment]
启动时在网络请求方面干了三件事
1 检查是否有新版，这个连接的GITHUB
2 初始化各引擎，比如取cookies用来通过验证，这个连接各引擎所在网页
3 取一次统计数据，这个连接51.la统计网站

由于GITHUB在国内连接时而缓慢时而正常，我估计是检查更新导致
其他两个都是连接的国内网站，不会花太长时间
下个版本我改善下

**Comment by iaston** [comment]
从善如流，👍
