### ISSUE TITLE
“是否修正文本”中的选项分别是什么意思？

### ISSUE THREAD

**Issue by iaston** [miaomiaosoft/PandaOCR#35]
![image](https://user-images.githubusercontent.com/11807657/61109638-f94c2c00-a4b7-11e9-8755-6f1c58f43567.png)
请问一下，这里面的：
是否修正文本
强行合并
智能合并
游戏通用
彩虹六号
未世鼠疫

第一个比较容易明白，第二个到第五个不太清楚是什么规则，网上查了很多都没有介绍，请问是否能简单介绍一下，谢谢。

**Comment by miaomiaosoft** [comment]
是否修正文本 = 不修正，OCR返回什么格式就是什么，一般是多行
强行合并 = 将返回的多行文本强行合成一行
智能合并 = 先将文本合成一行，再根据文中的符号比如句号、感叹号进行分行处理
游戏通用 = 基于智能合并但更针对处理游戏中的队友聊天信息
后两者和游戏通用差不多，但不同游戏略有差异

OCR的原理是直接识别出图像里每行的文字并直接返回，OCR并不知道哪里该是换行

比如这段话：
原文是一行的：President Trump confirmed Thursday that he is no longer pushing to include a citizenship question on the 2020 census

但是在图片里或网页因为显示宽度问题会自动折行大概变成这样：
President Trump confirmed Thursday that he is no longer 
pushing to include a citizenship question on the 2020 census

如果不修正的话，不仅排版乱，还可能会影响翻译和朗读的质量，合并成完整的一行或多行翻译朗读就自然的多

**Comment by iaston** [comment]
嗯嗯，明白了，谢谢
