### ISSUE TITLE
【优化只有当启用智能合并时行首空格 才生效】 能还原之前的吗

### ISSUE THREAD

**Issue by Noah1995** [miaomiaosoft/PandaOCR#36]
能调回之前的吗？
或者增加不智能合并的时候1、0开关

![【Snipaste】【2019-07-14】No 163042](https://user-images.githubusercontent.com/25548230/61181159-cf7c3c00-a654-11e9-8cff-501b59da8f25.jpg)

**Comment by Noah1995** [comment]
自动复制和监听不能同时打开吗?
一直叮叮叮的响...或者卡住....

**Comment by miaomiaosoft** [comment]
已更，你设为1就行了
