### ISSUE TITLE
双显示器的截图问题。

### ISSUE THREAD

**Issue by grs432** [miaomiaosoft/PandaOCR#37]
双显示器的截图问题。
只能截图一个显示器的

**Comment by miaomiaosoft** [comment]
试试高级截图方式，那个调用微信/QQ截图，如果同样不支持我也没办法

**Comment by miaomiaosoft** [comment]
或者参考这个：https://www.52pojie.cn/forum.php?mod=redirect&goto=findpost&ptid=919023&pid=26673329

利用其他支持双屏的截图工具进行截图
