### ISSUE TITLE
【腾讯翻译】有空行bug....

### ISSUE THREAD

**Issue by Noah1995** [miaomiaosoft/PandaOCR#38]
1丶
【腾讯翻译】有空行bug....
  会导致无法逐行模式匹配到空白行显示出错...
  谷歌引擎貌似也有第2行之后有多出2个空格缩进bug...
   
![【Snipaste】【2019-07-20】No 022812](https://user-images.githubusercontent.com/25548230/61557283-68b4b380-aa96-11e9-8291-22287ca51848.jpg)
![【Snipaste】【2019-07-20】No 025303](https://user-images.githubusercontent.com/25548230/61558442-9cdda380-aa99-11e9-8fbc-e0bb883f1e85.jpg)

2丶
【逐行模式】能否弹窗显示的时候增加翻译后增加一个空行...
  逐行是因为方便看顺便学习一下惹...
  如果文字很长的话都窝在很头疼....

![【Snipaste】【2019-07-20】No 024422](https://user-images.githubusercontent.com/25548230/61558015-6d7a6700-aa98-11e9-80a7-fca3e8a9c3b9.jpg)

**Comment by miaomiaosoft** [comment]
新版已解决
