### ISSUE TITLE
除了搜狗ocr其他的ocr都识别不了日文

### ISSUE THREAD

**Issue by wekiname** [miaomiaosoft/PandaOCR#39]
rt，软件设置里设置成“jp”也没卵用，日文全给我当成中文识别了。我去看了下这几个ocr都支持日文啊。搜狗ocr识别不了几次就超上限了。

编辑，是除了有道ocr别的都识别不了日文，口胡了

**Comment by miaomiaosoft** [comment]
都用的演示版？
已知演示版里就有道支持日文，其他基本都是中英
如果是自己申请注册的KEY用的API版的话可能会支持更多语言

**Comment by cybernamed** [comment]
我申请了搜狗OCR的API，实测日语识别也是会被当中文识别。我自己用python跑了搜狗OCR的demo说明API申请到了没有问题。有个问题就是搜狗OCR识别时需要指定一下识别的语种，否则默认是中文。默认情况下当识别日语时就会按中文来识别，希望作者看到能优化一下这部分。

**Comment by miaomiaosoft** [comment]
搜狗API版确实可以指定语言，默认用的是zh-CHS
下个版本加个配置项看看

**Comment by cybernamed** [comment]
我看了那几个OCR的文档，好像只有有道是自动识别语言的，其他的都要指定语言，所以强烈建议加这个配置项。（有道果然是做翻译的，这个倒是得夸奖一下。）

**Comment by miaomiaosoft** [comment]
新版已更，除了腾讯API版外，其他API版OCR都支持指定识别语言
