### ISSUE TITLE
不知名的bug

### ISSUE THREAD

**Issue by yfsmallmoon** [miaomiaosoft/PandaOCR#41]
电脑不用一段时间后，打开出现一堆匹配失败的弹窗

**Comment by miaomiaosoft** [comment]
无图无真相，下次记得截图

**Comment by liuyingxuanlv** [comment]
![image](https://user-images.githubusercontent.com/30750380/61773726-efb3b400-ae27-11e9-9205-022bb9650606.png)
![image](https://user-images.githubusercontent.com/30750380/61773742-f8a48580-ae27-11e9-883f-23b13b1cb992.png)

**Comment by miaomiaosoft** [comment]
看起来还真是我弹的，不过目前都没有其他人报告同样的问题，我自己这也从没遇到，估计不好解决
怀疑是网络问题导致，有用到正则的地方大概只有搜狗翻译
你试试看用浏览器能不能正常打开并使用 https://fanyi.sogou.com

**Comment by liuyingxuanlv** [comment]
![image](https://user-images.githubusercontent.com/30750380/61774809-3e624d80-ae2a-11e9-9802-5674977d23cd.png)
可以用

**Comment by miaomiaosoft** [comment]
那现在软件是启动就报错不能用还是放后台一段时间比如半小时才会报错

**Comment by liuyingxuanlv** [comment]
放后台一段时间，放多久会报错不清楚。

**Comment by miaomiaosoft** [comment]
那估计还是网络不稳的原因，本身程序没加判断，可能因网络不稳返回空文本导致正则出错

把配置文件这里改成0用用看
定时重载数据=0

**Comment by liuyingxuanlv** [comment]
好的，我试试

**Comment by liuyingxuanlv** [comment]
![image](https://user-images.githubusercontent.com/30750380/61920112-04f52380-af8b-11e9-94fe-ea099d2ade7e.png)
我电脑连得手机热点会时不时断网，定时重载数据调成0了断网期间还是会出现这个问题

**Comment by miaomiaosoft** [comment]
改成0了理论上只有刚启动那会才有可能报错
你这还是运行中报错？那就很费解了
