### ISSUE TITLE
软件启动后 "叮 已初始化完毕" 这个声音能取消吗?

### ISSUE THREAD

**Issue by heeroyuyj** [miaomiaosoft/PandaOCR#43]
如题

**Comment by miaomiaosoft** [comment]
这个应该没啥影响吧，不提示的话我怕有人刚运行就使用可能导致出错，所以提示还是要有的
如果你嫌音量太大我可以帮你调小到50，之前是80

**Comment by heeroyuyj** [comment]
呃 因为没看到任何开关/选项控制这个声音 是否能加个?

**Comment by miaomiaosoft** [comment]
因为不是功能配置只是个只响一次的提示，所以没有必要加个开关，我倒是好奇你非要关掉的理由是啥

**Comment by heeroyuyj** [comment]
因为之前用一直没这个提示音的 现在每次启动都叮一下 且不可关闭 所以才希望能恢复成原来那样

只是提问 也没别的意思 如果不方便就算啦

**Comment by 007zero** [comment]
抱歉，你没有回错人吧？我没有给你发过邮件。


 
---原始邮件---
发件人: "heeroyuyj"<notifications@github.com>
发送时间: 2019年7月29日 09:21:46
收件人: "miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [miaomiaosoft/PandaOCR] 软件启动后 "叮 已初始化完毕" 这个声音能取消吗? (#43)



因为之前用一直没这个提示音的 现在每次启动都叮一下 且不可关闭 所以才希望能恢复成原来那样
 
只是提问 也没别的意思 如果不方便就算啦
