### ISSUE TITLE
匹配失败, 请检查正则语句是否有误, 数量: 0

### ISSUE THREAD

**Issue by heeroyuyj** [miaomiaosoft/PandaOCR#44]
![image](https://user-images.githubusercontent.com/2717690/62269757-a20dfb80-b466-11e9-8ad1-ab4c5d6ea206.png)

这个提示最近弹出比较多, 不知为何?

配置文件如下所示

[程序配置]
开机运行=0
初次启动=1
收展状态=1
识别引擎=1
#指定图像识别语言：auto | zh | en | ja | 此配置限API版，auto只有道支持，其他不支持的将自动转为zh
识别语言=auto
翻译引擎=1
自动翻译=0
翻译来源语言=auto
翻译目标语言=zh
自动朗读=2
朗读引擎=2
#语音朗读播放方式 | 0=先下载再播放，慢 | 1=边下载边播放，快，但不是全都支持 | 默认0
朗读方式=0
朗读音量=70
排除朗读=1
自动复制=0
#复制成功提示 | 0=不启用 | 1=提示音 | 2=托盘气泡
复制提示=1
自动弹窗=0
弹窗内容=2
弹窗宽度=300
弹窗高度=200
#五种不同的半透明弹窗背景：1-5更换 | 0=不启用
弹窗背景=0
弹窗字体=微软雅黑
#十进制颜色数值如：1973790，0为透明
弹窗字体边框=1973790
#渲染方式，系统=0/符号位图+HT=1/符号位图=2/抗锯齿+HT=3/抗锯齿=4/CT+HT=5
弹窗字体渲染=4
#弹窗字体风格：0=普通 | 1=倾斜 | 2=加粗 | 3=加粗倾斜 | 4=删除线 | 5=下划线
弹窗字体风格=2
#十进制颜色数值如：1973790，0为默认黄色
弹窗字体颜色=0
弹窗字体大小=13
主窗字体大小=10
#秒数，0为不启用
自动隐藏弹窗=0
打开网址=0
文本修正=3
符号替换=0
#为文本每行开头添加空格 | 0=不启用 | 1=启用 | 2=只在选择了智能合并时才启用
行首空格=1
#截图像素：0=全屏 | 1=全屏高度-1
截图像素=0
高级截图=0
固定截图=0
#启用后双击选择固定截图规则将同时启用相应的文本修正
固定截图联动=0
截图热键=
#十进制颜色数值如：1973790，0为默认红色
截图选框颜色=327935
截图时透明度=255
#十进制颜色数值如：15000804，主窗口背景色，0为银白色
窗口背景颜色=0
#主窗口透明度，值越小越透明，1-255
窗口透明=245
监听复制=0
#共五种不同的识别加载动画效果 | 1-5开启并选择效果 | 0=禁用
加载动画=1
#定时重载统计数据和某些演示版引擎的COOKIES效验的分钟数 | 0=禁用 | 默认30分钟
定时重载数据=30
恢复焦点窗口=0
#鼠标停留在屏幕角落时触发截图 | 1-4分别为左上角、右上角、左下角、右下角 0=不启用
边角触发截图=0
#0=不启用保存 | 设置图片保存目录即启用，例：Z:\PIC
自动保存截图=0
#0=不启用保存 | 设置识别翻译文本保存目录即启用，例：Z:\PIC
自动保存文本=0
截图放大镜=0
[数据配置]
#0=免费演示版，1=API版（有免费试用也有付费的）
搜狗OCR版本=0
百度OCR版本=0
腾讯OCR版本=0
有道OCR版本=0
#
搜狗翻译版本=0
腾讯翻译版本=0
百度翻译版本=0
有道翻译版本=0
#请使用自己注册的ID和KEY，以下示例并不可用！
搜狗OCRPID=d16f9bfc81305e1a2dc8b2b3XXXX
搜狗OCRKEY=93611ea9bed496c7bba3dfeaXXXX
百度OCRID=pHYUg3eDVomNgidA6M5T9XXX
百度OCRSECRET=a161vVuzmw3s0iRvrY7CwT28ACZImXXX
腾讯OCRID=1106934XXX
腾讯OCRKEY=7Fs3hF4bsRWU3XXX
有道OCRKEY=1b71a281739afXXX
有道OCRSECRET=8pBxuHZ92zMXmvSpwx75ETyNoVQElXXX
#
搜狗翻译PID=859d1b4b9875b6805eb51ebb0cda0XXX
搜狗翻译KEY=6d27652a3fe12e3b889481ba6035eXXX
腾讯翻译ID=AKIDxy4DSckKo8HF4i6I6lJk6MRKKD0bCXXX
腾讯翻译KEY=2tY2NadpskRxOeiaHn7FD9tW2NZcXXXX
百度翻译ID=20190310000XXXX
百度翻译KEY=7HOeYQHoZesNaXXXXX
有道翻译KEY=1b71a281739afXXX
有道翻译SECRET=8pBxuHZ92zMXmvSpwx75ETyNoVQElXXX
[固定截图]
#固定截图快捷键：0=不启用 | alt/ctrl/shift+!/1 | !为主键区数字键 | 1为小键盘区数字键 | 示例：alt+! 或 alt+1
固定截图热键=0
固定截图区域=彩虹二号|500|500|300|200
01=彩虹一号|500|500|300|200
02=彩虹二号|500|500|300|200
03=彩虹三号|500|500|300|200
04=彩虹四号|500|500|300|200
05=彩虹五号|500|500|300|200
06=彩虹六号|500|500|300|200
07=彩虹七号|500|500|300|200
08=彩虹八号|500|500|300|200
09=彩虹九号|500|500|300|200
10=彩虹十号|500|500|300|200

**Comment by miaomiaosoft** [comment]
参考 https://github.com/miaomiaosoft/PandaOCR/issues/41
