### ISSUE TITLE
能否增加表格识别的部分呢？

### ISSUE THREAD

**Issue by wangmanv2** [miaomiaosoft/PandaOCR#45]
能否增加表格识别的部分,最近在使用过程中需要识别表格，而传统的文字识别很难满足表格识别的需要。想知道作者有没有开发相应的表格识别的功能呢？

**Comment by miaomiaosoft** [comment]
我这主要识别图片段落文字，表格和普通的OCR在功能实现和输出文本的格式上应该都不一样，我输出的是TXT文本，你要的是导出Excel格式文件，两者没法很好的共存，我也没这需求，抱歉
天若OCR好像有这功能，你可以去看看
