### ISSUE TITLE
使用“固定截图热键”识别小图片（或者图片的区域较小）有问题

### ISSUE THREAD

**Issue by cybernamed** [miaomiaosoft/PandaOCR#46]
如题，勾选“启动固定截图"时使用面板上的快捷键截取到的图能识别，
去掉勾选用配置文件中设置好的”固定截图热键“截取到的同一张图识别不了。

实验了一下，当图片足够大的时候固定截图热键也会生效。
其他方式识别的图片区域大小则没有限制，只有固定截图热键识别的图片要有足够的大小。
能否解决一下这个问题

ps：换其他OCR也是如此

**Comment by miaomiaosoft** [comment]
大概知道问题在哪了，下个版本修复看看
