### ISSUE TITLE
2.3.4不报毒，之后开始报了

### ISSUE THREAD

**Issue by mythnet** [miaomiaosoft/PandaOCR#47]
如题，虽然估计是误报，但能处理一下更好。

**Comment by miaomiaosoft** [comment]
我本地环境有NOD32保障，所以基本不会是真的有毒
虽然我不太可能会处理误报但还是问问是哪个杀毒报的，报的什么类型病毒

**Comment by mythnet** [comment]
会误报的自然是360。知道360是个垃圾软件，但不得不装，360天擎报：感染型病毒（Win32/ Trojan061）

**Comment by miaomiaosoft** [comment]
谢谢告知，不过由于360误报过于严重和流氓，他的这个感染报法我都不知道如何查起也就没法从程序本身解决了，如果真有感染型病毒如此严重的行为，我的NOD32不至于一声不吭，所以这种老流氓瞎报我没法处理，也处理不完，今天他报这个，明天你解决了他还可能报别的（比如为了防止某些游戏屏蔽热键我用了比较激进的HOOK方式也容易误报），而且每次编译都要这么来一次，浪费心力和时间

我本以为卡巴这类老牌杀毒也会误报，没想到在线查毒并没有
![QQ截图20190816185800](https://user-images.githubusercontent.com/4084875/63163433-ee0c9300-c057-11e9-9e2a-a330060bf208.jpg)

**Comment by a90120411** [comment]
PandaOCR v2.40 版本，Windows Defender 也会报毒
![image](https://user-images.githubusercontent.com/4596858/64323091-5c5cc980-cff6-11e9-81ec-21bb993c385c.png)

此外我测试了几个在线查毒的网站，均有不同程度的提示，报告如下：

1、https://virusscan.jotti.org/zh-CN/filescanjob/i1bshy4twm

2、https://www.virustotal.com/gui/file/57e591a798e57934e0a67f4915c3db902f299204bfb66ffa7589626d1b127788/detection

3、http://r.virscan.org/language/zh-cn/report/3c7081c8d992654c4fc1dae6f40a4ef9

**Comment by miaomiaosoft** [comment]
> PandaOCR v2.40 版本，Windows Defender 也会报毒
> ![image](https://user-images.githubusercontent.com/4596858/64323091-5c5cc980-cff6-11e9-81ec-21bb993c385c.png)
> 
> 此外我测试了几个在线查毒的网站，均有不同程度的提示，报告如下：
> 
> 1、https://virusscan.jotti.org/zh-CN/filescanjob/i1bshy4twm
> 
> 2、https://www.virustotal.com/gui/file/57e591a798e57934e0a67f4915c3db902f299204bfb66ffa7589626d1b127788/detection
> 
> 3、http://r.virscan.org/language/zh-cn/report/3c7081c8d992654c4fc1dae6f40a4ef9

Windows Defender本来误报就非常严重，甚至比360还严重
上面也说了，误报问题我是不会解决的，那太无聊了！
总之，不管是杀毒也好，在线查毒也好，都只是参考，是不是真的有毒我建议你学习下反编译之类的技能 （程序本身没有加密保护）！

开源你也解决不了，因为E语言本身就被一些杀毒歧视，加上一些功能比如上面提到的热键需要HOOK键盘之类容易被误报的代码
