### ISSUE TITLE
腾讯翻译和腾讯ocr是不是都失效了......

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#5]
都已经很久了...

**Comment by miaomiaosoft** [comment]
已经修复：https://github.com/miaomiaosoft/PandaOCR/releases/tag/1.9
我这测试腾讯翻译是好的，不过腾讯翻译有些不稳，建议用搜狗替代。

另外，腾讯OCR默认用的DEMO版，API换过几次，想更稳定建议用API版，程序其实早已内置了API版，
申请地址：https://ai.qq.com/product/ocr.shtml#identify，
之后修改config.ini配置文件中的相应部分：
TX_OCR=1 //1为DEMO版，2为API版
TX_OCR_id=110XXXXXXX //申请的ID
TX_OCR_key=7Fs3hF4XXXXXXXX //申请的KEY

**Comment by 990721830** [comment]
ocr可以....翻译真的无效.....
对了你现在的api用的什么翻译君还是腾讯AI Lab....
Lab翻译更加好一点.....
![snipaste20180908_074700](https://user-images.githubusercontent.com/25548230/45247671-e585e580-b33b-11e8-87a8-adbedb44f3f1.jpg)

**Comment by miaomiaosoft** [comment]
我这还是正常，不知道你那什么问题，检查下“翻译语言设定”，原先的ZH-CN在后面的版本已经换成zh了，也许和这个有关！

目前用的是翻译君，AI LAB看看接口好弄不，其实搜狗翻译质量是最好的，可以用这个替代

**Comment by 990721830** [comment]
我这边搜狗和腾讯都没用....
AI LAB有api啊

**Comment by miaomiaosoft** [comment]
删除config.ini试试
还不行那我也不知道了
知道有API，先看看好用不再说

**Comment by miaomiaosoft** [comment]
不知道你还在不在用，腾讯云有三种API
目前内置的DEMO版是翻译君的，API版是腾讯云的，另外还有腾讯AI实验室的翻译君和AI LAB
AI LAB的接口文档看了下，本来可以加上，但鉴权系统好像有点问题，暂时弄不了
