### ISSUE TITLE
大佬能支持朗读的语言选择嘛？

### ISSUE THREAD

**Issue by NOAME18** [miaomiaosoft/PandaOCR#52]
嗑日本书同时学日文，想听到日语发音

**Comment by NOAME18** [comment]
还有就是右上角的识别内容显示区域，双击复制或者是右键复制出来的文本都是乱码..

**Comment by miaomiaosoft** [comment]
朗读通常是自动的，你的文本是日语那朗读就是日语，前提OCR也要选择支持日语的，目前已知有道OCR支持
如果有的朗读引擎不支持日语你可以自己换着一个个试，我试了搜狗支持，文本框右键菜单可以手动朗读

复制乱码感觉不是我的问题，参考：https://wenda.so.com/q/1373819535060982

**Comment by miaomiaosoft** [comment]
下个版本加上朗读语言配置项，不过不是所有引擎全都支持，需要自行测试
