### ISSUE TITLE
不能兼容4K分辨率的笔记本，xps9560

### ISSUE THREAD

**Issue by reidentify** [miaomiaosoft/PandaOCR#53]
4K分辨率怎么办，截取的最大范围是屏幕的1/4，求开发者适配一下，谢谢

**Comment by miaomiaosoft** [comment]
各种原因，我没法解决

参见：https://github.com/miaomiaosoft/PandaOCR/issues/17
或者：https://github.com/miaomiaosoft/PandaOCR/issues/37
