### ISSUE TITLE
报毒问题能解决下最好，不然这么方便的应用，不能推广很可惜

### ISSUE THREAD

**Issue by xyhere2001** [miaomiaosoft/PandaOCR#55]
基本普通用户里装机量大的 软件  windows defender，360 都在报毒
不敢给人用，也就自己用下。

**Comment by lvjinxin999** [comment]
提个建议，增加语音，输出MP3功能 这个很实用

Yang Xin <notifications@github.com> 于2019年9月13日周五 下午2:30写道：

**Comment by lvjinxin999** [comment]
增加语音，输出MP3功能 这个很实用
在增加一个 复制文字 可以朗读 语音的功能

王者 <lvjinxin999@gmail.com> 于2019年9月13日周五 下午3:24写道：

**Comment by miaomiaosoft** [comment]
可惜也没办法，误报主要还是杀毒的识别能力不行，可不是我的问题。
你们用360的可以顺手提交下认证，看它能不能解除误报

@lvjinxin999 保存语音功能其实已经有了，配置文件里“自动保存音频”就是
复制文字 可以朗读 语音的功能其实应该也有了，在程序界面那“是否监听复制”选择“监听文本并翻译”后就行了

**Comment by xyhere2001** [comment]
> 可惜也没办法，误报主要还是杀毒的识别能力不行，可不是我的问题。
> 你们用360的可以顺手提交下认证，看它能不能解除误报
> 国产杀毒里我测试火绒都不报毒
> 
> @lvjinxin999 保存语音功能其实已经有了，配置文件里“自动保存音频”就是
> 复制文字 可以朗读 语音的功能应该也有了，在程序界面那“是否监听复制”选择“监听文本并翻译”后就行了

是否能出个不压缩壳的版本解决误报问题？ 体积大点是能接受的。

**Comment by miaomiaosoft** [comment]
@xyhere2001 不压缩报毒的更多，放弃吧，你不知道E语言写的东西被很多杀毒歧视吗？你就是写个空程序什么代码也没有它只要识别是E语言编译的直接报毒，你能咋整？
