### ISSUE TITLE
杀软误报的问题就不要再报告了！

### ISSUE THREAD

**Issue by miaomiaosoft** [miaomiaosoft/PandaOCR#56]
很多已关闭的issues里已经解释过很多次了，以后此类问题不予回复并直接关闭！

总之再重复一遍：
程序本身没有任何恶意行为，包括自己写的代码和引用的第三方模块。
我的编译环境本身也装有ESET NOD32杀软，偶尔也会在虚拟机里用火绒检测！有一次拿到卡巴在线查毒结果也是安全。
那为什么360和微软WD等会误报？那你得去问它们为什么都2020年了技术还是这么烂！

然而对于普通用户来说，我的话肯定不能随便相信，那怎么办？我推荐一些工具给你分析程序具体行为：
在线行为分析：
https://s.threatbook.cn/
https://www.maldun.com/submit/submit_file/

本地行为分析：
Sandboxie
VirtualBox

行为分析也看不懂？那你只能参考用户评价了！
本软件最早发布于吾爱破解和卡饭论坛，都这么久了，如果真有病毒木马一定会有人发现的！（PS：程序本身没有任何加密保护，OD轻松反编译）

**Comment by innerbeast** [comment]
特地注册账号来感谢作者，希望作者大大不要放弃维护，不能维护的话最好可以继续开源哈，不要为一些烂人坏了心情。

**Comment by innerbeast** [comment]
也支持做成商业软件尝试收费，用来追剧，玩游戏，看资料这个都是神器，价格适中的话还是有生存市场的。为别人的努力付费本来也理所应当。

**Comment by zsylife** [comment]
建议出个win10关闭微软WD的教程 不然很多人不会
希望继续更新 蛮好用的

**Comment by miaomiaosoft** [comment]
> 也支持做成商业软件尝试收费，用来追剧，玩游戏，看资料这个都是神器，价格适中的话还是有生存市场的。为别人的努力付费本来也理所应当。

已增加捐助入口，暂以这种方式维持后续更新维护，商业化付费使用那种得弄注册码验证功能，可能还要做加壳保护程序不被破解，运行性能可能会降低对用户也不友好，还是算了。

**Comment by miaomiaosoft** [comment]
> 建议出个win10关闭微软WD的教程 不然很多人不会
> 希望继续更新 蛮好用的

目前还会继续更新，主要维护现有功能或引擎可用
关闭杀毒这个百度就行啦

**Comment by SwaggyMacro** [comment]
https://github.com/miaomiaosoft/PandaOCR.Pro/issues/22

**Comment by StrollStars** [comment]
感谢作者科普，难怪ESET两边检测出来会有不同，开始还以为是病毒库新旧问题，结果是版本差异。
