### ISSUE TITLE
支持朗读更多的文字

### ISSUE THREAD

**Issue by wajika** [miaomiaosoft/PandaOCR#57]
如果文字字数超过几千字，测试了所有带*的选项，无法边下边播。

**Comment by miaomiaosoft** [comment]
哥们，几千字，你这是拿去听小说呢？
不仅边下边播没用，先下再播应该也没用，都是演示引擎，不支持这么长文本，一般都限制在两三百字左右，就算是购买的API接口像百度一次最多也只能500字。
你有这种大需求建议换用更专业的语音合成工具或服务！

**Comment by wajika** [comment]
> 哥们，几千字，你这是拿去听小说呢？
> 不仅边下边播没用，先下再播应该也没用，都是演示引擎，不支持这么长文本，一般都限制在两三百字左右。
> 你有这种大需求建议换用更专业的语音合成工具或服务！

主要是读微信公众号文章
