### ISSUE TITLE
希望弹窗位置可调

### ISSUE THREAD

**Issue by smaragdus326** [miaomiaosoft/PandaOCR#58]
现在的弹窗是默认右下角，在内容数量差异严重的时候使用不太方便，只能将高度设的很大来让显示结果不遗漏，这样有时候不能取消的弹窗内容又遮挡了东西。希望加入弹窗坐标设置功能或弹窗文字可调向下对齐。此外清空当前弹窗内容的方法只有双击标题上的线程，自动隐藏也不太方便，希望有快捷键设置。
如果可以还希望增加朗读当前识别/翻译内容的快捷键以满足只有部分需要朗读的情况。
其他内容折腾了下使用效果非常好，虽然手动部分不支持高分屏缩放但固定截图手动输入坐标后是可以的，手动的用snipaste也很好用，感谢制作软件。

**Comment by smaragdus326** [comment]
> ```
>    现在的弹窗是默认右下角，在内容数量差异严重的时候使用不太方便，只能将高度设的很大来让显示结果不遗漏，这样有时候不能取消的弹窗内容又遮挡了东西。希望加入弹窗坐标设置功能或弹窗文字可调向下对齐。此外清空当前弹窗内容的方法只有双击标题上的线程，自动隐藏也不太方便，希望有快捷键设置。
>   如果可以还希望增加朗读当前识别/翻译内容的快捷键以满足只有部分需要朗读的情况。
>   其他内容折腾了下使用效果非常好，虽然手动部分不支持高分屏缩放但固定截图手动输入坐标后是可以的，手动的用snipaste也很好用，感谢制作软件。
> ```

**Comment by smaragdus326** [comment]
更正下关闭弹窗的问题，是我这边在使用缩放的条件下没有办法使用弹窗右边那个按钮的原因

**Comment by miaomiaosoft** [comment]
你可以取消本程序跟随系统DPI设置再试试能不能点关闭弹窗的按钮，我这没有高分屏，无法测试和解决这类问题。

弹窗部分一是为了美观，二是考虑到显示的文本不会也不能太多（工具设计之初就是适用于识别段落文本，不适合整篇文章或过长的文本），最终显示的是一张实时生成的PNG图片，不是普通的文本编辑框，比较不好处理自动调整或向下对齐，目前建议增加弹窗宽度或者降低文字大小取消加粗显示来增加文本显示数量。

下个版本会在主界面编辑框右键增加手动朗读的功能。

我不太喜欢快捷键操作，因为处理这个对我来说有点麻烦，如果你试了上面取消DPI的话还是无法点击弹窗按钮那下个版本我给你另一种操作来实现，按住CTRL+鼠标单击任务栏图标=复制识别文本、ALT+单击=复制翻译文本、空格+单击=强行结束线程包括关闭弹窗

**Comment by 007zero** [comment]
你发错人了。


 
---原始邮件---
发件人: "miao_miao"<notifications@github.com&gt;
发送时间: 2019年9月25日 20:52:23
收件人: "miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [miaomiaosoft/PandaOCR] 希望弹窗位置可调 (#58)



你可以取消本程序跟随系统DPI设置再试试能不能点关闭弹窗的按钮，我这没有高分屏，无法测试和解决这类问题。
 
弹窗部分一是为了美观，二是考虑到显示的文本不会也不能太多（工具设计之初就是适用于识别段落文本，不适合整篇文章或过长的文本），最终显示的是一张实时生成的PNG图片，不是普通的文本编辑框，比较不好处理自动调整或向下对齐，目前建议增加弹窗宽度或者降低文字大小取消加粗显示来增加文本显示数量。
 
下个版本会在主界面编辑框右键增加手动朗读的功能。
 
我不太喜欢快捷键操作，因为处理这个对我来说有点麻烦，如果你试了上面取消DPI的话还是无法点击弹窗按钮那下个版本我给你另一种操作来实现，按住CTRL+鼠标单击任务栏图标=复制识别文本、ALT+单击=复制翻译文本、空格+单击=强行结束线程包括关闭弹窗

**Comment by 007zero** [comment]
为什么我收到那么多这样的邮件？


 
---原始邮件---
发件人: "miao_miao"<notifications@github.com&gt;
发送时间: 2019年9月25日 20:52:23
收件人: "miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [miaomiaosoft/PandaOCR] 希望弹窗位置可调 (#58)



你可以取消本程序跟随系统DPI设置再试试能不能点关闭弹窗的按钮，我这没有高分屏，无法测试和解决这类问题。
 
弹窗部分一是为了美观，二是考虑到显示的文本不会也不能太多（工具设计之初就是适用于识别段落文本，不适合整篇文章或过长的文本），最终显示的是一张实时生成的PNG图片，不是普通的文本编辑框，比较不好处理自动调整或向下对齐，目前建议增加弹窗宽度或者降低文字大小取消加粗显示来增加文本显示数量。
 
下个版本会在主界面编辑框右键增加手动朗读的功能。
 
我不太喜欢快捷键操作，因为处理这个对我来说有点麻烦，如果你试了上面取消DPI的话还是无法点击弹窗按钮那下个版本我给你另一种操作来实现，按住CTRL+鼠标单击任务栏图标=复制识别文本、ALT+单击=复制翻译文本、空格+单击=强行结束线程包括关闭弹窗

**Comment by miaomiaosoft** [comment]
@007zero 你可能关注了什么，也可能GAYHUB邮件发错，我这没回错

**Comment by smaragdus326** [comment]
不启用缩放时增加宽高和字体大小的确能解决弹窗使用问题，但后果是主界面窗口和字体太小而难以使用。新的任务栏操作逻辑已经基本解决了这里缩放下按钮消失的问题。虽然本来想要config里定义png的坐标，不过弹窗位置也可以通过宽高度调整到右上角。问题已解决，感谢更新和回复。

**Comment by smaragdus326** [comment]
@007zero 请取消github通知中心的自动订阅功能并删除对本repo的关注
