### ISSUE TITLE
当前网络不畅或由于被过度滥用，本程序将中止运行！或者尝试重新启动！

### ISSUE THREAD

**Issue by xingshu1990** [miaomiaosoft/PandaOCR#6]
老哥，这个是什么问题啊。W7 64位系统，原本用着好好的，不知道为什么7月份某一天以后，就不能使用了。

**Comment by miaomiaosoft** [comment]
确保你能访问这个网站：http://blog.sina.com.cn
如果这网站不通，程序就可能会提示这个并闪退

**Comment by xingshu1990** [comment]
确定能打开新浪，而且我还特地开飞机和不开飞机都试了一下。都出现这个问题。

**Comment by miaomiaosoft** [comment]
在config.ini 配置文件第二行加上
Debug=C326BCCEEBE2EDC5FB742B591283FF4C

**Comment by xingshu1990** [comment]
谢谢 搞定了。

然后提个建议，是不是可以这样，每个人自己去注册一下百度OCR，可以自行输入百度ocr相关密钥之类的，然后选择普通型，以及精准型。我自己用python，复制了网络上的代码，使用百度ocr精准一些的那个API，只不过目前我做不到截图识别，只是全图识别。有时候需要OCR PDF目录，全图识别是从左到右，连页码也直接OCR了。这个就比较麻烦。

所以，作者是否可以考虑一下。

**Comment by miaomiaosoft** [comment]
百度OCR的API版其实也早已内置了，在config.ini内
BD_OCR=1
BD_OCR_id=pHYUg3eDVomXXX
BD_OCR_secret=a161vVuzmw3s0iRvrY7CwXXX
BD_OCR=中数值1是免费的DEMO版，2就是需要自行申请KEY的API版，下面两项就是自己的KEY。

已经更新将API版改为精准版接口，多类型就不做了，百度的类型太多了，请重新下载：
https://github.com/miaomiaosoft/PandaOCR/releases/tag/1.9

**Comment by xingshu1990** [comment]
谢谢
