### ISSUE TITLE
英文系统下UI全为乱码

### ISSUE THREAD

**Issue by scegg** [miaomiaosoft/PandaOCR#61]
在英文Windows 10运行软件时，主界面，系统托盘菜单等均为乱码。

**Comment by miaomiaosoft** [comment]
https://github.com/miaomiaosoft/Keyda/issues/14
这是编程语言在编码上不支持unicode的坑，暂时解决不了，抱歉

**Comment by heloook** [comment]
我找到解决方法了 https://www.zhihu.com/question/34761050

**Comment by heloook** [comment]
设置非Unicode应用程序语言为中文

**Comment by miaomiaosoft** [comment]
> 我找到解决方法了 https://www.zhihu.com/question/34761050

谢谢，看来不全是程序编码的问题
