### ISSUE TITLE
目前一些已知并无法解决的问题

### ISSUE THREAD

**Issue by miaomiaosoft** [miaomiaosoft/PandaOCR#62]
1. 英文或繁体系统下整个程序界面中文将可能会乱码
2. 韩文同样会乱码，即使OCR支持识别韩文也显示不了
3. 不支持高分屏或者系统DPI缩放，截图将不完整，弹窗按钮无法点击，除非你将本程序的属性设置为不使用系统DPI
4. 只支持WIN系统，MAC之类的不会有
5. 文本朗读建议在200-500字以内，太长的文本需要更长的下载等待时间影响体验，也不打算利用分割多段的方式支持长文本朗读
6. 不会增加表格或公式识别，我真的一点都用不到

以上如有遇到或符合自己的情况就不用反馈或建议了

**Comment by hanshuangcao** [comment]
语音怎末关，每次打开都有语音，在一些办公地方比较尴尬

**Comment by miaomiaosoft** [comment]
> 语音怎末关，每次打开都有语音，在一些办公地方比较尴尬

自己翻一下配置文件

**Comment by wolfjojo** [comment]
希望能修复韩语翻译啊...截图识别没问题.就是翻译失败了.哈
现在模拟器玩日文和韩文游戏的很多吧应该

**Comment by miaomiaosoft** [comment]
> 希望能修复韩语翻译啊...截图识别没问题.就是翻译失败了.哈
> 现在模拟器玩日文和韩文游戏的很多吧应该

日文是支持的，韩文因为是UNICODE编码，编程语言或者说编译程序不支持
想要解决除非换语言重新写，然而我又不会，即使会也不太可能因为一个自己不太会用到的功能去重写一遍，这太伤身体了

**Comment by wolfjojo** [comment]
> 日文是支持的，韩文因为是UNICODE编码，编程语言或者说编译程序不支持
> 想要解决除非换语言重新写，然而我又不会，即使会也不太可能因为一个自己不太会用到的功能去重写一遍，这太伤身体了

这太尴尬了....我还想着如果韩文能识别出文字我粘贴翻译一下也行啊..看来完蛋.有道的截图翻译完全不行...

**Comment by Artniner** [comment]
请问怎么设置不使用系统DPI，配置文件里没找到

**Comment by innerbeast** [comment]
同事分享给我的软件，特地注册了GitHub来感谢作者，因为软件上没有打赏通道。这么优秀的软件，希望作者不要放弃，如果一定要放弃的话，能开源也可以啊，愿意付费使用

**Comment by WH-103** [comment]
希望可以增加公式识别功能，识别次数收费也可以

**Comment by miaomiaosoft** [comment]
> 希望可以增加公式识别功能，识别次数收费也可以

我再考虑一下，如果不难实现的话就增加吧

**Comment by DXJian** [comment]
大佬，德语无法识别可以加入吗？

**Comment by DXJian** [comment]
> > > > 大佬，德语无法识别可以加入吗？
> > > 
> > > 
> > > 我这边测试应该是支持的
> > > 你可以说具体点，举个例子？
> > 
> > 
> > 主要是三个变音和ss没有办法识别 ：
> > gewöhnen识别成 gewohnen
> > heiBen 识别成 heiB（变成一个ABC的B了）en
> 
> 这样，你给两段比较完整的句子，里面尽量包含多个容易和英文混淆的字符，同时附上标准翻译
> 我好测试看看
> 
> 识别部分的代码我没改动的，应该是网络问题，可能和今天全国网站变灰或不提供服务有关吧

Darauf kommt es doch überhaupt nicht an.Hast du dir denn die Konsequenzen überlegt?Bei deinem mittelmäßigen Realschulabschluss hast du nicht viele Möglichkeiten.
译：这根本不是重点，你考虑过后果吗？你中学毕业时没有很多选择。
临时找了段包含了äüö和ß的句子，这些字符如果识别错翻译起来在很多句子中会有很大的差异。再次感谢。

**Comment by miaomiaosoft** [comment]
> > > > > 大佬，德语无法识别可以加入吗？
> > > > 
> > > > 
> > > > 我这边测试应该是支持的
> > > > 你可以说具体点，举个例子？
> > > 
> > > 
> > > 主要是三个变音和ss没有办法识别 ：
> > > gewöhnen识别成 gewohnen
> > > heiBen 识别成 heiB（变成一个ABC的B了）en
> > 
> > 
> > 这样，你给两段比较完整的句子，里面尽量包含多个容易和英文混淆的字符，同时附上标准翻译
> > 我好测试看看
> > 识别部分的代码我没改动的，应该是网络问题，可能和今天全国网站变灰或不提供服务有关吧
> 
> Darauf kommt es doch überhaupt nicht an.Hast du dir denn die Konsequenzen überlegt?Bei deinem mittelmäßigen Realschulabschluss hast du nicht viele Möglichkeiten.
> 译：这根本不是重点，你考虑过后果吗？你中学毕业时没有很多选择。
> 临时找了段包含了äüö和ß的句子，这些字符如果识别错翻译起来在很多句子中会有很大的差异。再次感谢。

行，我明天看看是程序的问题还是OCR引擎的问题

**Comment by WH-103** [comment]
可以&nbsp; 这个应该不用德语，比如这个公式图片，识别出这串代码\psi_{a, b}(t)=\frac{1}{\sqrt{|a|}} \psi\left[\frac{t-b}{a}\right], a, b \in \mathrm{R}, a \neq 0&nbsp; &nbsp;在MathType中直接粘贴代码就直接能插入公式&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dengxj"<notifications@github.com&gt;; 
发送时间: 2020年4月4日(星期六) 凌晨2:08
收件人: "miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;; 
抄送: "执着。"<1573456903@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [miaomiaosoft/PandaOCR] 目前一些已知并无法解决的问题 (#62)





 
大佬，德语无法识别可以加入吗？

**Comment by miaomiaosoft** [comment]
> > > > > 大佬，德语无法识别可以加入吗？
> > > > 
> > > > 
> > > > 我这边测试应该是支持的
> > > > 你可以说具体点，举个例子？
> > > 
> > > 
> > > 主要是三个变音和ss没有办法识别 ：
> > > gewöhnen识别成 gewohnen
> > > heiBen 识别成 heiB（变成一个ABC的B了）en
> > 
> > 
> > 这样，你给两段比较完整的句子，里面尽量包含多个容易和英文混淆的字符，同时附上标准翻译
> > 我好测试看看
> > 识别部分的代码我没改动的，应该是网络问题，可能和今天全国网站变灰或不提供服务有关吧
> 
> Darauf kommt es doch überhaupt nicht an.Hast du dir denn die Konsequenzen überlegt?Bei deinem mittelmäßigen Realschulabschluss hast du nicht viele Möglichkeiten.
> 译：这根本不是重点，你考虑过后果吗？你中学毕业时没有很多选择。
> 临时找了段包含了äüö和ß的句子，这些字符如果识别错翻译起来在很多句子中会有很大的差异。再次感谢。

无能为力，OCR的API版引擎测试基本都支持德文，但程序本身不支持德语某些单词，ü是支持的，像äß（应该属于unicode编码）这种会乱码，那就跟韩文一样是不行的了
![BaiduShurufa_2020-4-4_16-33-51](https://user-images.githubusercontent.com/4084875/78422506-53b69980-7692-11ea-99cb-030487bfc206.jpg)

**Comment by WH-103** [comment]
好的，感谢您的研究





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miao_miao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月4日(星期六) 下午4:37
收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;;
抄送:&nbsp;"执着。"<1573456903@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 目前一些已知并无法解决的问题 (#62)





      
大佬，德语无法识别可以加入吗？
  
我这边测试应该是支持的
 你可以说具体点，举个例子？
  
主要是三个变音和ss没有办法识别 ：
 gewöhnen识别成 gewohnen
 heiBen 识别成 heiB（变成一个ABC的B了）en
  
这样，你给两段比较完整的句子，里面尽量包含多个容易和英文混淆的字符，同时附上标准翻译
 我好测试看看
 识别部分的代码我没改动的，应该是网络问题，可能和今天全国网站变灰或不提供服务有关吧
  
Darauf kommt es doch überhaupt nicht an.Hast du dir denn die Konsequenzen überlegt?Bei deinem mittelmäßigen Realschulabschluss hast du nicht viele Möglichkeiten.
 译：这根本不是重点，你考虑过后果吗？你中学毕业时没有很多选择。
 临时找了段包含了äüö和ß的句子，这些字符如果识别错翻译起来在很多句子中会有很大的差异。再次感谢。
  
无能为力，OCR的API版引擎测试基本都支持德文，但程序本身不支持德语某些单词，ü是支持的，像äß（应该属于unicode编码）这种会乱码，那就跟韩文一样是不行的了

**Comment by miaomiaosoft** [comment]
> 好的，感谢您的研究
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"miao_miao"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月4日(星期六) 下午4:37 收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;; 抄送:&nbsp;"执着。"<1573456903@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 目前一些已知并无法解决的问题 (#62) 大佬，德语无法识别可以加入吗？ 我这边测试应该是支持的 你可以说具体点，举个例子？ 主要是三个变音和ss没有办法识别 ： gewöhnen识别成 gewohnen heiBen 识别成 heiB（变成一个ABC的B了）en 这样，你给两段比较完整的句子，里面尽量包含多个容易和英文混淆的字符，同时附上标准翻译 我好测试看看 识别部分的代码我没改动的，应该是网络问题，可能和今天全国网站变灰或不提供服务有关吧 Darauf kommt es doch überhaupt nicht an.Hast du dir denn die Konsequenzen überlegt?Bei deinem mittelmäßigen Realschulabschluss hast du nicht viele Möglichkeiten. 译：这根本不是重点，你考虑过后果吗？你中学毕业时没有很多选择。 临时找了段包含了äüö和ß的句子，这些字符如果识别错翻译起来在很多句子中会有很大的差异。再次感谢。 无能为力，OCR的API版引擎测试基本都支持德文，但程序本身不支持德语某些单词，ü是支持的，像äß（应该属于unicode编码）这种会乱码，那就跟韩文一样是不行的了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

上面不是回你的，你要的表格识别我还没研究呢

**Comment by WH-103** [comment]
哈哈哈，弄混了 不好意思



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "miao_miao"<notifications@github.com&gt;; 
发送时间: 2020年4月4日(星期六) 下午4:43
收件人: "miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;; 
抄送: "执着。"<1573456903@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [miaomiaosoft/PandaOCR] 目前一些已知并无法解决的问题 (#62)





  
好的，感谢您的研究
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"miao_miao"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月4日(星期六) 下午4:37 收件人:&nbsp;"miaomiaosoft/PandaOCR"<PandaOCR@noreply.github.com&gt;; 抄送:&nbsp;"执着。"<1573456903@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [miaomiaosoft/PandaOCR] 目前一些已知并无法解决的问题 (#62) 大佬，德语无法识别可以加入吗？ 我这边测试应该是支持的 你可以说具体点，举个例子？ 主要是三个变音和ss没有办法识别 ： gewöhnen识别成 gewohnen heiBen 识别成 heiB（变成一个ABC的B了）en 这样，你给两段比较完整的句子，里面尽量包含多个容易和英文混淆的字符，同时附上标准翻译 我好测试看看 识别部分的代码我没改动的，应该是网络问题，可能和今天全国网站变灰或不提供服务有关吧 Darauf kommt es doch überhaupt nicht an.Hast du dir denn die Konsequenzen überlegt?Bei deinem mittelmäßigen Realschulabschluss hast du nicht viele Möglichkeiten. 译：这根本不是重点，你考虑过后果吗？你中学毕业时没有很多选择。 临时找了段包含了äüö和ß的句子，这些字符如果识别错翻译起来在很多句子中会有很大的差异。再次感谢。 无能为力，OCR的API版引擎测试基本都支持德文，但程序本身不支持德语某些单词，ü是支持的，像äß（应该属于unicode编码）这种会乱码，那就跟韩文一样是不行的了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
上面不是回你的，你要的表格识别我还没研究呢

**Comment by kkanton** [comment]
> > 语音怎末关，每次打开都有语音，在一些办公地方比较尴尬
> 
> 自己翻一下配置文件

小白不懂怎么修改配置文件：（

**Comment by miaomiaosoft** [comment]
> > > 语音怎末关，每次打开都有语音，在一些办公地方比较尴尬
> > 
> > 
> > 自己翻一下配置文件
> 
> 小白不懂怎么修改配置文件：（

更改配置文件：
提示方式=0 或其他数字

**Comment by liu220mao** [comment]
今天突然就乱码了，看了下有更新，然后更新到了v2.51最新版本，还是乱码。1、系统语言是中文
2、目录是D盘根目录（D:\PandaOCR），之前还好好的，怎么突然就这样了，是因为更新了Win10原因吗？

**Comment by miaomiaosoft** [comment]
> 今天突然就乱码了，看了下有更新，然后更新到了v2.51最新版本，还是乱码。1、系统语言是中文
> 2、目录是D盘根目录（D:\PandaOCR），之前还好好的，怎么突然就这样了，是因为更新了Win10原因吗？

尝试卸载这次的更新看看能不能恢复吧，WIN10不要经常更新，它的更新经常出现BUG，或者晚一点更新

**Comment by liu220mao** [comment]
> > 今天突然就乱码了，看了下有更新，然后更新到了v2.51最新版本，还是乱码。1、系统语言是中文
> > 2、目录是D盘根目录（D:\PandaOCR），之前还好好的，怎么突然就这样了，是因为更新了Win10原因吗？
> 
> 尝试卸载这次的更新看看能不能恢复吧，WIN10不要经常更新，它的更新经常出现BUG，或者晚一点更新

解决了：（控制面板—区域—管理—更改系统区域设置—Beta 版：使用Unicode UTF-8提供全球语言支持）不勾选就好了。

**Comment by miaomiaosoft** [comment]
> > > 今天突然就乱码了，看了下有更新，然后更新到了v2.51最新版本，还是乱码。1、系统语言是中文
> > > 2、目录是D盘根目录（D:\PandaOCR），之前还好好的，怎么突然就这样了，是因为更新了Win10原因吗？
> > 
> > 
> > 尝试卸载这次的更新看看能不能恢复吧，WIN10不要经常更新，它的更新经常出现BUG，或者晚一点更新
> 
> 解决了：（控制面板—区域—管理—更改系统区域设置—Beta 版：使用Unicode UTF-8提供全球语言支持）不勾选就好了。

意思不和WIN10更新有关咯？只是你自己改了系统设置导致的吧

**Comment by liu220mao** [comment]
> > > > 今天突然就乱码了，看了下有更新，然后更新到了v2.51最新版本，还是乱码。1、系统语言是中文
> > > > 2、目录是D盘根目录（D:\PandaOCR），之前还好好的，怎么突然就这样了，是因为更新了Win10原因吗？
> > > 
> > > 
> > > 尝试卸载这次的更新看看能不能恢复吧，WIN10不要经常更新，它的更新经常出现BUG，或者晚一点更新
> > 
> > 
> > 解决了：（控制面板—区域—管理—更改系统区域设置—Beta 版：使用Unicode UTF-8提供全球语言支持）不勾选就好了。
> 
> 意思不和WIN10更新有关咯？只是你自己改了系统设置导致的吧

嗯嗯，是的

**Comment by miaomiaosoft** [comment]
> > > > > 今天突然就乱码了，看了下有更新，然后更新到了v2.51最新版本，还是乱码。1、系统语言是中文
> > > > > 2、目录是D盘根目录（D:\PandaOCR），之前还好好的，怎么突然就这样了，是因为更新了Win10原因吗？
> > > > 
> > > > 
> > > > 尝试卸载这次的更新看看能不能恢复吧，WIN10不要经常更新，它的更新经常出现BUG，或者晚一点更新
> > > 
> > > 
> > > 解决了：（控制面板—区域—管理—更改系统区域设置—Beta 版：使用Unicode UTF-8提供全球语言支持）不勾选就好了。
> > 
> > 
> > 意思不和WIN10更新有关咯？只是你自己改了系统设置导致的吧
> 
> 嗯嗯，是的

OK 谢谢

**Comment by 18476305640** [comment]
如果识别的文字能分段就好了。

**Comment by peasshoter** [comment]
//==========================Crash Report(YangTuSoft)===========================
Crash Program：   [YTSOFT][xfnet.dll]

DLL Information:

Exception Code : C0000005 ACCESS_VIOLATION
Crash Address:  0B304AF8 01:C000000F 

CPU:
EAX:0B304AF8
EBX:00000000
ECX:00DD0D68
EDX:00000000
ESI:0B304AF8
EDI:00000000
CS:EIP:0023:0B304AF8
SS:ESP:002B:0018FBB0  EBP:0018FBD8
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010206

PDB Search Path:.;E:\downloads\Programs\

Call Stack:
Address   Frame     Function            SourceFile
0B304AF8  0018FBAC  FrmAddr Failed:870000:00000000 
755D62FA  0018FBD8  FrmAddr Failed:870001:000062FA C:\windows\syswow64\USER32.dll
755D6D3A  0018FC50  FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
755E0D3F  0018FC88  FrmAddr Failed:870001:00010D3F C:\windows\syswow64\USER32.dll
755E853A  0018FCA8  FrmAddr Failed:870001:0001853A C:\windows\syswow64\USER32.dll
0045D3A7  0018FCD8  FrmAddr Failed:870001:0005C3A7 E:\downloads\Programs\PandaOCR.exe
0045D16D  0018FD08  FrmAddr Failed:870001:0005C16D E:\downloads\Programs\PandaOCR.exe
0045D05C  0018FD30  FrmAddr Failed:870001:0005C05C E:\downloads\Programs\PandaOCR.exe
0045D416  0018FD7C  FrmAddr Failed:870001:0005C416 E:\downloads\Programs\PandaOCR.exe
755D6D3A  0018FDF4  FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
755D77C4  0018FE54  FrmAddr Failed:870001:000077C4 C:\windows\syswow64\USER32.dll
755D7BCA  0018FE64  FrmAddr Failed:870001:00007BCA C:\windows\syswow64\USER32.dll
00589699  0018FE74  FrmAddr Failed:870001:00188699 E:\downloads\Programs\PandaOCR.exe
Stack Param Info:

Call Stack:
Address   Frame     Function            SourceFile
0B304AF8  0018FBAC  FrmAddr Failed:870000:00000000 

755D62FA  0018FBD8  FrmAddr Failed:870001:000062FA C:\windows\syswow64\USER32.dll

755D6D3A  0018FC50  FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll

755E0D3F  0018FC88  FrmAddr Failed:870001:00010D3F C:\windows\syswow64\USER32.dll

755E853A  0018FCA8  FrmAddr Failed:870001:0001853A C:\windows\syswow64\USER32.dll

0045D3A7  0018FCD8  FrmAddr Failed:870001:0005C3A7 E:\downloads\Programs\PandaOCR.exe

0045D16D  0018FD08  FrmAddr Failed:870001:0005C16D E:\downloads\Programs\PandaOCR.exe

0045D05C  0018FD30  FrmAddr Failed:870001:0005C05C E:\downloads\Programs\PandaOCR.exe

0045D416  0018FD7C  FrmAddr Failed:870001:0005C416 E:\downloads\Programs\PandaOCR.exe

755D6D3A  0018FDF4  FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll

755D77C4  0018FE54  FrmAddr Failed:870001:000077C4 C:\windows\syswow64\USER32.dll

755D7BCA  0018FE64  FrmAddr Failed:870001:00007BCA C:\windows\syswow64\USER32.dll

00589699  0018FE74  FrmAddr Failed:870001:00188699 E:\downloads\Programs\PandaOCR.exe


每次更新，点通知就闪退，也没打开网页

**Comment by miaomiaosoft** [comment]
> //==========================Crash Report(YangTuSoft)===========================
> Crash Program： [YTSOFT][xfnet.dll]
> 
> DLL Information:
> 
> Exception Code : C0000005 ACCESS_VIOLATION
> Crash Address: 0B304AF8 01:C000000F
> 
> CPU:
> EAX:0B304AF8
> EBX:00000000
> ECX:00DD0D68
> EDX:00000000
> ESI:0B304AF8
> EDI:00000000
> CS:EIP:0023:0B304AF8
> SS:ESP:002B:0018FBB0 EBP:0018FBD8
> DS:002B ES:002B FS:0053 GS:002B
> Flags:00010206
> 
> PDB Search Path:.;E:\downloads\Programs\
> 
> Call Stack:
> Address Frame Function SourceFile
> 0B304AF8 0018FBAC FrmAddr Failed:870000:00000000
> 755D62FA 0018FBD8 FrmAddr Failed:870001:000062FA C:\windows\syswow64\USER32.dll
> 755D6D3A 0018FC50 FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
> 755E0D3F 0018FC88 FrmAddr Failed:870001:00010D3F C:\windows\syswow64\USER32.dll
> 755E853A 0018FCA8 FrmAddr Failed:870001:0001853A C:\windows\syswow64\USER32.dll
> 0045D3A7 0018FCD8 FrmAddr Failed:870001:0005C3A7 E:\downloads\Programs\PandaOCR.exe
> 0045D16D 0018FD08 FrmAddr Failed:870001:0005C16D E:\downloads\Programs\PandaOCR.exe
> 0045D05C 0018FD30 FrmAddr Failed:870001:0005C05C E:\downloads\Programs\PandaOCR.exe
> 0045D416 0018FD7C FrmAddr Failed:870001:0005C416 E:\downloads\Programs\PandaOCR.exe
> 755D6D3A 0018FDF4 FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
> 755D77C4 0018FE54 FrmAddr Failed:870001:000077C4 C:\windows\syswow64\USER32.dll
> 755D7BCA 0018FE64 FrmAddr Failed:870001:00007BCA C:\windows\syswow64\USER32.dll
> 00589699 0018FE74 FrmAddr Failed:870001:00188699 E:\downloads\Programs\PandaOCR.exe
> Stack Param Info:
> 
> Call Stack:
> Address Frame Function SourceFile
> 0B304AF8 0018FBAC FrmAddr Failed:870000:00000000
> 
> 755D62FA 0018FBD8 FrmAddr Failed:870001:000062FA C:\windows\syswow64\USER32.dll
> 
> 755D6D3A 0018FC50 FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
> 
> 755E0D3F 0018FC88 FrmAddr Failed:870001:00010D3F C:\windows\syswow64\USER32.dll
> 
> 755E853A 0018FCA8 FrmAddr Failed:870001:0001853A C:\windows\syswow64\USER32.dll
> 
> 0045D3A7 0018FCD8 FrmAddr Failed:870001:0005C3A7 E:\downloads\Programs\PandaOCR.exe
> 
> 0045D16D 0018FD08 FrmAddr Failed:870001:0005C16D E:\downloads\Programs\PandaOCR.exe
> 
> 0045D05C 0018FD30 FrmAddr Failed:870001:0005C05C E:\downloads\Programs\PandaOCR.exe
> 
> 0045D416 0018FD7C FrmAddr Failed:870001:0005C416 E:\downloads\Programs\PandaOCR.exe
> 
> 755D6D3A 0018FDF4 FrmAddr Failed:870001:00006D3A C:\windows\syswow64\USER32.dll
> 
> 755D77C4 0018FE54 FrmAddr Failed:870001:000077C4 C:\windows\syswow64\USER32.dll
> 
> 755D7BCA 0018FE64 FrmAddr Failed:870001:00007BCA C:\windows\syswow64\USER32.dll
> 
> 00589699 0018FE74 FrmAddr Failed:870001:00188699 E:\downloads\Programs\PandaOCR.exe
> 
> 每次更新，点通知就闪退，也没打开网页

哪里的通知，主窗口还是右下角弹窗

**Comment by sjy234** [comment]
您好，我更新了2.55版本，现在的情况是一翻译就会弹出软件界面， 之前2.52版本可以直接在屏幕右下角显示翻译，这个版本怎么设置才可以？？希望可以发送邮件478711953@qq.com

**Comment by miaomiaosoft** [comment]
> 您好，我更新了2.55版本，现在的情况是一翻译就会弹出软件界面， 之前2.52版本可以直接在屏幕右下角显示翻译，这个版本怎么设置才可以？？希望可以发送邮件[478711953@qq.com](mailto:478711953@qq.com)

我无法给你发QQ邮件：
> 无法发送到<478711953@qq.com>, 原因是:收件人（478711953@qq.com）关闭了数字帐号邮箱

具体开了哪些功能，最好截图看一下，邮件回复如果不方便可以点软件上的反馈按钮加群

**Comment by massolala** [comment]
鼠标在屏幕左上角是会出发截屏ocr，请问有关闭这个的选项吗，找了下没发现

**Comment by miaomiaosoft** [comment]
> 鼠标在屏幕左上角是会出发截屏ocr，请问有关闭这个的选项吗，找了下没发现

再仔细找找？

“边角触发截图=0”

**Comment by XZPQNBV5** [comment]
[https://wx1.sbimg.cn/2020/05/31/Snipaste_2020-05-31_23-09-52.png](url) 1920*1280de 屏幕只能截取部分区域，如何解决

**Comment by miaomiaosoft** [comment]
> [https://wx1.sbimg.cn/2020/05/31/Snipaste_2020-05-31_23-09-52.png](url) 1920*1280de 屏幕只能截取部分区域，如何解决

不是有写吗，而且有问题应该发新帖，在这回复会导致上面不相关的人也收到邮件通知
不支持高分屏或者系统DPI缩放，截图可能不完整，弹窗按钮无法点击，除非你将本程序的属性设置为不使用系统DPI或勾选“高级截图”（ #17 ）

**Comment by XZPQNBV5** [comment]
不好意思呀，小白第一次发帖

**Comment by XZPQNBV5** [comment]
试了下，高级截图可以解决这个问题，谢谢大神

**Comment by xtay1625** [comment]
我试了一下，好像双屏幕状态下，无法对次屏幕截图识别，只能在主屏上操作。

**Comment by miaomiaosoft** [comment]
> 我试了一下，好像双屏幕状态下，无法对次屏幕截图识别，只能在主屏上操作。

在截图组件那选高级截图支持双屏
