### ISSUE TITLE
源码呢？

### ISSUE THREAD

**Issue by livehl** [miaomiaosoft/PandaOCR#63]
说好的开源？就是把下载文件放上来？
还反复说不解决杀软误报。
我就怕了，怕不是打着开源的幌子放肉鸡？
恰饭请直接放捐助二维码，开源软件收费也行，打着开源的幌子做下三滥，不得好死!

**Comment by miaomiaosoft** [comment]
![QQ截图20191003102009](https://user-images.githubusercontent.com/4084875/66094663-665af380-e5c7-11e9-968f-63c2b3e588aa.jpg)

既然你这么暴躁，戾气这么重，那我也就不客气的回复了！

我从来没在任何地方声称这是开源工具，当然我也知道有一些转载网站看到GITHUB网站就认为是开源，那是他们的问题
我早就在项目首页写明“开源？好的，马上就开！”，这意思你看不懂那就是你和语文老师的问题了
误报问题我已经解释很多了，傻逼要用还非只信傻逼杀软我有什么办法？为什么卡巴和NOD32就不报呢？是卡巴更智能还是更烂？你解释下！
你怕就别用呗，搞的好像有人求着你用，你用不用我跟我不发生半毫利益关系
放肉鸡？表述不清我帮你纠正，那叫放后门，这事请你实锤，否则建议闭嘴（程序只加了压缩壳没加密，你自己没那个能力可以花点小钱请专业人士分析反编译）！
我可谢谢你的建议，但我不靠这玩意恰饭，也不需要收费，当然话可不能说死，但目前就是这样！
“打着开源的幌子做下三滥，不得好死” 我还是建议你实锤，否则不得好死的可能得先是你

本来这将会是我在GITHUB上开源的第二个小工具，可惜吧，我TM就无私分享自用工具还TM被你骂，就是因为你这样素质的人太多，我已经渐渐失去了开源的兴趣，开源本来是为了交流学习，共同维护提高，可在某些没那个技术嘴还臭九年义务教育都没读完的人眼里开源的意义只剩下自证程序清白，这有什么意义！

**Comment by 2220209876** [comment]
Cent大军来袭

**Comment by ilvjyw** [comment]
艹你老母 就是你这种喷子 360孤儿太多 害的多少大佬的作品不更了 
不懂装懂的辣鸡  丢你老母 鄙视你 !
