### ISSUE TITLE
关于左上角左键点击LOGO之后的语音问题。。。。。

### ISSUE THREAD

**Issue by RudeTheJack** [miaomiaosoft/PandaOCR#64]
能不能取消了啊，每次打开软件都要随时提防着，但又忍不住想要去点，我心好累啊2333333333

**Comment by miaomiaosoft** [comment]
帮你问过医生了，说这毛病他们可以治！
![v2-18118d654bc772ed278d2cc1e530097d_hd](https://user-images.githubusercontent.com/4084875/66134335-c46cf280-e62a-11e9-879c-62b87de05620.jpg)
如果有第二个和你一样有这种奇怪需求的话我就在新版帮你取消

**Comment by huanghe2015** [comment]
埋个这样的彩蛋😭

**Comment by RudeTheJack** [comment]
> 埋个这样的彩蛋😭

刚发现的时候把我吓一跳

**Comment by Topher887** [comment]
软件很好用，就这个声音这个有点强迫症，如果可以的话请去掉或者加个开关吧，无意冒犯，还有感谢

**Comment by miaomiaosoft** [comment]
你们太坏了吧，明明不点就可以的事
服了你们，下个版本我看看怎么处理下

**Comment by Topher887** [comment]
> 你们太坏了吧，明明不点就可以的事
> 服了你们，下个版本我看看怎么处理下

给大佬添麻烦了，多谢多谢

**Comment by miaomiaosoft** [comment]
新版已加配置
其他调试参数=讯飞发音:1@x_yiping|备用引擎日志:1|手贱开关:1|

手贱开关:0  就是关
