### ISSUE TITLE
不支持多屏幕

### ISSUE THREAD

**Issue by GTSeventeEn** [miaomiaosoft/PandaOCR#69]
谢谢作者。发现软件，高级截图方式是支持多屏幕截屏识别，但是普通方式不支持。
小意见: OCR软件，目的是为了识别文字，那么是否考虑将识别结果文字置于左边大位置，实际上，用户可能不关心原始截图。

**Comment by miaomiaosoft** [comment]
非高级截图确实不支持，所以才会有一个高级截图

"将识别结果文字置于左边大位置"
意思是去掉截图显示部分么，感觉不行吧
如果你觉得右边的文本框显示的文本太少你可以双击启用大窗口显示

**Comment by GTSeventeEn** [comment]
谢谢。发现文本框右键之后还有隐藏功能。赞一个。
