### ISSUE TITLE
【建议】能不能添加一个新功能

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#7]
1丶比如主窗识别一整段然后是左键选中一个单词或部分按ctrl (自定义) 发音

2丶或者不知道能不能适用win全局........
直接鼠标移动到单词上按ctrl (自定义) 就可以单独识别和发音
![2018 09 16 17 41 43](https://user-images.githubusercontent.com/25548230/45595062-65651d00-b9d8-11e8-9d3b-c7917c071127.gif)

源自类似下面这个chrome拓展翻译侠的操作
https://github.com/magic-FE/translate-man

**Comment by miaomiaosoft** [comment]
我做不到这么复杂的
既然都有不少现成的扩展，就没必要用全局的替代了
