### ISSUE TITLE
能否在不选择修正文本的时候识别文本去除每段开头的空格

### ISSUE THREAD

**Issue by ATTNT** [miaomiaosoft/PandaOCR#72]
工作中不喜欢合并文本，直接复制段落，但选择不修正文本厚每段开都都有2个空格，要手动去除，有点麻烦，最好增加多一个保持段落又去除开头空格的修正模式！谢谢

**Comment by miaomiaosoft** [comment]
修改配置
行首空格=0
或者改为2就只会在智能合并时有空格

**Comment by ATTNT** [comment]
感谢回复，原来是我研究不仔细，谢谢
