### ISSUE TITLE
联网问题。需要HTTP系统代理功能。

### ISSUE THREAD

**Issue by tinyboxxx** [miaomiaosoft/PandaOCR#75]
公司电脑需要设置IE代理联网。

![图片](https://user-images.githubusercontent.com/13427224/68275790-88a0cf00-00a7-11ea-8789-c4223094e043.png)

可否增加代理功能？

**Comment by miaomiaosoft** [comment]
软件应该会跟随系统代理设置
如果你想让软件使用独立的代理可以试试 SocksCap64 
因为从没想过会需要这种功能，现在再加的话会比较麻烦
