### ISSUE TITLE
关于快捷键拦截问题

### ISSUE THREAD

**Issue by hqyyqh** [miaomiaosoft/PandaOCR#78]
## 运行环境

PandaOCR 版本：<VER：2.43>
Windows：1903

## 出现的问题

- 设置了截图热键之后（比如 F4），在浏览器按下快捷键，这时会定位到浏览器地址栏，然后再启动 PandaOCR 截图。

- 接着再次将截图热键改为 F5 进行测试，在浏览器按下 F5 之后，会出现先开始刷新网页，然后再截图的情况。

这个是快捷键拦截有问题吗？

## 演示

**F4 定位到浏览器地址栏**
![F4_test](https://user-images.githubusercontent.com/38676455/68531002-9f198580-0348-11ea-848b-2a0e098a9a62.gif)

**F5 刷新网页**
![F5_test](https://user-images.githubusercontent.com/38676455/68531004-a17bdf80-0348-11ea-88db-cb1116fd09cb.gif)

**Comment by miaomiaosoft** [comment]
F4和F5本身在浏览器上就是快捷键啊，F5就是通用的刷新键
这不冲突，是正常的
你要么设置别的按键，要么把鼠标移到屏幕左上角来启动截图

**Comment by hqyyqh** [comment]
我的理解是按下个快捷键应该只有一个应用程序响应。
因为有些应用内置的快捷键(比如vscode，sublimetext)就一大堆。设置一个完全不与其他应用冲突的快捷键太难了。
比如我将snipaste的截图快捷键设置为 F4，那么在浏览器内按下F4的时候只会触发截图，而不会定位到地址栏。这是我想要的效果。

**Comment by miaomiaosoft** [comment]
知道你意思了，其实很早的版本就是你说的这样
但是发现这种方法会被某些游戏给屏蔽，导致在游戏中无法截图，所以之后才换的现在这种全局的方式

下个版本我尝试增加一个配置项“热键类型”来应用不同的方式

**Comment by miaomiaosoft** [comment]
已更新，新版已增加此配置项
