### ISSUE TITLE
【建议】使用了几天，可以提几点建议吗

### ISSUE THREAD

**Issue by nancheung97** [miaomiaosoft/PandaOCR#79]
1.程序主窗口可以调节大小（在高分屏下窗体显得很小很小）；
![image](https://user-images.githubusercontent.com/34061813/68540318-bc8f3380-03ca-11ea-9edc-82f229e831c4.png)

2.程序的语音可以给个开关（有些人的办公场景是需要开启声音的）；
3.翻译后的弹窗提醒，当用户阅读完成后可以手动×掉（目前翻译完成后就一直显示，影响后续工作）。
……（我真不是产品经理）

**Comment by miaomiaosoft** [comment]
1. 不支持高分屏的，这是已知无法解决的问题，是编程工具不支持，调节大小也没啥用，你看你的截图不仅是拉大窗口就行，其他的控件都不对了，而且截图和弹窗功能在高分屏下也会异常，建议你在系统上设置此软件不跟随系统DPI除了界面小点功能应该都能正常，文字大小可以在配置里改。
2. 哪个语音？程序提示语音开关可以自己改配置项：提示方式
3. 弹窗默认应该是15秒左右自动关闭的，如果不是就自己改一下配置项：自动隐藏弹窗

**Comment by nancheung97** [comment]
> 1. 不支持高分屏的，这是已知无法解决的问题，是编程工具不支持，调节大小也没啥用，你看你的截图不仅是拉大窗口就行，其他的控件都不对了，而且截图和弹窗功能在高分屏下也会异常，建议你在系统上设置此软件不跟随系统DPI除了界面小点功能应该都能正常，文字大小可以在配置里改。
> 2. 哪个语音？程序提示语音开关可以自己改配置项：提示方式
> 3. 弹窗默认应该是15秒左右自动关闭的，如果不是就自己改一下配置项：自动隐藏弹窗

1. 我修改了dpi设置，截屏是可以正常的，目前确实如你所说，界面小点，如我issues中的截图所示，窗体里各选项的字很小看不清，当然我现在除了字比较小之外，别的都能正常使用了，所以我想，如果可以自由调节窗口的大小或许能解决这一问题。

2，3如你所说已解决，谢谢。
