### ISSUE TITLE
【有一个bug有啊】

### ISSUE THREAD

**Issue by 990721830** [miaomiaosoft/PandaOCR#8]
![snipaste20181120_235925](https://user-images.githubusercontent.com/25548230/48785940-b5d26100-ed20-11e8-871c-10d570f39ff5.jpg)
【启用弹窗提示】勾子不点的情况下截图直接电脑卡住...
只能重启解决...
你测试的时候确保没有重要文件正在作业...

**Comment by miaomiaosoft** [comment]
是个BUG，快捷键调用任务管理器可以关闭，不用害怕
https://github.com/miaomiaosoft/PandaOCR/releases/tag/1.9.2
