### ISSUE TITLE
怎么联系你？

### ISSUE THREAD

**Issue by qiudiss** [miaomiaosoft/PandaOCR#80]
我们想在我们软件里开你这软件的入口~
怎么联系？

**Comment by miaomiaosoft** [comment]
可以先说下大概啥事，如果你是正规软件我是不建议调用这个的，因为很多已知问题无法解决，你可以看看https://github.com/miaomiaosoft/PandaOCR/issues/62

**Comment by qiudiss** [comment]
无所谓的  我们只是给用户简单应用

![image](https://user-images.githubusercontent.com/45060738/68746350-6244db80-0633-11ea-8f81-80b04e52a87d.png)

**Comment by miaomiaosoft** [comment]
那你直接调用就行了，如果不想你的用户接收到更新提示可以在配置里关掉

**Comment by qiudiss** [comment]
有考虑商业版本嘛？

**Comment by miaomiaosoft** [comment]
暂时没考虑，因为就像上面说的，有很多解决不了的问题，我不想浪费你钱，再者我懒，甚至有些隐藏功能我都没公开
