### ISSUE TITLE
在高级截图时不能完全隐藏程序窗口

### ISSUE THREAD

**Issue by 371401674** [miaomiaosoft/PandaOCR#81]
wind10系统，pandaocr2.43在高级截图时程序窗口有一半挡住了想要识别的地方，如果不点高级截图的话，矩形框就不能拉满屏，在wind7系统没有这种现象。

**Comment by miaomiaosoft** [comment]
有人反馈过，你应该是高分屏吧，这软件对高分屏支持不好，下一个版本会试图改善

**Comment by 371401674** [comment]
> 有人反馈过，你应该是高分屏吧，这软件对高分屏支持不好，下一个版本会试图改善

谢谢你的回复，试了一下，把分辨率改到1024*768的时候可以使用了，但是屏幕会变小，很难看

**Comment by miaomiaosoft** [comment]
新版尝试修复截图时主窗口不隐藏的问题，但是高分屏上的显示问题这个无法解决
