### ISSUE TITLE
最新版的腾讯翻译和有道翻译用个人ABI翻译无结果。

### ISSUE THREAD

**Issue by picturehome** [miaomiaosoft/PandaOCR#84]
如题。

**Comment by miaomiaosoft** [comment]
需要提供你申请的API供我测试

**Comment by picturehome** [comment]
可以，怎么发给你？

**Comment by miaomiaosoft** [comment]
直接发这就行，我看到后会帮你删除

**Comment by picturehome** [comment]
腾讯翻译ID=2124105052
腾讯翻译KEY=Hydw8fGLMqP8K3Ev
有道翻译KEY=5f9ca65b7d50c725
有道翻译SECRET=rNhINEzWrGSW33OsIxRgUja1ccAjTsdc

**Comment by miaomiaosoft** [comment]
OK收到，我看看先

**Comment by miaomiaosoft** [comment]
新版已经更新修复，你的腾讯API是翻译君的，引擎版本那里记得选2
