### ISSUE TITLE
希望增加騰訊優圖API版和OCR.space的API版/直書文字支持

### ISSUE THREAD

**Issue by Yusei-StarDust** [miaomiaosoft/PandaOCR#85]
因為有識別直書文字/豎排文字的需求，而就我所知以上列出的這兩個可以識別直書文字。另外測試使用騰訊OCR AI版，雖然可以識別出直書文字沒錯，但卻是從左行到右行而不是從右到左……

**Comment by miaomiaosoft** [comment]
直书应该有道OCR支持的比较好，你可以试试这个
OCR.space是没有API版的，只内置了一个演示版，因为识别速度在大陆太慢了，所以没加
腾讯这个问题我处理不了，其实所有OCR我都没办法处理左右识别的问题，我只是调用OCR的接口，至于返回什么格式或是识别质量得看OCR自身的识别能力，我顶多只能纠正一下换行的排版而已

**Comment by Yusei-StarDust** [comment]
是這樣，謝謝建議！不過有道OCR似乎是要付費才能使用……因為個人的需求沒有要到付費的程度，然後騰訊優圖有每日500次免費識別又能識別直書的樣子，所以才希望也有個API版，當然這取決於作者您的開發意願啦……

**Comment by miaomiaosoft** [comment]
有道演示版可以用啊，不用付费
另外似乎我没正确理解你的意思，你是要我增加腾讯优图和SPACEOCR的API版本么？
