### ISSUE TITLE
能不能识别后自动弹出窗口

### ISSUE THREAD

**Issue by cherub0507** [miaomiaosoft/PandaOCR#86]
截图OCR以后能不能自动弹出识别结果的窗口？
现在如果最小化到右下角，识别以后必须再去点一次才能获取识别结果。
烦请大神考虑增加这个功能，非常感谢！

**Comment by miaomiaosoft** [comment]
不是有自动弹窗功能么，这功能就是干这个的
如果你是高分屏，那弹窗功能可能会失效，如果是这样我没法解决，那你就不要关闭窗口，应该最小化就行
