### ISSUE TITLE
软件是否开源

### ISSUE THREAD

**Issue by VKingi** [miaomiaosoft/PandaOCR#87]
你好
1. 请问软件现在有计划开源吗？
2. 软件界面请问使用的是什么框架、使用的是易语言开发的吗？

**Comment by miaomiaosoft** [comment]
本来是开源，但后来遇到些恶心人恶心事就觉得没心情了
易语言
没框架，纯组件

**Comment by bihubihu** [comment]
好的，和天若差不多吗？
