### ISSUE TITLE
搜狗OCR识别错误

### ISSUE THREAD

**Issue by iPixelOldC** [miaomiaosoft/PandaOCR#88]
搜狗OCR识别错误，无法识别，提示更换引擎。
钱已经冲过了，软件设置的是API版，翻译正常使用及扣费成功。
其次改为演示版是可以正常使用的。

**Comment by miaomiaosoft** [comment]
那麻烦提供下你申请的ID和KEY给我测试

**Comment by iPixelOldC** [comment]
额，搜狗的我没发现哪里能重置，所以不好意思，不能给你。话说你用你自己的或者新申请一个不就可以测试了
如果你那里可以，那就是我这边设置问题，如果有空，不嫌麻烦，告诉我你是怎么弄的就好了。
如果你也不行，那就是软件本身的问题。




------------------&nbsp;Original&nbsp;------------------

**Comment by iPixelOldC** [comment]
![图片](https://user-images.githubusercontent.com/13417924/69901571-6ce6cb00-13be-11ea-8861-d96b9f60359c.png)
配置文件

**Comment by iPixelOldC** [comment]
![图片](https://user-images.githubusercontent.com/13417924/69901582-9ef82d00-13be-11ea-93f7-4e3e4f71ecdb.png)
账号内充值情况

**Comment by miaomiaosoft** [comment]
配置是没问题的

提供的话我方便找到问题在哪，一般也就用你十次左右
我个人的使用量还用不到API版本，其次我不太喜欢给网站提供手机号
不提供的话我只能盲猜盲修了
应该都有删除重建KEY的功能吧，你再找找

**Comment by iPixelOldC** [comment]
暂时没找到，我刚刚写邮件问客服了，还没回复

**Comment by iPixelOldC** [comment]
- 客服还是没回话。
- 我刚刚用官网例程，测试了我的PID和KEY，测试成功，扣费也是正常的。

> {"result":[{"groupID":0,"idx":0,"content":"图片二进制内容进行base64编码后的字符串\n","frame":["2,4","312,4","312,22","2,22"]}],"success":1,"zly":"zly","ocr_time":567.5270557403564,"id":"2638056814776156160","lang":"zh-CHS","direction":0}

**Comment by iPixelOldC** [comment]
...貌似得加它QQ群，找群内技术支持，才可能可以重置。。。不过既然我配置文件对了，官网例程跑通了，大概应该不是我这边的问题吧，所以是不是你那边弄错了啥东西？

**Comment by miaomiaosoft** [comment]
哥们，我要KEY就是用来解决我这边的问题啊，你以为我是要来自己用的么
之前就是按官方文档写的，后来有人给了一个KEY测试是可用的，现在出错有可能是官方接口做了什么修改
没有KEY我没法找出是哪有改动，就算盲目修复了也得拿KEY测试一下是否成功才好发新版啊

那个KEY不包含你的个人信息，只是一组随机数字而已，我测试也就用几次而已，用不了几毛钱吧，不知道为什么你这么纠结

**Comment by iPixelOldC** [comment]
不不不，钱不是问题，问题是，我不想直接暴露一个我无法轻易重置的东西，如果这个东西可以重置，你为了修bug，把钱用完，我都无所谓。如果你要API文档的话，我这边试着传份mht文件或者截图给你

**Comment by miaomiaosoft** [comment]
我看到就帮你删除，除了我还能暴露给几个人
既然都纠结那就不用修了
我就义务劳动还整这么复杂
没心情，懒的修了

**Comment by iPixelOldC** [comment]
行吧。。。文档就扔这里了，反正我早就买了白描。。。不过你要是开源，我就给你修了。。。把txt改为html就能用了。（并且话说我不想暴露这玩意，不就和你不想把电话暴露给搜狗，不是一样的吗？你自己都不愿意把这种风险信息给一个大公司，凭什么要求我，把这种东西交给，你一个陌生人？？？将心比心，互相理解，不行吗？）
[文本识别文档-接入文档.txt](https://github.com/miaomiaosoft/PandaOCR/files/3908226/-.txt)


[文本识别文档-常见问题.txt](https://github.com/miaomiaosoft/PandaOCR/files/3908225/-.txt)

**Comment by miaomiaosoft** [comment]
我就笑了，KEY并不能反查到个人信息，你怎么拿来和手机号比？你觉得你这逻辑说的通么？
文档是公开的，我自己就能看到，谢谢

**Comment by iPixelOldC** [comment]
文档都给你了？？？？逻辑全部在这里，官网例程，我已经跑通了？？？你按照官网例程重写相关代码？然后发个测试版，我自己测试不就行了。要是好了，我直接告诉你不就行了，没好，你加个日志不就可以了，接口有返回错误信息啊

**Comment by miaomiaosoft** [comment]
“并且，这个问题没解决，你关issue干嘛？”

我连这个权力都没有？
我是故意不给你解决么，你昨天提供的话我当场就给你修好了。
这就一个人软件，属于爱用不用，你应该也是成年人，大家都自觉一点事情不早解决了

我内置那么多接口我会不知道哪里容易出问题么，给KEY只是减少浪费你我的时间，有时按文档写可能因一个编码也会出问题，我编译一次传你一次再测试有问题再打回循环修复
你的时间可能不值钱，我的时间可值

扯这么多真是浪费时间，咱俩都挺杠，聊不来，就算你现在给KEY我也不乐意给你修了，就这么着吧，不用再回了，周末是用来好好享受的，不是给人免费劳力还罗里八索的

**Comment by iPixelOldC** [comment]
不是，Issue是汇报bug的地方，没修的bug的相关issue为什么要关闭？你可以不帮我解决，可以不去修理。但直接去关闭....你项目的管理手段我不太理解...还是说你把这货当工单系统了.....要真是这样....那行吧，我误解了。然后这也是我最后的回复，你的软件我是不会用了，等我考试周过了，我自己写个去.....

**Comment by miaomiaosoft** [comment]
不，不会有坑，因为我会修，但不是为了你而修，你懂我的意思不
再多说都无益，免费修BUG整到最后还可能得罪你我图个啥呢
这issue也会被删除
