### ISSUE TITLE
截图区域BUG

### ISSUE THREAD

**Issue by Artniner** [miaomiaosoft/PandaOCR#89]
战神K680E-G6D2截图截不到屏幕右侧和下侧，分辨率1920x1080，大概只能截到1530x863的位置

**Comment by miaomiaosoft** [comment]
试试高级截图，听说可以截全
禁用系统DPI参考：https://github.com/miaomiaosoft/PandaOCR/issues/17#issuecomment-480382706

**Comment by Artniner** [comment]
感谢！解决了，不过新版Win10设置改了
![BUG](https://user-images.githubusercontent.com/51869733/69966493-7b192080-1551-11ea-9a8f-f9df5b6894a9.png)
