### ISSUE TITLE
想请教一下开发者关于段落优化的问题

### ISSUE THREAD

**Issue by Chandler-Lu** [miaomiaosoft/PandaOCR#90]
开发者您好，最近用各种接口制作了macOS端的OCR工具，但是在段落优化方面没有想到什么好的思路，也确实没有找到相关的参考。
目前做了一个简易的判断，当返回的数组末尾是特定标点符号的时候不换行，但是测试下来还是没有您的软件优化的好。
因此想请教您一下这方面的思路，谢谢！

**Comment by miaomiaosoft** [comment]
其实思路和你说的是一样的，结尾是句号或感叹号就换行，否则就合并
区别之处可能在于合并的时候我检测了文本属于中文还是英文，英文的话给结尾加个空格，对之后的翻译有好处

**Comment by Chandler-Lu** [comment]
感谢～第二条确实是我没想到，我再滚去研究研究:joy:
