### ISSUE TITLE
希望添加点击单词真人发音和词根功能

### ISSUE THREAD

**Issue by lsz7575** [miaomiaosoft/PandaOCR#91]
可以作为一个插件来搞,需要就添加不需要就不加,类似wox..

真人发音
https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/generic?q=GENERIC

词根词源
https://www.youdict.com/w/analyse

至于api怎么来我不知道..我只是个啥也不懂的小白..
网络搜索菜单中添加两个网站也行... =  =

**Comment by miaomiaosoft** [comment]
新版加了
先划词选中单词，再右键 - 网络搜索 - 剑桥词典
也可以直接划词后朗读
