### ISSUE TITLE
监听文本和监听两者一次后出现卡住问题...

### ISSUE THREAD

**Issue by Noah1995** [miaomiaosoft/PandaOCR#93]
监听文本和监听两者一次后出现卡住问题...
监听图像似乎没有问题...

**Comment by Noah1995** [comment]
![image](https://user-images.githubusercontent.com/25548230/71313751-f6e2fa80-2477-11ea-9950-1f46022b6628.png)

**Comment by miaomiaosoft** [comment]
应该不是这里的问题
感觉是弹窗功能会偶尔导致卡死
具体还找不到原因

**Comment by Noah1995** [comment]
之前也有卡住的问题...
后来我记得你修复了...
我昨天打开的时候又卡住了...
https://github.com/miaomiaosoft/PandaOCR/issues/36#issuecomment-512695005

**Comment by miaomiaosoft** [comment]
可以试试关掉朗读，和将窗口关闭至托盘用用看
现在怀疑这两个地方导致
