### ISSUE TITLE
双屏在使用高级截图时窗口会跳到第二屏幕上

### ISSUE THREAD

**Issue by slipingblue** [miaomiaosoft/PandaOCR#96]
双屏截图时，点击“截图识别”或截图热键，窗口会出现在第二屏幕的固定x坐标和与主窗口刚才位置相同的y坐标上，使第二屏幕的显示内容被遮挡。上一版本没有该问题。

**Comment by slipingblue** [comment]
说错,在试了多个版本后,发现2.40没有这个问题

**Comment by miaomiaosoft** [comment]
从你的描述我不太明白啥问题
大概是说识别后主窗口会重新显示并遮挡弹窗？
你可以试试修改配置：
截图隐藏窗口=0

或者在截图前隐藏主窗口（点关闭按钮）

**Comment by slipingblue** [comment]
> 从你的描述我不太明白啥问题
> 大概是说识别后主窗口会重新显示并遮挡弹窗？
> 你可以试试修改配置：
> 截图隐藏窗口=0
> 
> 或者在截图前隐藏主窗口（点关闭按钮）

emmm...我再描述一下,就是PandaOCR在显示器1上---点击截图识别想要截取显示器2上的内容(高级截图)---PandaOCR出现在显示器2上,会遮挡住要截取的内容
大概就是这样的.

还有一个问题,就是当我的鼠标出现在显示器2的上面时,也会触发截图,虽然我已经关掉了边角触发

**Comment by miaomiaosoft** [comment]
双屏的问题其实我是无法解决的，我没有双屏也不知道如何从代码上区别
暂时没有直接解决办法，但可以试试间接解决
问题一试试就像上面说的方法
问题二既然关闭无效不如设置边角为左下角

**Comment by slipingblue** [comment]
> 双屏的问题其实我是无法解决的，我没有双屏也不知道如何从代码上区别
> 暂时没有直接解决办法，但可以试试间接解决
> 问题一试试就像上面说的方法
> 问题二既然关闭无效不如设置边角为左下角

好的,谢谢0.0
不过我发现2.40版本的用起来并没有那些问题,应该还是会继续用这个版本吧
感谢你的程序,读起文章来快了很多 thx
