### ISSUE TITLE
主窗口太小了，电脑分辨率高点打开主窗口上面的字都看不清，不能放大主窗口

### ISSUE THREAD

**Issue by caodongyu** [miaomiaosoft/PandaOCR#97]
``主窗口太小了，电脑分辨率高点打开主窗口上面的字都看不清，不能放大主窗口

**Comment by miaomiaosoft** [comment]
不支持高分屏，你可以把识别和翻译的字体大小增大，将就用吧

**Comment by caodongyu** [comment]
我发现应该不是分辨率的问题，应该和显示器大小有关，我用一体机（21寸）打开主窗口显示还可以，字体都比较清晰，我用的索菲打开主窗口文字都看不到（太小了）
