### ISSUE TITLE
电脑连接扩展屏时有BUG

### ISSUE THREAD

**Issue by Delayless** [miaomiaosoft/PandaOCR#98]
感谢作者，这是我用过的最好的翻译软件，最喜欢的就是截图识别，但是目前发现有两处BUG。
1. 我电脑连接的两块屏幕。当我完成了一次截图翻译，他会马上自动再一次进入截图状态，按Esc取消截图后还是会再一次自动进入截图操作。这个bug貌似是只要我把鼠标移到第二块屏幕就会出现，就像是明明要按自定义按键（ALT+1）触发截图，却好像是把光标移到拓展屏上就会触发一样。
2. 同样是连接两块屏幕的时候，第二块屏幕无法截图识别，除非打开”高级截图方式“，但是普通截图翻译会更方便一点，不需要二次确认。
希望作者能在下一个版本修复，谢谢您。

ps:另外为了排除按键冲突，我把除浏览器以外的其他所有软件都关闭了。

**Comment by Delayless** [comment]
问题一的现象打个比方，明明是自定义按键（ALT+1）触发截图，却好像是把光标移到拓展屏上就会触发一样。

**Comment by miaomiaosoft** [comment]
我没有双屏，不知道要如何从代码上解决

1. 这个问题可能与默认启用的“边角触发截图”功能有关，你修改一下配置把它关掉：
边角触发截图=0
边角触发禁用=EXE|1.EXE

2. 没有双屏，解决不了，高级截图其实就是直接调用旧版的QQ截图

**Comment by miaomiaosoft** [comment]
另外提醒下 alt+1热键可能会与默认启用的 ”固定截图热键=alt+1“ 冲突，修改一下关掉：
固定截图热键=0

如果没冲突就无视

**Comment by Delayless** [comment]
感谢感谢，关闭边角触发好像解决了第一个问题。
第二个问题应该是您开发或者调用的截图工具（非高级截图）的BUG，如果能修复会更好（我挺喜欢这个截图十字架的）。
另外我想到了一个退而求其次的方案，在高级截图松开鼠标左键之后程序自动回车，这样就不需要多此一举的二次确认了，大部分用户也不会用到这个来作为截图工具编辑截图吧。

**Comment by miaomiaosoft** [comment]
高级截图就是为了截图后可能需要修改截取范围或简单编辑的人提供的，你的想法理论上应该可行但自动回车完成那其他功能就没用了
非高级截图的BUG可能修不了，本身这个编程语言对多屏、高分屏这些支持都不太好

高级截图后你不用专程去点那个完成按钮，直接双击截取的区域就可以结束，习惯下应该也挺方便的

**Comment by Delayless** [comment]
好的
