### ISSUE TITLE
全屏状态下使用固定截图会跳出切换到pandaocr

### ISSUE THREAD

**Issue by betgo** [miaomiaosoft/PandaOCR#99]
请问怎样避免跳出?
1.将panda隐藏之后也会跳出程序,但不会显示panda程序窗口.

**Comment by miaomiaosoft** [comment]
如果是游戏你要设置为窗口化全屏而不是全屏

**Comment by betgo** [comment]
游戏窗口化,使用截图也会跳出切换程序,重新点击游戏屏幕才能继续
浏览器全屏却不会 :)

**Comment by miaomiaosoft** [comment]
改一下配置：
恢复焦点窗口=1
